### ISSUE TITLE
Internal Security Audit

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#110]
Before v2.0 release, @defuse will perform an audit of the code.

**Comment by paragonie-scott** [comment]
As will I, to the best of my ability. :)

**Comment by defuse** [comment]
I started some of this while reviewing my own PR, see comments https://github.com/defuse/php-encryption/pull/212#discussion_r59108165 https://github.com/defuse/php-encryption/pull/212#discussion_r59108233 https://github.com/defuse/php-encryption/pull/212#discussion_r59108540

**Comment by defuse** [comment]
As part of the audit I should also think about what unit tests we could add.

**Comment by larowlan** [comment]
I'm willing to work in said tests, with guidance

**Comment by defuse** [comment]
The code is basically frozen now, so we can start reviewing it for security and telling people to review it. I *would* like to have security review of the documentation I'm writing, especially https://github.com/defuse/php-encryption/blob/v2-add-documentation/docs/CryptoDetails.md but it's not as important as review of the code.

**Comment by paragonie-scott** [comment]
`\o/`

**Comment by paragonie-scott** [comment]
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Core.php#L208
  * Is this really the consequence of a broken environment?
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L76
  * Wrong docblock, should be string (should we check the type here too?)
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L97
  * Same as previous
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L246-L276
  * We could probably just calculate ciphertext length once and reduce calls to `mb_strlen()`
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L296
  * This is now a string
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L328
  * This, too, is now a string
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/DerivedKeys.php#L29
  * Should this have a type declaration? Or are we leaving it open for Key|string usage?

Those are the only things I saw.

**Comment by defuse** [comment]
My audit is done, the only thing to come of it is the minor fixes in #261, the vulnerability #263, and the (resolved) question #262.

**Comment by defuse** [comment]
Re: @paragonie-scott's audit results:

* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Core.php#L208
  * Is this really the consequence of a broken environment?
    * **Yes, the semantics of that exception include the library itself as part of the "environment", and if that throws it implies there's a bug in the library.**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L76
  * Wrong docblock, should be string (should we check the type here too?)
    * **Already fixed.**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L97
  * Same as previous
    * **Already fixed.**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L246-L276
  * We could probably just calculate ciphertext length once and reduce calls to `mb_strlen()`
    * **Agreed, but wontfix because it's just performance and we don't have the bandwidth to fix it.**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L296
  * This is now a string
    * **Fixed in #261**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/Crypto.php#L328
  * This, too, is now a string
    * **Fixed in #261**
* https://github.com/defuse/php-encryption/blob/1cdd27d2300c6d4212c15e2fae41ce9a7728716b/src/DerivedKeys.php#L29
  * Should this have a type declaration? Or are we leaving it open for Key|string usage?
    * **Those should both be string, added docs in #261**.

Thanks!!

**Comment by defuse** [comment]
Okay, we've both audited it. Internal security audit over!
