### ISSUE TITLE
Use a type to store the config, not an array.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#112]
An array can silently-ish fail when we look up an entry that doesn't exist. We should instead be calling a method on an object, so that it fails very loudly.

**Comment by paragonie-scott** [comment]
Yeah, that makes a lot more sense.

**Comment by defuse** [comment]
Here's *exactly* why this is important:

https://github.com/defuse/php-encryption/commit/6e72941a8a96e237cc1a493dd48031e10c0b7047

Had I not caught that bug while writing unit tests, it would've been possible to change a ciphertext's header to say version "0.0", and it would've tried to use a null config (probably making it possible to forge ciphertexts).

**Comment by defuse** [comment]
Done in #116.
