### ISSUE TITLE
Test cases for backwards compatibility attack prevention

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#117]
Ensure

- Trying to decrypt a legacy ciphertext with `decrypt()` generates an exception.
- Test the logic in `getVersionConfigFromHeader()` to make sure the version-greater-than checking logic is correct.

**Comment by paragonie-scott** [comment]
I should note that the file headers are included in the HMAC, so tampering with that should return an InvalidCiphertextException.

**Comment by defuse** [comment]
See here for a great example of a backwards compatibility attack that bypassed TLS's MAC over the entire conversation: https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf (logjam). For us the potential threat is:

1. In some version X, we discover that the MAC key is weak, or the hash function used in that version is broken.
2. We fix that in version X+1 but still allow decryption of version-X ciphertexts.
3. But since the MAC was broken in X, all X+1 ciphertexts can be downgraded to version X.

If that ever actually did happen, we'd have to disallow automatic decryption of version X (it would still be fine to automatically detect and decrypt X+1, X+2, X+3, etc.), and make the user do a special call to decrypt version X ciphertexts. Hence the code I added to make it easy to specify the minimum version you're allowed to auto-detect.

**Comment by defuse** [comment]
The unit tests I wrote for this caught a security bug! Good thing I wrote them.
