### ISSUE TITLE
Use PHPUnit for tests

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#119]
What we're doing for tests currently is not scalable.

@paragonie-scott: Is it okay if I violate the GPL and copy https://github.com/paragonie/halite/blob/master/test/phpunit.sh into this project?

**Comment by defuse** [comment]
Wait, that wouldn't be violating the GPL, since the script is its own source code, so there's no problem with bundling it.

**Comment by defuse** [comment]
In #116, all of the tests except for the stream ones are moved into PHPUnit. I also substantially improved the test coverage.

**Comment by defuse** [comment]
In order to close this ticket, the file tests have to be moved into PHPunit (and expanded to include things like wrong-key decryption, ciphertext tampering, etc.)

**Comment by paragonie-scott** [comment]
Even if you *were* violating GPL here, I'd release it to you under WTFPL.

**Comment by defuse** [comment]
We're now using PHPunit for tests (except for the runtime tests)! Yay!
