### ISSUE TITLE
Add some defense-in-depth to incrementCounter()

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#121]
`incrementCounter()` is such a crucial function that it should check the types and sizes of its arguments. In particular, it should also check that `$inc + 255` is representable an integer (this occurs when the rightmost byte is `0xFF`, and after that we never have to worry about overflow since the sum is shifted right by 8, and the sum in the next iteration can at most increase the number of bits by 1).

**Comment by defuse** [comment]
This is done in #116.

Reviewer: Before closing, please think if there are any more test cases that should be added!

**Comment by paragonie-scott** [comment]
Aside from the failure caused by #22 (and possibly any errors that failure is hiding), this looks very good to me. I like the way you organize everything. :+1:

**Comment by defuse** [comment]
I think the tests are pretty good. The internal and external audits should give good coverage of this function and suggest more tests if there are any to be made.
