### ISSUE TITLE
PHPUnit needs PHP >= 5.6 so Travis is broken on older versions.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#122]
For example: https://travis-ci.org/defuse/php-encryption/jobs/85855211

```
Begin Unit Testing

This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.

The command "./test.sh" exited with 1.

Done. Your build exited with 1.
```

Fuck.

Is there an older version of PHPUnit that works on 5.4?

**Comment by paragonie-scott** [comment]
Yes. Hold on. Someone made a similar patch to one of my projects.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/blob/master/tests/phpunit.sh#L39-L53

**Comment by defuse** [comment]
Thank you! Fixed.

**Comment by defuse** [comment]
Confirmed fixed.
