### ISSUE TITLE
Verify that padding is stripped off correctly when decrypting legacy ciphertexts

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#123]
Looking at the code, OpenSSL would have to use PKCS#7 by default for decrypting CBC mode. Is that what it does?

**Comment by defuse** [comment]
(There's a test case that checks decryption works, but I want to understand why it's working on the code level.)

**Comment by paragonie-scott** [comment]
Yes, [OpenSSL does PKCS#7 padding for you](https://3v4l.org/X1nPu).

**Comment by defuse** [comment]
Awesome! And great way of demonstrating it.
