### ISSUE TITLE
Prevent Partial Reads and Writes

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#125]
See also: [Halite's `File::readBytes()` and `File::writeBytes()`](https://github.com/paragonie/halite/blob/ee5e92ee65dfebf26b7d8c559921ce2a5d4cf76c/src/File.php#L973-L1041) API for reference.

This could greatly reduce the amount of `if ($result === false)` lines by making a separate method for stream reading/writing that throws an exception if it can't proceed.

**Comment by defuse** [comment]
That looks good. I'll take it and modify it to fit within this project. Thanks!

**Comment by defuse** [comment]
Oh there might already be a PR for this issue.

**Comment by paragonie-scott** [comment]
Yeah, I made #129 a few hours ago. :P

**Comment by paragonie-scott** [comment]
This is a duplicate of #114
