### ISSUE TITLE
Decide whether or not to make a StackTraceProtector object for keys.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#126]
@paragonie-scott commented: https://github.com/defuse/php-encryption/issues/97#issuecomment-148881544

That's a good point. We should see if it's correct, and if not see if there's any way to structure the key object that would make it correct.

**Comment by defuse** [comment]
[Awesome, it works!](https://3v4l.org/Abue1)

So: As long as we're not deep enough down (i.e. we haven't stripped the key out of the Key object or passed one of the derived keys as an argument yet) it won't get leaked.

Is it worth making an internal `StackTraceProtector` class that just holds an arbitrary variable in a private member and using that for all the keys?

**Comment by paragonie-scott** [comment]
There's also this, but I think a lot of people would get upset if we actually used this: https://3v4l.org/454gF

**Comment by defuse** [comment]
That's clever. Why do you think people would get upset?

**Comment by paragonie-scott** [comment]
It's abusing a language feature, it's an antipattern, it violates our purist sense of morality, it's "magic", it's witchcraft. Any or all of the above.

**Comment by defuse** [comment]
All of those heuristics (like don't do crazy shit, don't violate purist senses of morality, don't use magic etc.) are simply tools used in practice to make it more likely the complex code you're writing is correct. If we eschew them, we should have an indepndent argument for correctness, so:

1. Is it guaranteed to always return the correct value? (I think this is obvious, since otherwise static variables would be broken -- and we use them elsewhere too).
2. Is it guaranteed to always protect the key? (less obvious: PHP could conceptually dump the values of static variables the class depends on in future versions... but maybe the default var_dump() format and tostring formats and serialize formats explicitly say this will never happen in the future, or maybe there's some technical reason it won't)
3. Does putting the key in a static variable expose it to extra risk? (for example, if PHP has a method for obtaining the values of all static variables in the process, and some code decides to dump them all out)

**Comment by paragonie-scott** [comment]
1. Barring a memory corruption vulnerability that clobbers the zval, yes.
2. Unless the exception is triggered by `key()`, it should never be leaked.
3. I'd ask the folks who maintain xdebug if they have a way to look into the staticvars in a function or method, but I'm inclined to say "no".

Bonus: We could add a destructor that zeroes it from memory. :)

**Comment by paragonie-scott** [comment]
Updated: https://3v4l.org/UrndH

Uses `spl_object_hash($this)` so two instances of the same object don't clobber each other.

**Comment by defuse** [comment]
We're already doing this (the `Key` class) so this can be closed.
