### ISSUE TITLE
File still uses old string keys, not Key objects.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#132]
The `File` class should only accept keys by way of `Key`.

**Comment by paragonie-scott** [comment]
PR incoming soon :)

**Comment by paragonie-scott** [comment]
I ended up folding this into #129 via https://github.com/paragonie/php-encryption/commit/3017bf5d4a885f4f9ce6024eb8c23e6491f63578

**Comment by defuse** [comment]
Feel free to add the review-needed label to the ticket once there's a PR open, btw. It's awesome to look at the ticket list and see all of the things that are about to be finished :)

**Comment by defuse** [comment]
It'll also motivate me to review the PR.

**Comment by defuse** [comment]
This is done
