### ISSUE TITLE
Testing of `File` is insufficient.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#133]
While trying to reproduce another issue, I added a `return;` line after the `encryptResource()` call in `encryptFile()`. The tests for file didn't catch this!

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/php-encryption/commit/081f0101c680b097d34c0a3374d8e2f4ffb47c3a

**Comment by defuse** [comment]
Hmmm... On second thought, maybe I don't want the tests to have caught those bugs. That bug is hard to catch, since it's only a resource leak. Now the interface sort of tricks the user into thinking they need to check the return value when they don't. But there are other higher priority things so I'm going to accept it.

**Comment by paragonie-scott** [comment]
Shall I send a PR to remove the return statements?
