### ISSUE TITLE
Use only pure streaming operations, except for one rewind.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#134]
The `File` encryption and decryption make heavy use of `ftell()` to measure file sizes and get the current position within the file. Does this make it vulnerable to any sort of TOCTTOU attacks? 

Some ideas:

- What if we've opened a file in read-only mode and some other process has it open in append-only mode, and the size changes after we've measured it?
- Others?

What guarantees does "the operating system" provide once we have a file resource? Note that "the operating system" is *every* operating system PHP runs on, so we have to look at the lowest common denominator.

**Comment by paragonie-scott** [comment]
I wonder if we could use [`flock()`](https://secure.php.net/manual/en/function.flock.php) too? :)

**Comment by defuse** [comment]
`flock()` is a different sort of thing. It doesn't actually give you exclusive rights to the file, it's more of a voluntary advisory thing.

**Comment by paragonie-scott** [comment]
Seems like a mostly useless feature then. Hmm.

**Comment by paragonie-scott** [comment]
Could we abstract everything into a stream object? Keep track of the file size and position without relying on `ftell()` etc.?

**Comment by paragonie-scott** [comment]
For example: https://github.com/paragonie/halite/commit/e8c3e3b0893c504cb73d262e41b229d71aae7f1d

https://github.com/paragonie/halite/blob/master/src/Stream/ReadOnlyFile.php

**Comment by defuse** [comment]
This is going to (probably) be fixed in the newer commit, but I want to take a look at the whole thing, not just diffs, before I close it.

**Comment by defuse** [comment]
It's much better now, but we're still using fstat and ftell to know when to pass the different length argument to readBytes. Hmm... Maybe readBytes() should just tell its caller when its reached EOF, so that we can check that and know when to stop. Then, it would be *entirely* stream based, and the only "weird" operation would be a simple rewind back to the beginning.

**Comment by defuse** [comment]
readBytes telling the caller about EOF also makes it super easy to fix #145.

**Comment by defuse** [comment]
Oh... crap. The MAC is at the end. *that's* why we're doing all this crazy fseek() business.

**Comment by defuse** [comment]
I'm just going to put the MAC at the front since the only argument for putting it at the end is to avoid having to store 32 bytes of state during processing, which is a ridiculous argument.

**Comment by defuse** [comment]
Oh wait, we don't know the MAC until we've encrypted everything.

**Comment by defuse** [comment]
We have three options that I can see:

- Spoil the currently fseek-free encryption routine to rewind and fill in the MAC after it's done encrypting, then write a super-clean nearly-fseek-free decrypter.
- Keep the really complicated fseek stuff in the decrypter, and fix all of the logic/arithmetic bugs.
- Keep the fseek-free encryption with the MAC at the end, *and* remove most of the fseeking from decryption, but somehow ignore the last 32 bytes of the file by checking feof only.

**Comment by defuse** [comment]
I'm starting to realize my ideal of not using fseek() is unreasonable or even impossible.

**Comment by defuse** [comment]
Screw it. Let's just audit the hell out of what we have.
