### ISSUE TITLE
HMAC-SHA512?

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#135]
AES-128 and SHA-256 both have a 128-bit security level.

Since we're climbing up from AES-128-CBC to AES-256-CTR, would it also be worthwhile to upgrade to HMAC-SHA-512 if for no other reason than to have a consistent security level of 256 bits?

**Comment by defuse** [comment]
I was thinking about that, but then I remembered MACs have the same security as their output length (not half, since you can't birthday a MAC).

**Comment by paragonie-scott** [comment]
Another point to consider: Length-extension attacks.

The only SHA2-family hash function that isn't known to be vulnerable, that is also available in PHP, is SHA-384.

Should we consider this at all anywhere?

**Comment by defuse** [comment]
I don't think so. HMAC and HKDF's security is based on collision resistance (roughly), so length extensions don't hurt us.
