### ISSUE TITLE
Make sure invalid file ciphertexts always throw InvalidCiphertextException

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#145]
Right now, it seems like an invalid ciphertext could cause a throw of `CannotPerformOperationException`, by causing `readBytes()` to try and read past the end of the file.

One way to do this is to have `readBytes()` take a boolean flag called `$readingCiphertext`, such that, if true, it throws an InvalidCiphertextException, and otherwise it throws an `CannotPerform...`

**Comment by defuse** [comment]
Before fixing this, answer the question: Is it actually possible for a malformed ciphertext to cause this to throw? Or is it *always* a race condition or something that'll do it? If the latter, then we don't need to change the exception.

**Comment by defuse** [comment]
Ugh, there's a confounding problem which is that the file I/O could actually fail, and in that case we wouldn't want to throw an invalid ciphertext exception. So... we have to make sure that the contents/length of the ciphertext file can't cause this exception to be thrown.

**Comment by defuse** [comment]
Wait it's easy to distinguish them: If `fread()` fails, it's an I/O error, but if we reach feof() early it's an invalid ciphertext. And `readBytes()` already distinguishes those two cases. So the boolean flag thing might work.

**Comment by defuse** [comment]
What if the ciphertext is fine and the I/O fails *just* before the call to feof()? If `feof()` would return false, then what I said above doesn't work. Hopefully only an attempt at reading can change the error state.

**Comment by defuse** [comment]
I added some (failing) tests for this in #148.

**Comment by paragonie-scott** [comment]
Tests pass in #170 ;)

**Comment by defuse** [comment]
I don't think this would be a security bug anymore -- at worst the application crashes instead of thinking it's an invalid ciphertext. If you're using this library in an application where that actually matters (i.e. you're trial decrypting ciphertexts and don't want to crash) then you should specifically audit this library to make sure it's reliable in that setting. I think we've done all we reasonably can.
