### ISSUE TITLE
The Key class is confused between normal encryption and file encryption

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#146]
The Key class takes version numbers of normal encryption. Right now the file encryption thing is broken because `File::createNewRandomKey()` still returns a string, not a Key object. We need to either make a different Key class for file encryption, or somehow unify the versioning scheme so it can understand both.

**Comment by paragonie-scott** [comment]
I'd be fine with either approach, but creating a separate key for file encryption might lead to better habits (but then again, this would come at the cost of UX).

**Comment by defuse** [comment]
Wait a second, why is `Crypto.php` passing an argument to `CreateNewRandomKey()`? It doesn't take any arguments.

**Comment by defuse** [comment]
*sigh*, it's not an error in PHP to pass too many arguments: https://bugs.php.net/bug.php?id=13892

**Comment by defuse** [comment]
So, I thought for some reason `Key` depended on the encryption's config because it looked like a ciphertext version was getting passed into that call, but I guess it doesn't.

The key class is abstracting a random string of a certain length. There's no reason that it should depend on what it's being used for. So... this isn't a bug?

**Comment by defuse** [comment]
We should use the same 'Key' class for both. But what happens if we need to use different key sizes in the future?

**Comment by defuse** [comment]
Ok, this isn't a problem. The real problem is #150.
