### ISSUE TITLE
What is maximu size of encrypted text?

### ISSUE THREAD

**Issue by mtangoo** [defuse/php-encryption#149]
I have limitation on storage so I want to know If I can use defuse library. If I have let say 100chars text and I do encrypt it, what is the Maximum resultant characters?
Thanks

**Comment by paragonie-scott** [comment]
**Version 1.x**:

```php
function getExpectedCiphertextSize(int $sizeOfInput) : int
{
    $padding = ($sizeOfInput % 16);
    if ($padding === 0) { // PKCS7
        $padding += 16;
    }
    return 16 // IV
        + 32 // HMAC-SHA-256
        + $sizeOfInput
        + $padding;
}
```
In version 1, you get [152 bytes](https://3v4l.org/aZmJO) of ciphertext. This is raw binary of course. If you want to hex-encode it, double this number (so 304 characters).

**Version 2**:

```php
function getExpectedCiphertextSize(int $sizeOfInput) : int
{
    return 4 // Version tag
        + 16 // IV
        + 16 // HKDF Salt
        + 32 // HMAC-SHA-256
        + $sizeOfInput;
}
```

Version 2 gets rid of PKCS7 padding (by switching from AES-128-CBC to AES-256-CTR), but adds a 4-byte version tag and a 16-byte HKDF salt, so this adds a small bit of overhead but leads to a predictable, one-to-one mapping of plaintext size to ciphertext size.

Your 100 byte message becomes [168 bytes of ciphertext](https://3v4l.org/ovfh4) in version 2.

However, version 2 defaults to hex-encoding, so if you see 336 characters of hex (by default), don't be surprised.

Which should you use? Version 2 is more suitable for encrypting a large number of messages (i.e. more than 2^64) without worrying about IVs/nonces repeating.

**Comment by mtangoo** [comment]
Since its not into production yet, I can go withany version (and hence 2 at your recommendation)
Thanks @paragonie-scott  for clearing this. I really appreciate!

**Comment by pnowosie** [comment]
Issue was closed, but... just in the name of correctness :) I think formula for version 1.x ciphertext should be 
```php
$padding = 16;
$reminder = ($sizeOfInput % 16);
if ($reminder !== 0) { // PKCS7
    $padding -= $reminder;
}
```
So ciphertext size is "full" multiplicity of block size. Am I right?

**Comment by paragonie-scott** [comment]
Probably, yeah. The important thing is that PKCS7 rounds up to the nearest multiple of 16, but if you're exactly at 0, it adds 16 bytes.

**Comment by defuse** [comment]
Can we add those functions to the class and add unit tests for them? #155.
