### ISSUE TITLE
Make Crypto and File check that the 'Key' object they are given is big enough

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#150]
Key can represent keys of different sizes. The code that uses them should check that the key is the right size, i.e. 32 bytes.

**Comment by defuse** [comment]
What if we support different key sizes in the future? It'll be confusing, because you'll be able to pass *some* Key objects, but not others. Maybe 'Key' should be called 'Key256'?

**Comment by paragonie-scott** [comment]
Do you foresee any key size other than 256 bits? :)

**Comment by defuse** [comment]
No, I don't.

**Comment by defuse** [comment]
Ok yeah, let's just make the `Key` object always require 32 bytes.

I wonder if we should do the HKDF in `Key`, too.

**Comment by paragonie-scott** [comment]
`$key->split($salt)` perhaps?

**Comment by defuse** [comment]
There was already a minimum length check of 16. I changed the constant to 32.
