### ISSUE TITLE
Ensure all function calls are fully qualified.

### ISSUE THREAD

**Issue by twistor** [defuse/php-encryption#151]
Throughout the code, it seems that you're trying to use fully qualified function calls.`\sort()` instead of `sort()` I'm guessing this is so that builtin functions can't be overridden with namespace tricks.

The problem is that this isn't done consistently.

While, it's easy enough to go through the code and find them, it would be better to automate this.

I can whip up a simple PHPUnit test that fails if it finds any unqualified function calls using https://github.com/nikic/PHP-Parser.

This also applies to constants, true, false, null, OPENSSL_RAW_DATA. That can be fixed as well, but would make more sense in a followup.

**Comment by paragonie-scott** [comment]
> The problem is that this isn't done consistently.

It should be. I apologize if I overlooked any in my commits.

Let's make the code consistent and explicit :+1:

**Comment by twistor** [comment]
Started hacking on something over here.

#153

**Comment by defuse** [comment]
Done.
