### ISSUE TITLE
How to safely encode key for other use?

### ISSUE THREAD

**Issue by stevenmusumeche** [defuse/php-encryption#156]
I'm attempting to use this library to encrypt a payload that needs to be decrypted on a mobile platform using a pre-shared key.  The documentation says not to call base64_encode, so I'm wondering how I can accomplish this?

**Comment by paragonie-scott** [comment]
https://github.com/defuse/php-encryption/blob/master/tests/encode.php

Note that version 2 is coming out very soon, so this might be more of interest: https://github.com/defuse/php-encryption/blob/v2.0/src/Encoding.php

**Comment by defuse** [comment]
Thanks @paragonie-scott for answering these questions!

**Comment by paragonie-scott** [comment]
@stevenmusumeche https://github.com/defuse/php-encryption/releases/tag/v2.0.0 :)
