### ISSUE TITLE
Version 2 - Goals, Security Properties, etc.

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#158]
At some point, we should identify the advantages of version 2 over version 1, in particular of its security properties.

For example, consider this claim that I'm making about both versions of the library:

-----

* **Version 1**: After encrypting 2^64 blocks with the same key, you could expect a single IV collision. With enough IV collisions, confidentiality is degraded.
* **Version 2**: The addition of a 32-byte salt to the HKDF key splitting means your nonce (formerly IV) birthday collision is inconsequential, since the encryption key for each message will be different (birthday collision chance of 2^128).

Consequence: You should rekey before 2^64 blocks in version 1. You can safely encrypt 2^196 bytes (congruent to 2^192 blocks) of data with version 2 before you get your first (IV, salt) collision.

-----

Is this valid? Are you 100% sure that I'm not overstating the benefit of version 2?

(Like most fleshy humans, I'm blind to my own biases.)

**Comment by defuse** [comment]
A big single message containing 2^128 blocks would not be safe, but 2^128 small messages might be. So the claim has to be modified to take into consideration how those blocks are distributed over different messages. I'll have to think about it more.

**Comment by defuse** [comment]
Closing this ticket because there doesn't appear to be any good criteria for it being closed, and without that, it could be open indefinitely.
