### ISSUE TITLE
Problem Storing Generated Key

### ISSUE THREAD

**Issue by GenerationLabs** [defuse/php-encryption#160]
Hi there,
I've been having some issues with testing 2.0 because the createNewRandomKey() returns an object and not a string. I'd like to save my key into a database for later use, but objects aren't allowed.

I'm curious what you would recommend I do?

Currently I get this error with the following code:
```
$key = Crypto::createNewRandomKey();
$encryptedData = Crypto::Encrypt($text, $key);

PHP Warning:  mb_strlen() expects parameter 1 to be string, object given in ...../crypt/src/Core.php on line 260
```

When I attempt to store it to a DB I get:
```
PHP Catchable fatal error:  Object of class Defuse\Crypto\Key could not be converted to string in
```

In an attempt to possibly use bintoHex() to solve It also comes up with an string related error.
When I var dump I get this from the key:
```
object(Defuse\Crypto\Key)#8 (3) {
  ["key_version_header":"Defuse\Crypto\Key":private]=>
  string(4) "��"
  ["key_bytes":"Defuse\Crypto\Key":private]=>
  string(32) "
&�,���"Ei�:gt�@�cc�
Jݼ��!"
  ["config":"Defuse\Crypto\Key":private]=>
  object(Defuse\Crypto\KeyConfig)#9 (3) {
    ["key_byte_size":"Defuse\Crypto\KeyConfig":private]=>
    int(32)
    ["checksum_hash_function":"Defuse\Crypto\KeyConfig":private]=>
    string(6) "sha256"
    ["checksum_byte_size":"Defuse\Crypto\KeyConfig":private]=>
    int(32)
  }
}
```

Is the encrypt function suppose to take the whole key object or did I miss a step to turn it into a string?

**Comment by paragonie-scott** [comment]
Have you seen [`Key::saveToAsciiSafeString()`](https://github.com/defuse/php-encryption/blob/a32bc7f256f8c905a7d5087c7a6b76d660bbcbdd/src/Key.php#L205-L216) yet?

**Comment by sstok** [comment]
https://github.com/defuse/php-encryption/issues/161#issuecomment-177489467

**Comment by defuse** [comment]
The `PHP Warning:  mb_strlen() expects parameter 1 to be string, object given in` is a bug. I think it's fixed now, I'm not sure.

**Comment by defuse** [comment]
Question has been answered, closing.
