### ISSUE TITLE
Will not run on xampp

### ISSUE THREAD

**Issue by mctrivia** [defuse/php-encryption#162]
Tried running example.php and the only thing I get is:

Cannot safely create a key

Running xampp on windows 10.  PHP Version 5.6.8

tests/encode.php  returns:
Fatal error: Call to undefined function openssl_random_pseudo_bytes() in C:\xampp\htdocs\p\tests\encode.php on line 8

**Comment by kodekrash** [comment]
If openssl_random_pseudo_bytes is undefined, the OpenSSL module for PHP isn't installed.

You can verify this with `extension_loaded( 'openssl' )`

You may also need to install OpenSSL support for Windows.

**Comment by mctrivia** [comment]
yep that is the problem.  works now.
