### ISSUE TITLE
encrypt and decrypt empty string

### ISSUE THREAD

**Issue by robstoll** [defuse/php-encryption#165]
I am getting the following error
`Defuse\Crypto\Exception\InvalidCiphertextException with message 'Ciphertext is too short.'`
When I do the following:

```php
use Defuse\Crypto\Crypto;
$key = Crypto::CreateNewRandomKey();
$crypt= Crypto::encrypt('', $key, true);
$plain = Crypto::decrypt($crypt, $key, true);
```
Is this a bug? A security precaution? If so, why is it possible to encrypt an empty string in the first place?

**Comment by paragonie-scott** [comment]
> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.

Pull request #166 contains a unit test and patch, should we consider "able to encrypt/decrypt empty strings" to be expected behavior.

**Comment by robstoll** [comment]
I am no security expert and hence do not know if information is leaked out while encrypting and decrypting empty strings. If that is not the case, then I do not really see why this should not be expected behaviour

**Comment by paragonie-scott** [comment]
https://3v4l.org/uULd5

**Comment by robstoll** [comment]
Looks good to me, but I am no security expert. Is there a reason why the library does not support it in the first place?

**Comment by paragonie-scott** [comment]
> Is there a reason why the library does not support it in the first place?

That code originally worked on a block cipher in CBC mode, which means the ciphertext size would always be at least 1 block long (16 bytes). Version 2 (which, by the way, you shouldn't be using yet) is switching to CTR mode, which doesn't impose this requirement.

**Comment by robstoll** [comment]
> which, by the way, you shouldn't be using yet
oh really, is 2.x not stable yet? How easy will it be to migrate from 1.x to 2.x? I am using your library in a new project and do not want to migrate to 2.0 after a year or so

**Comment by paragonie-scott** [comment]
> oh really, is 2.x not stable yet?

Nope. It's still a [work in progress](https://github.com/defuse/php-encryption/releases).

> How easy will it be to migrate from 1.x to 2.x?

We have a [`legacyDecrypt()`](https://github.com/defuse/php-encryption/blob/v2.0/src/Crypto.php#L237-L321) method to decrypt old messages so you can re-encrypt them with the new ciphertext format. But one of the big differences is that, instead of a binary string, the encrypt methods now expect a [`Key`](https://github.com/defuse/php-encryption/blob/v2.0/src/Key.php) object.

It will require a little bit of effort, but not a huge reverse-engineering effort to access your old data.

**Comment by defuse** [comment]
Great catch! This is definitely a bug. We should be able to encrypt the empty string!

**Comment by defuse** [comment]
I'm labeling this as a security bug since success/failure might leak to an attacker whether the string was empty or not, which could in certain situations be meaningful information.

**Comment by defuse** [comment]
This is fixed now.
