### ISSUE TITLE
Password encrypting /w cookies

### ISSUE THREAD

**Issue by Kivylius** [defuse/php-encryption#168]
Yes, you already told us, over and over again **not to encrypt the password**, but I need it as plain-text. Let me explain. I'm creating an email client plugin for a CMS (Drupal), the plugin create IMAP/SMTP connections and must use plain-text, so:

* Assume user is logged in and can access `Email_Client` class
* `name`, `email`, `userinfo`, & `serverdata` stored encrypted on sql.
* `password` stored encrypted in a cookie.
* `$keys` are stored as a `const` in the file, and different per install. 
* Assume all `const` are converted using `hexToBin()` function

Here is a bit of suido-ish code to get an example going.

```PHP
final class Email_Client {
    // These keys would be Generated Crypto::binToHex((Crypto::CreateNewRandomKey());
    // When used, it would be: Crypto::hexToBin(const); - I excluded it for tidy code
    const EC_SALT = "c1cdc3081b0d5518b18ae6a76cd6e492"; // hash salt
    const DB_EKEY = "745799c2163be75005485bc141a0b195"; // db encryption key
    const CO_EKEY = "85520a31bc7d896cda9f3d0ee456e552"; // cookie encryption key
    const KN_SKEY = "5bce8ba01e9c4a22748e01728f523f20"; // key name secret key

    public static function register($login, $password){
        //Store the user data in the database, 
        $user = getUser();
        $name = hash_hmac( 'sha256', $user.EC_SALT, KN_SKEY );
        $enc_login = Crypto::encrypt( $login, DB_EKEY )
        $enc_login = base64_encode($enc_login);
        MySQL::Store('user', $name,  $enc_login ); // id: xx, key: $name, value: $enc_login
            
        // Store the userpassword in a cookie.
        self::_setCookie( $name, $password, CO_EKEY );
    }

    public static function login(){
        // Get the user data.
        $user = getUser();
        $name = hash_hmac( 'sha256', $user.EC_SALT, KN_SKEY );
        $enc_login = MySQL::Get('user', $name );
        $enc_login = base64_decode($enc_login);
        $login =  Crypto::decrypt( $enc_login, DB_EKEY );
        
        
        // Get the password from a cookie.
        $password = self::_getCookie( $name, CO_EKEY );
    }
}
```

> 1.  `Userid` is retrieved, its salted and hashed to use as the `name` in the database table -  'user', that has a `id|name|value` structure. The value is encrypted. The set is stored.
> 2.  Using the same `name` as the database table `name` and value (password) is encrypted and stored in a cookie using ([set/get secure cookie](https://gist.github.com/wopot/94e33bdd1d7faaaa56e2))

* Q1 How insecure is this system?
* Q2 Is there an alternative way to do this?
* Q3 Half life 3 confirmed?

**Comment by defuse** [comment]
I linked this in #52 to make sure we see it while we're writing documentation, thanks!
