### ISSUE TITLE
I think something is wrong with the v2.0 branch

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#174]
In all the pull requests I'm seeing comments I left to review some of scott's commits... so the thing people are basing their work off of must be newer than our current v2.0 branch and I'm very confused.

**Comment by defuse** [comment]
Oh I see https://github.com/defuse/php-encryption/pull/171

**Comment by defuse** [comment]
I don't know how to fix it or what's going on, but that's okay. @paragonie-scott Can you write me instructions for how to fix it sometime or just fix it yourself (not today, it's not urgent, and I don't plan to work on v2.0 today so whenever works).

**Comment by defuse** [comment]
Oh maybe github just thinks those are new commits to merge because the hashes are different.

**Comment by defuse** [comment]
Oh.... what happened was on the `master` branch so that's the one I need to fix (probably by a force push)

**Comment by defuse** [comment]
```
d2c3327 master@{0}: commit: Fix exception names everywhere
6e13003 master@{1}: pull github master: Fast-forward
8d063fe master@{2}: merge chriseskow-fix-spelling-errors: Merge made by the 'recursive' strategy.
8640a5f master@{3}: commit: Add better exception messages
5384bae master@{4}: pull github master: Merge made by the 'recursive' strategy.
01eae0a master@{5}: commit: Make CryptoException parent class and use PHP naming convention
7e6383f master@{6}: pull github master: Fast-forward
be0c860 master@{7}: commit: Add newline to end of file
b610a2e master@{8}: commit: Don't re-run tests, indicate the past failure.
10354e8 master@{9}: pull github master: Merge made by the 'recursive' strategy.
24e85c9 master@{10}: commit: Unify the method constant and move the support check into runtimeTest
774e991 master@{11}: commit: Add authors section, since it's not just me
a5ab299 master@{12}: pull github master: Fast-forward
61e88d6 master@{13}: pull github master: Fast-forward
78dfc81 master@{14}: pull github master: Merge made by the 'recursive' strategy.
a7c56b9 master@{15}: commit: Clarify Rule 4
df7ab56 master@{16}: commit: Change audit status
3c7a03f master@{17}: commit: Change audit status
b87737b master@{18}: commit: Add version, author, keywords to composer
93b1dd5 master@{19}: merge composer: Merge made by the 'recursive' strategy.
116deea master@{20}: commit: Strengthen constant changing warning
ab05cfd master@{21}: commit: Try this?
575d0a8 master@{22}: pull github master: Fast-forward
f8cfab8 master@{23}: pull github master: Fast-forward
ff9c48f master@{24}: commit: Make tests actually fail when they fail.
33b9dfb master@{25}: merge multibyte: Fast-forward
7d7f086 master@{26}: commit: Fix #19
8aa6ff9 master@{27}: commit: Add note to the warning
6dad077 master@{28}: commit: Markdownize the rules
```

fuck yeah, that's probably enough info to fix it

**Comment by defuse** [comment]
```
1fa67b9 refs/remotes/github/master@{0}: pull github: fast-forward
399fc4c refs/remotes/github/master@{1}: pull: fast-forward
d2c3327 refs/remotes/github/master@{2}: update by push
6e13003 refs/remotes/github/master@{3}: pull github master: fast-forward
8d063fe refs/remotes/github/master@{4}: update by push
8640a5f refs/remotes/github/master@{5}: update by push
5384bae refs/remotes/github/master@{6}: update by push
16ec922 refs/remotes/github/master@{7}: pull github master: fast-forward
7e6383f refs/remotes/github/master@{8}: pull github: fast-forward
be0c860 refs/remotes/github/master@{9}: update by push
b610a2e refs/remotes/github/master@{10}: update by push
10354e8 refs/remotes/github/master@{11}: update by push
90bb7de refs/remotes/github/master@{12}: pull github master: fast-forward
774e991 refs/remotes/github/master@{13}: update by push
a5ab299 refs/remotes/github/master@{14}: pull github master: fast-forward
61e88d6 refs/remotes/github/master@{15}: pull github: fast-forward
78dfc81 refs/remotes/github/master@{16}: update by push
e59bb70 refs/remotes/github/master@{17}: pull github: fast-forward
df7ab56 refs/remotes/github/master@{18}: update by push
```

**Comment by defuse** [comment]
I think it's 399fc4c

**Comment by defuse** [comment]
Yeah this looks right: https://github.com/defuse/php-encryption/compare/399fc4c...master

I'm going to force push master back to that.

**Comment by paragonie-scott** [comment]
:+1: and again, sorry about that. I'm getting more practice with using git with IDEs so hopefully (for the sake of every project I work on) it won't ever happen again.

**Comment by defuse** [comment]
Okay force pushed it. Hmm... all of this stuff is still showing up in the PRs https://github.com/defuse/php-encryption/pull/163

Might actually be something to do with the v2.0 branch but I'll check tomorrow.

**Comment by defuse** [comment]
No worries @paragonie-scott!

**Comment by defuse** [comment]
When I go to v2.0 on GitHub I get "This branch is 62 commits ahead, 2 commits behind master." This could get really interesting...

**Comment by defuse** [comment]
All the extra commits in the pull request start with d3520c9 so what's special/different about that one.

**Comment by defuse** [comment]
I don't understand because all of the commits (with the same SHA1 hashes) exist in the v2.0 branch so why would GitHub think the pull request is adding them?

**Comment by defuse** [comment]
Somethign to do with " 	Merge pull request #127 from paragonie/v2.0 …

Only one class per file (PSR-1)

	
afda73a"

**Comment by defuse** [comment]
Oh, this might answer it: https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch/35203417

**Comment by defuse** [comment]
Sigh, I guess I'll just close this as a GitHub UI issue.
