### ISSUE TITLE
Make string and file encryption compatible.

### ISSUE THREAD

**Issue by twistor** [defuse/php-encryption#175]
It is surprising that I cannot encrypt a string and write it to a file, then decrypt the file as a file.

Ideally, `Crypto::encrypt()` and `Crypto::decrypt()` would just create an in-memory stream and use `File::encryptResource()` and `File::decryptResource()`. That would significantly reduce the surface area as well.

**Comment by defuse** [comment]
That's not a bad idea... It's been bugging me that there's two separate things each with their own formats to maintain. I was thinking about just dropping the file encryption code altogether, but I might like this idea more.

**Comment by paragonie-scott** [comment]
:+1:

**Comment by defuse** [comment]
Yeah, since it's surprising that they're not compatible, either we do this or we drop the file encryption code. I haven't 100% decided on either one yet.

**Comment by defuse** [comment]
Let's make them compatible. I wonder what PHP has for in-memory streams and such.

**Comment by defuse** [comment]
The docs: https://secure.php.net/manual/en/wrappers.php.php

**Comment by defuse** [comment]
Re-using the file class was a really nice idea in theory but in practice, because of file descriptor limits, it's really unreliable. You wouldn't be able to decrypt many ciphertexts in parallel. See #195.

We have 3 options.

1. Leave things as they are (incompatible implementations).
2. Change the Crypto code to be compatible with the File code.
3. Delete the File code.

**Comment by defuse** [comment]
Given infinite resources (2) is the best option.

**Comment by defuse** [comment]
Option (2) also gives us an increase in confidence because we have two different implementations of the same thing to test against each other.

**Comment by defuse** [comment]
(2) should be easy actually we just have to move the HMAC and use the same version header.

**Comment by defuse** [comment]
I found a (non-security) bug in the File encryption code while working on making them compatible with each other: The IV was incremented before the call to openssl_encrypt, not after.

**Comment by defuse** [comment]
They'll be made compatible by #197.

**Comment by twistor** [comment]
As per #206, I don't think php://memory was causing the file descriptor issues.I don't think it uses real file descriptors. I looked in the PHP source to verify, but that code path is strange, and I had other stuff to do. So, reducing to one code path is still an option.

I'm curious what the tradeoff is of having two implementations vs nearly cutting the codebase in half is.

**Comment by defuse** [comment]
@twistor: Good point. I opened #210 to revisit that decision.

**Comment by twistor** [comment]
I just wanted to confirm that file descriptors aren't an issue. I just ran this locally. I had to jack the memory up, but it worked.

```php
<?php

const LIMIT = 1000000; // One million

$files = [];

for ($i = 0; $i < LIMIT; ++$i) {
  $files[] = fopen('php://memory', 'r+b');
}

print "done\n";
```

**Comment by defuse** [comment]
@twistor thanks for confirming that!

**Comment by defuse** [comment]
Done in #212.
