### ISSUE TITLE
Cannot safely perform encryption

### ISSUE THREAD

**Issue by page3131** [defuse/php-encryption#176]
I am not using SSL is this required?
I am using windows 10, PHPv7,fast cgi.
I am runing the example.php and this is the report.

HTML Error: Cannot safely perform encryption

Exception:
Defuse\Crypto\Exception\CannotPerformOperationException Object ( [message:protected] => [string:Exception:private] => [code:protected] => 0 [file:protected] => php-encryption-master\src\Crypto.php [line:protected] => 618 [trace:Exception:private] => Array ( [0] => Array ( [file] => php-encryption-master\src\Crypto.php [line] => 221 [function] => ensureFunctionExists [class] => Defuse\Crypto\Crypto [type] => :: [args] => Array ( [0] => openssl_get_cipher_methods ) ) [1] => Array ( [file] => php-encryption-master\src\Crypto.php [line] => 65 [function] => runtimeTest [class] => Defuse\Crypto\Crypto [type] => :: [args] => Array ( ) ) [2] => Array ( [file] => php-encryption-master\example.php [line] => 9 [function] => createNewRandomKey [class] => Defuse\Crypto\Crypto [type] => :: [args] => Array ( ) ) ) [previous:Exception:private] => )
Notice: Undefined variable: key in php-encryption-master\example.php on line 20

**Comment by paragonie-scott** [comment]
Are you using master or a stable release?

**Comment by page3131** [comment]
On the download page master is selected how to I find the stable?

**Comment by paragonie-scott** [comment]
https://github.com/defuse/php-encryption/releases/tag/v1.2.1

OR, add this to your composer.json

```json
{
    ...
    "require": {
        ...
        "defuse/php-encryption": "^1.2",
        ...
    }
    ...
}

**Comment by page3131** [comment]
I tried as you suggested and still it is reporting the same error. 
looks like a v2 option is available. I downloaded that. It didn't have a example.php but I ran the autoload.php with no errors. I think it is working at this point.

**Comment by paragonie-scott** [comment]
> looks like a v2 option is available

NO. It's not ready. Use 1.2.1.

**Comment by page3131** [comment]
I figured the same file would work in the 2.0 download so I copied it over from the master and it is still giving the same error. I looked in the branch list and didnt see a 1.2.1 to select for download. Seems like i don't know where to look.

**Comment by paragonie-scott** [comment]
Use [composer](https://getcomposer.org/).

https://packagist.org/packages/defuse/php-encryption

**Comment by page3131** [comment]
same file as in php-encryption-master\example.php copied to php-encryption-2.0\example.php
I will check composer.

**Comment by page3131** [comment]
this is becoming a challenge I was unable to install composer. to download from the composer server. It reported an error on composer install
--
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl

**Comment by page3131** [comment]
i just noticed this https://github.com/defuse/php-encryption/releases/tag/v1.2.1 and downloaded it.

**Comment by page3131** [comment]
I did that and got this message. It is probably somthing with my configuration and not your service.
"php\php.7.0.2x64\php.exe" "php-encryption-1.2.1\example.php"
Cannot safely create a key
Done.

**Comment by page3131** [comment]
I put a print_r statement in there:

CannotPerformOperationException Object ( [message:protected] => [string:Exception:private] => [code:protected] => 0 [file:protected] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\Crypto.php [line:protected] => 577 [trace:Exception:private] => Array ( [0] => Array ( [file] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\Crypto.php [line] => 299 [function] => EnsureConstantExists [class] => Crypto [type] => :: [args] => Array ( [0] => OPENSSL_RAW_DATA ) ) [1] => Array ( [file] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\Crypto.php [line] => 557 [function] => PlainEncrypt [class] => Crypto [type] => :: [args] => Array ( [0] => k���.@���=~s�*�-�W����o�E��Q0�F�\���� R���$E�O��+A{�l7 [1] => +~(�Ҧ��� �O< [2] =>    ) ) [2] => Array ( [file] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\Crypto.php [line] => 269 [function] => AESTestVector [class] => Crypto [type] => :: [args] => Array ( ) ) [3] => Array ( [file] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\Crypto.php [line] => 129 [function] => RuntimeTest [class] => Crypto [type] => :: [args] => Array ( ) ) [4] => Array ( [file] => C:\inetpub\wwwroot\personal\toolKit\scripts\php-encryption-1.2.1\example.php [line] => 4 [function] => CreateNewRandomKey [class] => Crypto [type] => :: [args] => Array ( ) ) ) [previous:Exception:private] => ) Cannot safely create a key

**Comment by page3131** [comment]
Is there a specific php.ini setting that needs to be enabled like extension=defuse.dll

**Comment by paragonie-scott** [comment]
> I am not using SSL is this required?

Yes, you need the OpenSSL extension. If you were using Composer, it would block installation until you enabled it.

**Comment by sstok** [comment]
Just uncomment extension=php_openssl.dll in your php.ini

If it doesn't work, copy ssleay32.dll and libeay32.dll to the c:\Windows\System32 folder (not advised but it should do the trick). REMEMBER to do this for every time you install a new php version as these libraries get outdated in time, and with SSL that's never a good thing.

Better is to install openssl for Windows, like https://indy.fulgan.com/SSL/ (architecture must match php architecture x32 vs x64) and keep it up-to-date.

**Comment by defuse** [comment]
Closing this because it's not an issue with this library but an issue getting the dependencies installed. Thanks to everyone who is helping to do support, by the way, that's giving me a lot more time to work on the code stuff!
