### ISSUE TITLE
File::createNewRandomKey() problem

### ISSUE THREAD

**Issue by aadimator** [defuse/php-encryption#177]
I have been having difficulty using the createNewRandomKey() in the File class. It returns a string and I get an error complaining that encryptFile requires Key but is getting a string. I've spent the last three hours trying to understand and solve the problem.
I should confess that I don't have much experience using PHP. I just have to do a project which requires PHP.
So, could anyone tell me what's the problem and how to solve it?

**Comment by paragonie-scott** [comment]
Why are you using the unfinished version 2 code?

Go back to using `1.2.1` which doesn't have a File API until version 2 comes out. Trust me, there will be fanfare when it does. :)
