### ISSUE TITLE
With v2.0, is there a way to programatically determine the ciphertext length from a given input length?

### ISSUE THREAD

**Issue by madmatt** [defuse/php-encryption#178]
Provided I know the key and the input value, is there a way to determine the `strlen()` of the cipher text output?

I'm asking because I'm writing a DB wrapper to encrypt data at rest, and want the user of this module to give me the initial length (e.g. "Int(5)" which I translate to "Varchar(200)", assuming that 5 characters of input always produces a ciphertext string <200 characters).

Just wondering if this is possible, or if an approximate/maximal value can be determined somehow?

Apologies if this is described somewhere, I've had a quick look but can't see anything.

**Comment by paragonie-scott** [comment]
1. Easy mode: Use `TEXT` and make this not your concern.
2. See #149

**Comment by madmatt** [comment]
Hey @paragonie-scott, that's awesome - thanks! I thought about using TEXT, and we might still do that, but because e.g. MySQL stores TEXT blobs separate from the table, it means if we're encrypting a lot of content, lookups and retrievals are slower. Maybe only millseconds difference, but when you're encrypting 30 different values for thounsands of rows it'll add up. Plus we want to store encrypted, and also filter stuff without having to decrypt and filter in userland code.

I missed #149 when I was looking, thanks!

**Comment by paragonie-scott** [comment]
> Plus we want to store encrypted, and also filter stuff without having to decrypt and filter in userland code.

You'll find that this is going to be a bigger challenge than you probably anticipate anyway. Ciphertexts are indistinguishable from one another in this library.

**Comment by madmatt** [comment]
Interesting - thanks for the heads-up, I'll take a look at that :)
