### ISSUE TITLE
Python Port

### ISSUE THREAD

**Issue by flavioheleno** [defuse/php-encryption#179]
Hi guys,

I've worked on a python port of the library and I was wondering what should I do next in terms of adding it to GitHub and PyPi.

As there isn't a clear LICENSE for php-encryption I'm not sure how to proceed.

Thanks for such a brilliant library btw. :-)

**Comment by paragonie-scott** [comment]
@defuse can answer the licensing question (I think it's BSD?), but your users will be much better served by libsodium than this project.

https://download.libsodium.org/doc/bindings_for_other_languages/index.html

https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium

**Comment by sstok** [comment]
License is MIT ;)
https://github.com/defuse/php-encryption/blob/master/composer.json#L4

**Comment by flavioheleno** [comment]
@paragonie-scott I've opted for this library as I didn't want to reinvent the wheel and its source seemed simple enough to be ported in one go (our application uses both PHP and Python stacks).

@sstok thanks for pointing it out!

@defuse any comments?

**Comment by flavioheleno** [comment]
As @defuse hasn't said anything about this I'm gonna close it.

To whoever is interested on the port, the code is available here: https://github.com/veridu/py-encryption - help, improvements and comments are more than welcome.

**Comment by defuse** [comment]
@flavioheleno It's awesome that you ported this library to Python! Unfortunately I have no time to review it or otherwise "approve of it." For compatibility between languages I, like @paragonie-scott strongly suggest using libsodium instead of porting this library, but you're of course welcome to port the library.
