### ISSUE TITLE
Required php extension list

### ISSUE THREAD

**Issue by AngeIII** [defuse/php-encryption#183]
Please provide minimal php extension list to make this library work.

Note that php.ini-production by default is:
```
;extension=php_bz2.dll
;extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
;extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
;extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
;extension=php_openssl.dll
;extension=php_pdo_firebird.dll
;extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll

; The MIBS data available in the PHP distribution must be installed.
; See http://www.php.net/manual/en/snmp.installation.php
;extension=php_snmp.dll

;extension=php_soap.dll
;extension=php_sockets.dll
;extension=php_sqlite3.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
;extension=php_xsl.dll
```

**Comment by AngeIII** [comment]
As I see the `php_openssl.dll` is required? Is there any library that will work without any php extension?

**Comment by sstok** [comment]
Cryptography is complicated and works best in a low-level language like C(++), you can write an RSA encryption in purely PHP but it would still require GMP/BCMath or be much slower (or not properly secure the first time, as it needs proper auditing from others).

If you don't have OpenSSL you need to install it, if that's not possible you should fire whoever is blocking it. You can't provide security in a high-level language unless it's provided by an extension.

If you can't rely on your OS's CSPRNG, you can't fix it or put different:

> if the OS's CSPRNG is fucked, you're already fucked and can't prevent being fucked further, so don't bother trying to unfuck that situation - slackmaxell
https://twitter.com/ircmaxell/status/653950793830297603

**Comment by AngeIII** [comment]
Thanks for clarification.
