### ISSUE TITLE
Chance of a new 1.2.x release without the mcrypt extension requirement

### ISSUE THREAD

**Issue by larowlan** [defuse/php-encryption#184]
Any chance of a new 1.2.x release to include #53 in line with https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by paragonie-scott** [comment]
I'm fairly sure the plan is to get 2.0.0 out ASAP then put this in "maintenance-only mode", which basically means it will only be maintained if a security update is necessary. Unfortunately, @defuse hasn't had any spare time to dedicate to this project.

**Comment by larowlan** [comment]
Ok, I'll try and spend some time in the issue queue to assist with time pressure.

**Comment by defuse** [comment]
Yeah, that's the plan.

**Comment by defuse** [comment]
I should be honest and transparent and say that I *do* have spare time, it just isn't going to this project for some reason, for example I spent a few hours this week writing [a toy implementation of some quantum-computer-proof public key crypto](https://github.com/defuse/lwe-pkc) and even more hours reading The Mathematical Theory of Communication.

**Comment by defuse** [comment]
The main psychological blocker is that I'm not confident I can make the file encryption stuff secure. So maybe I should spend a 5-hour timebox on trying to get that done, and if at the end of that timebox I'm not confident in its security, I'll just cut the feature from v2.0.

**Comment by larowlan** [comment]
Ok, and would a non-mcrypt dependent point release for the 1.2 branch be a nice point to call it LTS? `</cheeky>`

Willing to help out with support if that helps

**Comment by defuse** [comment]
Don't have time to do this separately from the 2.0 release, so closing.
