### ISSUE TITLE
Report mb_substr returning false to upstream php and ourSubstr bugs to other code that's copied it

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#189]
The docs don't mention mb_substr can return false, WORSE, it does so differently than substr(). This forced me to add this patch to ourSubstr:

https://github.com/defuse/php-encryption/blob/v2.0/src/Core.php#L298-L307

**Comment by defuse** [comment]
Er, okay, so this depends in a super complicated way on which version of PHP you're using. See the tests: https://github.com/defuse/php-encryption/blob/v2.0/test/unit/CoreTest.php

I honestly came an inch away from ragequitting on this entire library and just deleting it off github. I now believe PHP is not safe to use because it's documentation is incorrect and does not include the subtle differences between versions (and you have no way of finding that out except by comparing source code or testing).

**Comment by paragonie-scott** [comment]
Wow, what a nightmare. I'll add these checks to the other implementations.

**Comment by defuse** [comment]
Minimal test case for the bug report:

```
[firexware@firexware-pc tmp]$ cat test.php 
<?php
$result = mb_substr('abc', 5, 2);
var_dump($result);
[firexware@firexware-pc tmp]$ php -d mbstring.func_overload=0 test.php 
string(0) ""
[firexware@firexware-pc tmp]$ php -d mbstring.func_overload=7 test.php 
bool(false)
[firexware@firexware-pc tmp]$ php -v
PHP 7.0.4 (cli) (built: Mar  5 2016 09:28:27) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by defuse** [comment]
**sigh** there's an even worse bug in mb_substr https://bugs.php.net/bug.php?id=66797

**Comment by defuse** [comment]
Yeah, so it's been impossible to reliably take substrings longer than 4GB (even on 64-bit PHP) since at least before 2014. Adding a check to detect this.

**Comment by defuse** [comment]
Reported the bug I found: https://bugs.php.net/bug.php?id=71971

**Comment by defuse** [comment]
I opened a ticket over in defuse/password-hashing about this and @paragonie-scott knows about it so I think we're done here.
