### ISSUE TITLE
Code cleanup pass

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#198]
Look over all the code, check for:

- Unreachable code (e.g. functions that are never called).
- Files without trailing new lines.
- Tabs that should be spaces.
- Consistent capitalization (e.g. some static methods are CamelCase some are whateverThisIsCalled)
- Comments are correct (and all the methods that need documentation have doc comments).

**Comment by defuse** [comment]
Maybe look up that PSR-2 thing or whatever it is :)

**Comment by larowlan** [comment]
If you want PSR-2 I'm happy to take this on

**Comment by larowlan** [comment]
Or if you want something else, still happy to take it on

**Comment by defuse** [comment]
@larowlan: We want PSR-2. If you're going to do it, do it on top of the branch in #197 since there are some big changes that are about to be merged there.

**Comment by larowlan** [comment]
Will do

**Comment by defuse** [comment]
@larowlan Awesome, thanks!

**Comment by chriseskow** [comment]
I'd recommend using [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), which can automatically modify the code to adhere to PSR-2 standards (among other style changes). You can also add it to composer.json's `require-dev` and add a .php_cs file to configure it and make it easier to run consistently.

**Comment by larowlan** [comment]
Great minds think alike ;)

**Comment by defuse** [comment]
Fix the comments in `File`: https://github.com/defuse/php-encryption/pull/212#discussion_r59108709

**Comment by defuse** [comment]
Also make sure the right kind of exception is being thrown (see #216).

**Comment by defuse** [comment]
What's the standard for those `/**` doc comments? Is there a tool that can generate good documentation from them so that the "single source of truth" is the comments in the code and the documentation people see is generated?

**Comment by defuse** [comment]
Only 9 non-test non-exception files. I'll timebox 20 minutes on each one today.

**Comment by defuse** [comment]
```
$ ack -i 'TODO|FIXME|HACK|XXX' src/ test/
src/KeyOrPassword.php
57:            // TODO: Is reusing the same $salt between PBKDF2 and HKDF acceptable?

src/Crypto.php
20:     * @param string $key // TODO: this is wrong

test/unit/PasswordTest.php
27:    // TODO more tests (of the checksummed encoding, etc.)
```

**Comment by defuse** [comment]
Here's the "standard": https://en.wikipedia.org/wiki/PHPDoc

**Comment by defuse** [comment]
"The Long Description continues for as many lines as desired and may contain HTML markup for display formatting." loooool nope nope nope

**Comment by defuse** [comment]
Done in #220.
