### ISSUE TITLE
Suppress fopen warnings with @?

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#214]
`fopen()` will output a PHP warning when it fails. That's annoying because I'm trying to write a command-line file encryption tool with this library and PHP spits out a warning *and* throws an exception, so I can't give the user a clean error message. Should we add `@` to the `fopen()` calls to suppress the error so that the library only throws exceptions and doesn't generate warnings?

I think so.

**Comment by defuse** [comment]
Also the fact I'm just noticing this says that our tests aren't exercising the file-doesn't-exist cases, and we need to add those tests.

**Comment by narfbg** [comment]
Exceptions thrown by `fopen()`? First time I hear this.

But regardless, the general rule is to never suppress warnings - `display_errors` should be disabled on production environments so that they aren't seen by users, but can still be logged.

**Comment by defuse** [comment]
@narfbg Whoops, I wrote that wrong, I should have written "PHP spits out a warning *and* **we** throw an exception."

Ok, I'll revert my changes.

**Comment by sethbattin** [comment]
Squashing the error output is fine as long as the error is still handled, one way or another.  It sounds like the Exception is doing that.  The @ operator only reduces the error level below the logging threshold, which is exactly what is wanted in this case.

**Comment by narfbg** [comment]
`false` being returned is sufficient for the library itself to handle the condition, but `E_WARNING` messages usually contain information that is *very* useful to users (application developers in this case, obviously).

There are of course cases where error-suppression may be desirable or even unavoidable (`iconv()` comes to mind), but with no specific context here I'm inclined to point out what is considered the current best practice in PHP-land. Hence my previous comment. :)

**Comment by paragonie-scott** [comment]
Throwing an exception is a little bit louder than a warning; it forces developers to either handle it or their app crashes (not failing silently). If we're suppressing an error but throwing an exception with a meaningful/helpful message, that's probably preferable.

**Comment by defuse** [comment]
By suppressing errors we are losing information, e.g. the error message in the warning will be "... is a directory" if you try to open a directory path as a file, and something else if the file doesn't exist. I wonder if there's a way we could get the warning message / data and pack it into the exception we throw?

**Comment by paragonie-scott** [comment]
```php

public function openFile(string $filePath)
{
    if (\is_dir($filePath)) {
        throw new FooException('This is a directory, not a file.');
    }
    // ...
    $fileHandle = @\fopen($filePath, 'r');
    if ($fileHandle === false) {
        throw new BarException('Could not open file');
    }
    return $file;
}
```

**Comment by defuse** [comment]
@paragonie-scott: Are those the only two cases, or could there be other cases like "you don't have permission to open that file" or "that file is a weird thing in /dev that can't be opened" in which case it would still lose error information?

**Comment by paragonie-scott** [comment]
That's what the `// ...` was meant for. :)

We can add all of these cases, but in general: `is_readable()` and `is_writable()` is all the information we really need.

**Comment by defuse** [comment]
Oh, I see. I think I'd probably rather lose information than implement all of those cases :)

**Comment by sethbattin** [comment]
The error message would still be available through `error_get_last`, or via any registered error handler function.  You could acquire the message verbatim for all cases, if it's relevant.  The error level, if @'ed, would be zero, but the message would be intact.

**Comment by defuse** [comment]
@sethbattin: Thanks! I'll give that a try.

**Comment by defuse** [comment]
Done in #220. (Thanks @sethbattin that worked perfectly!)
