### ISSUE TITLE
how to give a new key insted of random key?

### ISSUE THREAD

**Issue by rsmmukesh** [defuse/php-encryption#219]
how to give a new key insted of random key? fixed key

**Comment by rsmmukesh** [comment]
please help me. i want to know whether is possible or not. i want to save password in encrypted format and i want to check when login the user.

**Comment by defuse** [comment]
@rsmmukesh: You don't want to use encryption to store passwords. See here: https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016
