### ISSUE TITLE
Unit test: Checksummed ascii-safe encoding

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#222]

**Comment by larowlan** [comment]
There is implicit test coverage here in KeyTest::testSaveAndLoadKey as it relies on `Encoding::loadBytesFromChecksummedAsciiSafeString` and `Encoding::saveBytesToChecksummedAsciiSafeString`

Do you want an additional test or is that enough?

**Comment by larowlan** [comment]
`\KeyTest::testIncorrectChecksum` also has test for the checksum

**Comment by defuse** [comment]
I think I'll just change that test to test `Encoding::loadBytesFromChecksummedAsciiSafeString` and `Encoding::saveBytesToChecksummedAsciiSafeString` specifically, and get rid of that test for `Key`.

**Comment by larowlan** [comment]
Want me to do it?

**Comment by defuse** [comment]
@larowlan: Sure! Thanks :)

**Comment by defuse** [comment]
#228

**Comment by defuse** [comment]
Done (I didn't merge the pull request since it had unwanted php-cs-fixer changes, I just cherry picked the commit right onto v2.0)
