### ISSUE TITLE
Return value of stream_set_read_buffer and stream_set_write_buffer aren't checked

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#223]
These calls can fail. What are the consequences if they do? If there are no negative consequences, why do we call them? If there are, should we detect the failure and throw an EnvironmentIsBrokenException?

**Comment by defuse** [comment]
Note that the behavior of some other functions depend on whether the stream is buffered or not, so check that.

**Comment by paragonie-scott** [comment]
> What are the consequences if they do?

Performance hit. This has no bearing on how much is actually read or written.

**Comment by defuse** [comment]
Ok, awesome!
