### ISSUE TITLE
Encrypting encryption keys

### ISSUE THREAD

**Issue by LesleyT** [defuse/php-encryption#231]
Hey I'm figuring out a good way to store my encryption keys.
I wanted to create a user specific key on account creation, encrypting those with an application specific encryption key. But so far I haven't figure out a way to encrypt an existing key without breaking the encryption/decryption the library provides.

Any ideas to how I could do this?

**Comment by dcharles525** [comment]
I'm working on a method that encrypts the users private key with their non-hashed password on signup. Then every-time they log in I take the raw password and decrypt it. The private key is then stored in the php session data until logout/timeout. Not sure if this is the best way to do it, but its just a method I thought of.

**Comment by LesleyT** [comment]
Storing the users private key plainly in a session isn't ideal either. You will have to take stuff like session hijacking in consideration. I like the idea though, for a third layer of protection which isn't stored anywhere.

And thanks, somehow you made me think simple and clearly. I was trying to encrypt a generated key to encrypt a message. Instead I just needed to encrypt the message with a generated key. Then encrypt that key with a new one, storing result in the db.

**Comment by LesleyT** [comment]
@dcharles525 after some looking around I found this issue  #161 
I believe this is what you wanted to do? Hope this helps u as well.


$key = hash_pbkdf2(
    'sha256',
    $YOUR_USERS_PASSWORD_HERE,  $A_HARD_CODED_PASSWORD_SALT_MADE_OF_16_OR_MORE_RANDOM_BYTES_UNIQUE_PER_USER,
    100000, // minimum 86000
    16,
    true
);
$cipher = Crypto::encrypt($message, $key);
$plain = Crypto::decrypt($cipher, $key);
var_dump($message === $cipher); // bool(true)

**Comment by dcharles525** [comment]
@LesleyT thanks for finding this!

**Comment by defuse** [comment]
This will be a feature of version 2, there will be a `KeyProtectedByPassword` class.
