### ISSUE TITLE
Make sure PBKDF2 output length is short enough to not be wasting cycles

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#235]
If you ask for too much output length from PBKDF2 it's needlessly slow. I can't remember the details but I think if it's larger than the hash function output size then it basically does all the iterations twice. Check this.

**Comment by redragonx** [comment]
Ok so, I made sure the output length is short enough for your use of SHA-256 (32 bytes) with PBKDF2. And the length should follow these recommendations:

- Must be no more than the native hash's output size
     -   SHA-1 is 20 bytes, SHA-224 is 28 bytes, SHA-256 is 32 bytes, SHA-384 is 48 bytes, SHA-512 is 64 bytes
- Must be no less than your risk tolerance.

References used:

- http://security.stackexchange.com/questions/53115/how-to-know-which-output-length-to-request-from-pbkdf2
- https://www.ietf.org/rfc/rfc2898.txt

**Comment by defuse** [comment]
Thanks!
