### ISSUE TITLE
New tag and dependency guidance needed

### ISSUE THREAD

**Issue by airways** [defuse/php-encryption#237]
Hello there,

Currently the 1.2.1 tag does not have the same namespace structure as master. This seems to be a fairly out of date release. Is it possible to have a new tag created on a stable point?

Also can you provide guidance on what version should be used in readme.md? Currently this is lacking, making getting started a bit harder than it probably should be. A simple encrypt / decrypt example there would also be very helpful.

**Comment by paragonie-scott** [comment]
> Is it possible to have a new tag created on a stable point?

Yes, the new tag will be `2.0.0` and is currently the focus of our development.

* https://github.com/defuse/php-encryption/issues?q=milestone%3A%22v2.0+security+freeze%22
* https://github.com/defuse/php-encryption/milestones/Internal%20Security%20Audit
* https://github.com/defuse/php-encryption/milestones/v2.0%20release

**Comment by defuse** [comment]
The changes on master after 1.2.1 are really minor and aren't worth worrying about. I'd wait for 2.0.0 which is a major improvement (and should be out in 2-3 weeks).

**Comment by airways** [comment]
Excellent, sorry that I missed that information.

So, is it currently safe to use dev-master for a _nearly_ production system?

I suppose the official answer may need to be "no" if this tag hasn't yet been created, which is understandable.

**Comment by defuse** [comment]
If you need to use it right now, use 1.2.1 then upgrade to 2.0.0 after it's released. If you can wait a few weeks then wait for 2.0.0. There's a huge API change between the two so if you track master, everything's going to break once 2.0.0 (currently on the v2.0 branch) gets merged into master.

**Comment by paragonie-scott** [comment]
I would use 1.2.1 until it's ready.

> So, is it currently safe to use dev-master for a *nearly* production system?

Feel free to **test** against `~2.0@dev` (in your composer.json) but I would hold off on deploying it, at all, until it's tagged. We're in a code freeze so nothing *should* change, but if a security change is called for it probably will in a backwards-incompatible-with-current-dev-branch way.

**Comment by paragonie-scott** [comment]
In case you hadn't heard, [2.0.0 is out](https://github.com/defuse/php-encryption/releases/tag/v2.0.0).
