### ISSUE TITLE
Embed the PHPUnit public key

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#239]
Travis tests keep failing because it's not on the keyserver. Just check it in and replace the command that fetches it from the server with one that loads it from the file. (Keep the fingerprint check so that it's easy for someone reading the file to see which fingerprint it corresponds to).

**Comment by paragonie-scott** [comment]
Yeah, that will prevent keyserver problems from incorrectly reporting errors.

**Comment by defuse** [comment]
Done in #226
