### ISSUE TITLE
Doc Review: docs/classes/Crypto.md

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#244]
Review `docs/classes/Crypto.md` for correctness as well as understandability.

**Comment by larowlan** [comment]
nit: one of the params has $raw\_binary instead of $raw_binary

**Comment by larowlan** [comment]
Thoughts on adding some emphasis to 

> We recommend configuring PHP to never output stack traces

?

**Comment by defuse** [comment]
@larowlan: I fixed the backslash issues, thanks for catching that!

What do you mean by emphasis? Italicize it, or word it differently, or explain how it can be done?

**Comment by larowlan** [comment]
Bold maybe? Maybe we could put a section about it in the installing and verifying section.
Because really, all the hard work of this library could be undone by a bad stacktrace

**Comment by stonky** [comment]
Conversely, if you're implementing your own exception handling it's fairly trivial to sanitise your stack trace with a regex (having very recently had to do this for some code using the existing Defuse library). Stack traces can be absolutely invaluable on a live system. So whilst I appreciate that a _very_ strong warning is needed, I don't think it's quite so black and white.

**Comment by paragonie-scott** [comment]
I've fixed systems that were inadvertently logging users' plaintext passwords into Trac, unknown to the developers. They had tried to use a regex to filter out the request contents, but forgot the stack trace.

The simplest fix is to change your authentication API and its usage from

```php
class Foo
{
    public function authenticate(string $username, string $password): int
    {
        // Make the magic happen
    }
}
// ...
$userID = $foo->authenticate($username, $password);
```
to 

```php
class sensitive 
{
    protected $data;
    public function __construct(string $data)
    {
        $this->data = $data;
    }
    
    public function __debugInfo()
    {
        return [];
    }
    
    public function getStringValue()
    {
        return $this->data;
    }
}

class Foo
{
    public function authenticate(string $username, sensitive $password): int
    {
        // Make the magic happen
    }
}
// ...
$userID = $foo->authenticate($username, new sensitive($password));
```

**Comment by paragonie-scott** [comment]
Sidenote: I did this in Airship:

* https://github.com/paragonie/airship/blob/master/src/Engine/Security/HiddenString.php
* https://github.com/paragonie/airship/blob/f47d0373d2ee27d9ed4301fb2a1e78f83c2260a5/src/Engine/Security/Authentication.php#L129

**Comment by paragonie-scott** [comment]
Since this has been reviewed, I'm closing it.
