### ISSUE TITLE
Doc Review: docs/classes/KeyProtectedByPassword.md

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#247]
Review `docs/classes/KeyProtectedByPassword.md` for correctness as well as understandability.

**Comment by paragonie-scott** [comment]
This is good, but I think an example that illustrates the difference between `Key` and `KeyProtectedByPassword` would be helpful. (Outside the classes dir.)

**Comment by defuse** [comment]
The use of `KeyProtectedByPassword` is illustrated in the tutorial, so what I'll do is wait for people to see if people ask for help and answer the most frequent confusions about it.
