### ISSUE TITLE
Doc Review: docs/CryptoDetails.md

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#248]
Review `docs/CryptoDetails.md` for correctness as well as understandability.

**Comment by paragonie-scott** [comment]
It looks correct, and understandable enough for a cryptographer. I don't think most users will need these details, however.

If you want to satisfy their needs, a quick list of the primitives used might be helpful. e.g. https://github.com/paragonie/halite/blob/master/doc/Primitives.md

**Comment by defuse** [comment]
LGTM.
