### ISSUE TITLE
Doc Review: docs/Tutorial.md

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#252]
Review `docs/Tutorial.md` for correctness as well as understandability.

**Comment by larowlan** [comment]
nit:
``` catch (Defuse\Crypto\WrongKeyOrModifiedCiphertextException) {``` is missing the ```$e``` argument

**Comment by larowlan** [comment]
great docs, awesome job

**Comment by defuse** [comment]
Done, made some minor fixes.
