### ISSUE TITLE
Compatibility with other packages for decrypting?

### ISSUE THREAD

**Issue by timstallmann** [defuse/php-encryption#256]
Hi all -- I'm using this library currently to encrypt some data which is sent to another party's Microsoft SQL DB, where it then needs to be decrypted. They're having a lot of trouble properly decrypting the cyphertexts from Crypto::encrypt; I'm guessing because the Crypto output is packaged along with an authentication hash and the IV vector. Is this as simple as taking a substring of Crypto output? Any other advice on how to get the output to play well with other encryption libraries?

**Comment by defuse** [comment]
Hi @timstallmann!

I would recommend using libsodium if you need compatibility with code in other languages. You can get libsodium for just about any language. However if that's not an option, the ciphertext format for version 1 (version 2 is still unreleased) is HMAC (32 bytes) || IV (16 bytes) || CIPHERTEXT (variable number of bytes), where:

- HMAC is the HMAC-SHA256 over IV || CIPHERTEXT.
- IV is a random IV (for AES-128 in CBC mode).
- CIPHERTEXT is the encryption of the plaintext using AES-128 in CBC mode with IV.

The key for the HMAC is derived from the provided key using HKDF: https://github.com/defuse/php-encryption/blob/master/src/Crypto.php#L146

Same for the key for encryption/decryption, with a different info string: https://github.com/defuse/php-encryption/blob/master/src/Crypto.php#L151

**Comment by defuse** [comment]
Here's a link to libsodium: https://github.com/jedisct1/libsodium

If you do go the route of re-implementing the decryption in a different language, please be careful to get it reviewed. Even though it's only decryption there is still opportunity for mistakes to be made.

**Comment by timstallmann** [comment]
Thanks much! I'll point the other developer to this thread.

**Comment by defuse** [comment]
I just realized what I wrote could be interpreted as "libsodium will let you decrypt this library's ciphertexts." That's not the case: You'd have to switch to libsodium on the sending and as well.

**Comment by defuse** [comment]
Also the padding is PKCS#7
