### ISSUE TITLE
Different way of uploading releases

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#257]
See this comment: https://github.com/defuse/php-encryption/pull/226#issuecomment-215970366

(I wasn't aware that GitHub let you upload your own files for releases.)

**Comment by defuse** [comment]
@glensc If you would like to see this happen and have spare cycles to donate, it would be awesome if you could take a shot at adding `random_compat` as a composer dependency and modifying the `.phar` building script to pull `random_compat` down using compser.

**Comment by glensc** [comment]
the PR should be against [v2.0](https://github.com/defuse/php-encryption/tree/v2.0) branch right?

**Comment by defuse** [comment]
@glensc Yep!

**Comment by glensc** [comment]
and you're sure you are against using box.phar to build?

**Comment by defuse** [comment]
I'm not opposed to `box.phar` since I don't know what it is yet, but hopefully it will be easy to look at it and make sure it's generating a `.phar` that accurately represents the source code. Using it is an extra window for a backdoor / vulnerability to get inserted.

**Comment by defuse** [comment]
Done in #264

**Comment by paragonie-scott** [comment]
#264 is closed, so I'm closing this too.
