### ISSUE TITLE
File Chunking

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#26]
This is probably going to be used to encrypt files. Currently, the entire file would have to be loaded into memory. We should support file chunking, once the cool folks over in https://github.com/kaepora/miniLock/issues/2 figure out how to do it safely.

**Comment by defuse** [comment]
Duplicate of #39.

**Comment by pr4xx** [comment]
Does this library provide encryption of large files without filling the memory now? I could not find a definite answer yet.

**Comment by paragonie-scott** [comment]
File.php
