### ISSUE TITLE
Loading the .phar from a web application

### ISSUE THREAD

**Issue by rec0de** [defuse/php-encryption#269]
I guess this is a real noob question, but I have been running into some problems trying to use the library with my website.

When I include the .phar archive into a web application, the first line ("#!/usr/bin/env php") is interpreted as HTML and output to every page I use the library in.

Editing the .phar to remove the first line obviously breaks the signature and so far I haven't found a way to avoid outputting the first line every time the .phar is loaded.

How do I correctly use the library in this scenario?

**Comment by pnowosie** [comment]
Including .phar is described [Option 2 | InstallingAndVerifying.md](https://github.com/defuse/php-encryption/blob/master/docs/InstallingAndVerifying.md)
Have you seen / followed this?

**Comment by rec0de** [comment]
Yes, I did. The problem is that when using require_once(), everything outside of the php tags (i.e. the first line) is output as HTML

**Comment by defuse** [comment]
This is a bug. @glensc do you know of an option to make box not generate this line? Or do I have to add a command to the Makefile that strips that line out?

**Comment by glensc** [comment]
yes, https://github.com/box-project/box2/issues/88

**Comment by glensc** [comment]
and looks like i already mentioned this to you:
https://github.com/paragonie/random_compat/pull/83#issuecomment-177822330

**Comment by glensc** [comment]
see #270

**Comment by defuse** [comment]
@glensc Sorry I missed that before! Thanks for fixing it. I'll close this after I release `2.0.1`.

**Comment by defuse** [comment]
Done! Thanks very much @glensc!
