### ISSUE TITLE
autoload file deleted

### ISSUE THREAD

**Issue by sijpkes** [defuse/php-encryption#276]
The autoload file was deleted in commit b769781c7db43d9b0a0e0adbe98868718c0a7479. This has broken my project.  

Is there a best practice workaround for this (other than replacing with the old autoload.php file)?

**Comment by defuse** [comment]
You can either pull the library in with composer, or use the `.phar` which you can download here: https://github.com/defuse/php-encryption/releases

**Comment by defuse** [comment]
More info: https://github.com/defuse/php-encryption/blob/master/docs/InstallingAndVerifying.md

**Comment by sijpkes** [comment]
Thanks for the info.  It seems just removing the reference to the autoloader file fixed this issue for me. I'm still getting my head around PSR-4.
