### ISSUE TITLE
Is really necessarily keep 12 MB file in tests?

### ISSUE THREAD

**Issue by jakubboucek** [defuse/php-encryption#278]
Because tests are a part of a package, is really necessarily to keep big 12 MB file https://github.com/defuse/php-encryption/blob/master/test/unit/File/large.jpg ?

Can you separate tests (especially these non-integration tests) to `require-dev` package to prevent upload this huge useless file to production?

**Comment by spaze** [comment]
Note: There's #272 to mark tests as `export-ignore`, that should do the trick too.

**Comment by defuse** [comment]
That file isn't really important to test coverage, so I'm just going to delete it.

**Comment by jakubboucek** [comment]
Thank you! It will be make your library very very more effective.
