### ISSUE TITLE
Release v2.0.2

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#281]

**Comment by paragonie-scott** [comment]
PRs I believe can be considered for 2.0.2:

- [ ] #280 
- [ ] #275 
- [ ] #272 
- [ ] #266 

I'm not sure how I feel about #267 and #274 -- they definitely need a more thorough review than I'd feel comfortable with for a patch release (especially since they could become a blocker).

Just my $0.02.

**Comment by defuse** [comment]
I merged all of those including #267 (I'm convinced its safe since it only deletes a method in the main code and changes test code). I agree #274 needs more review.

**Comment by defuse** [comment]
The signing key is on my PC so the actual release will have to wait a couple weeks until I have Internet hooked up in my new place.

**Comment by defuse** [comment]
Oh hey I have internet now so maybe I can do the release soon. :-)

**Comment by defuse** [comment]
v2.0.2 has been released!
