### ISSUE TITLE
Loading .phar archive

### ISSUE THREAD

**Issue by alf007mx** [defuse/php-encryption#285]
Hi!

I've been trying to load the .phar file but it seems not to load the classes.
This is my sample code:

`require_once 'defuse-crypto.phar';`
`$key = Key::createNewRandomKey();`
`echo $key->saveToAsciiSafeString();`

I get the following server response:

Fatal error: Class 'Key' not found in C:\xampp\htdocs\defuse.php on line 2

Hope you can help me.
Thanks.

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30

**Comment by alf007mx** [comment]
It worked when I put the following code:

`$key = \Defuse\Crypto\Key::createNewRandomKey();`
`echo $key->saveToAsciiSafeString();`

**Comment by paragonie-scott** [comment]
You could also make use of the [use](https://secure.php.net/manual/en/language.namespaces.importing.php) language feature.

**Comment by alf007mx** [comment]
Thanks.
