### ISSUE TITLE
Fatal Error CSPRNG

### ISSUE THREAD

**Issue by alf007mx** [defuse/php-encryption#286]
Hi!

I just want to know why I'm getting the following error:

Fatal error: Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system'.

I use the .phar file.

**Comment by paragonie-scott** [comment]
See https://github.com/paragonie/random_compat/issues/109

**Comment by alf007mx** [comment]
Thank you. Once again.

**Comment by alf007mx** [comment]
It worked! Thanks

**Comment by paragonie-scott** [comment]
Glad to hear it. :)
