### ISSUE TITLE
WrongKeyOrModifiedCiphertextException

### ISSUE THREAD

**Issue by alf007mx** [defuse/php-encryption#287]
Hi!

I have the following problem, when I encrypt my file in the web server and after I download it to my local XAMPP application I notice that the content of the file it's different, the size is exactly the same but not the content. I receive the following error:

WrongKeyOrModifiedCiphertextException

How can I achieve to get the same content of the file to decrypt it in my local server?

Thanks.

**Comment by paragonie-scott** [comment]
How are you downloading the file?

**Comment by alf007mx** [comment]
Thanks for the quick response. I get the file form a page hosted in the web server. I have a link to the file inside the app. So a click it and I download the file like if was any other.

**Comment by defuse** [comment]
The bug lies somewhere in the way you're downloading this file, and I have no experience with windows WebClient stuff, so unfortunately I have to close this issue.
