### ISSUE TITLE
PHP 7 requirement

### ISSUE THREAD

**Issue by ElooKoN** [defuse/php-encryption#288]
The description says the library requires PHP 5.4 or newer – isn't that wrong? Since you (only) use random_bytes() PHP 7 is needed. What about a fallback to openssl_random_pseudo_bytes()?

**Comment by paragonie-scott** [comment]
https://github.com/defuse/php-encryption/blob/master/composer.json#L23

**Comment by ElooKoN** [comment]
Thanks, I missed that.

**Comment by defuse** [comment]
Thanks @paragonie-scott!
