### ISSUE TITLE
Static PBKDF2_ITERATIONS

### ISSUE THREAD

**Issue by Schnoffel** [defuse/php-encryption#289]
Currently there are 100,000 iterations set in PBKDF2_ITERATIONS. Wouldn't it be better to save the number of iterations into the header so there are no compatibility issues when increasing the number of iterations at a later date?

**Comment by paragonie-scott** [comment]
> Wouldn't it be better to save the number of iterations into the header so there are no compatibility issues when increasing the number of iterations at a later date?

We sort of do! Just not directly. If we increase the number of iterations, it will be in a future version of the library. In this case, the major/minor version will be the deciding factor here.

Exposing more knobs for people to turn isn't a good idea: It adds API complexity and doesn't greatly improve security. You're more likely to switch to Argon2i (via libsodium) than to increase your PBKDF2 iterations to 200,000 (for example).

**Comment by ElooKoN** [comment]
Thanks for your fast answer, seems you like your project :)

Yes, the version number can do this. I don't see any problem when it is increased all two years or so. API complexity is an argument of course. For that reason I do not use libsodium because the current version of defuse does exactly what I need. It is very clean, understandable and simple written.

**Comment by paragonie-scott** [comment]
> For that reason I do not use libsodium because the current version of defuse does exactly what I need in PHP only. It is very clean, understandable and simple written.

If you want libsodium's features an an interface similar to this one (in terms of usability), check out [Halite](https://github.com/paragonie/halite).

**Comment by paragonie-scott** [comment]
The libraries I recommend are roughly [as stated here](https://paragonie.com/blog/2015/11/choosing-right-cryptography-library-for-your-php-project-guide).

This library is great. Halite does a little more (public key crypto, thanks to libsodium), but was made with the same end goals in mind. Neither is a bad choice.

**Comment by Schnoffel** [comment]
With ›this library is great‹ you mean defuse or Halite?

**Comment by paragonie-scott** [comment]
Defuse.

**Comment by Schnoffel** [comment]
Thank you! So I will also have a look to Halite, currently I implemented Defuse, but I din't know Halite was also developed by you. Good work, thanks for that.

**Comment by defuse** [comment]
I second Halite's awesomeness. Thanks @paragonie-scott for responding to this question!
