### ISSUE TITLE
Bring back autoload.php?

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#297]
From an email I received:

> Thanks for making this library.
> 
> I was using the old version when there was an autoload.php file but now I noticed that the latest version doesn't include this anymore.
> 
> I am now unable to use this library on shared hosting providers since they do not have .phar enabled.
> 
> Would it be possible to bring back the option to use autoload.php?

**Comment by defuse** [comment]
PHP is so confusing. There shouldn't be so many configuration options. When I decided to use `.phar`s I was under the impression that `require`ing it worked in exactly the same situations as a `require`ing a `.php` file did.

**Comment by defuse** [comment]
There is indeed a `--disable-phar` option when you're compiling PHP, *sigh*.

**Comment by paragonie-scott** [comment]
There are still three ways to go:

1. Phar
2. Composer
3. Manual

The difference is that we aren't providing a copy-paste solution for people who have backed themselves into the "do everything manually" corner.

I would recommend just creating a gist with this autoload.php script and point people to it. It's a narrow corner case.

**Comment by paragonie-scott** [comment]
Here's a gist with an autoload.php: https://gist.github.com/paragonie-scott/949daee819bb7f19c50e5e103170b400

**Comment by paragonie-scott** [comment]
I believe this can be closed now that an autoloader is available from the documentation.
