### ISSUE TITLE
KeyProtectedByPassword for authentication

### ISSUE THREAD

**Issue by rec0de** [defuse/php-encryption#298]
In a use case where a KeyProtectedByPassword is stored for every user and unlocked upon login, is it safe to use this Key for authentication instead of a regular password hash?

As far as I can tell, unlocking the key and proving that it can decrypt a given ciphertext should provide the same level of security while storing an additional password hash would only increase attack surface (both the hash and the locked key can be used to check for password validity anyway, so a brute force attacker could choose the one with better cracking performance or known vulnerabilities).

Are there any drawbacks / vulnerabilities to this method?

**Comment by sstok** [comment]
I think you are mixing some concepts here, `KeyProtectedByPassword` is for creating an Encryption key based on a password. As using a password only will not produce enough safety for a good encryption key (length and a same password would produce the same key).

So no you should not use this class for authenticating a user.

**Comment by rec0de** [comment]
Perhaps I didn't explain what I mean enough:
What I wanted to ask was, in a scenario where I have to store a (random) encryption key which is protected by the users password (so that the user can unlock the key and perform encryption & decryption of stored data) *anyway*, is it safe to *also* use this key to verify the validity of the password entered on login (by attempting to unlock the stored key)?
As the KeyProtectedByPassword can only be unlocked and used for decryption by providing the correct user password, this should provide the same level of security as comparing the password to a separate hash, shouldn't it?

**Comment by defuse** [comment]
Yes, storing a `KeyProtectedByPassword` for each user, and then checking their password by attempting to unlock it is safe for user authentication. `KeyProtectedByPassword` uses 100,000 iterations of PBKDF2. 

If you use `KeyProtectedByPassword` *as well as* some other password storage system (e.g. Argon2, scrypt, etc.) for the same password, and the attacker learns both of them, the cracking difficulty is (in most cases) equivalent to whichever one is weakest.
