### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by dnicastro** [defuse/php-encryption#299]
I try to install php-encryption through composer

I run into the same error with a  paragonie/random_compat

  _Problem 1
    - Installation request for defuse/php-encryption 2.0.1 -> satisfiable by defuse/php-encryption[2.0.1].
    - defuse/php-encryption 2.0.1 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.2] but these conflict with your requirements or minimum-stability._

My definition in composer.json for minimum-stability is "dev"
"minimum-stability": "dev"
"defuse/php-encryption": "2.0.1"
.......

Is this to resolve for you or is this an error of my side?

**Comment by paragonie-scott** [comment]
Change your "2.0.1" to "^2.0" and it should work fine.

**Comment by dnicastro** [comment]
Hi.

Thanks for feedback!!

I changed, but error is the same.
I work with Drupal8, but this shouldn't have any effect?

Same error when:
 _composer require defuse/php-encryption_ 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - defuse/php-encryption 2.0.1 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.2] but these conflict with your requirements or minimum-stability.
    - defuse/php-encryption 2.0.0 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.2] but these conflict with your requirements or minimum-stability.
    - Installation request for defuse/php-encryption ^2.0 -> satisfiable by defuse/php-encryption[2.0.0, 2.0.1].

I can't figure out, why the requirements failed

Best regards

**Comment by paragonie-scott** [comment]
Try getting rid of minimum-stability then.

**Comment by paragonie-scott** [comment]
Oh wait, I see the problem.

1. defuse/php-encryption requires random_compat 2
2. drupal requires random_compat 1

Go to your drupal's composer.json and change the version flag for random_compat to `^1|^2`.

**Comment by dnicastro** [comment]
Ok, thank

I did not know drupal also use random_compat.

I have some error, but this is from symfony.

So i try to find a Drupal Patch

 Problem 1
- Conclusion: don't install paragonie/random_compat v2.0.2
- Conclusion: don't install paragonie/random_compat v2.0.1
- Installation request for symfony/yaml ~2.8 -> satisfiable by symfony/yaml[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
- Installation request for symfony-cmf/routing 1.3.* -> satisfiable by symfony-cmf/routing[1.3.0, 1.3.0-RC1, 1.3.0-RC2, 1.3.0-RC3, 1.3.0-RC4, 1.3.x-dev].
- Installation request for drupal/core ~8.0 -> satisfiable by drupal/core[8.0.0, 8.0.0-beta10, 8.0.0-beta11, 8.0.0-beta12, 8.0.0-beta13, 8.0.0-beta14, 8.0.0-beta15, 8.0.0-beta16, 8.0.0-beta6, 8.0.0-beta7, 8.0.0-beta8, 8.0.0-beta9, 8.0.0-rc1, 8.0.0-rc2, 8.0.0-rc3, 8.0.0-rc4, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.0.x-dev, 8.1.0, 8.1.0-beta1, 8.1.0-beta2, 8.1.0-rc1, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.1.7, 8.1.8, 8.1.9, 8.1.x-dev, 8.2.0-beta1, 8.2.0-beta2, 8.2.0-beta3, 8.2.0-rc1, 8.2.x-dev, 8.3.x-dev].
- defuse/php-encryption 2.0.0 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.2].
- defuse/php-encryption 2.0.1 requires paragonie/random_compat ~2.0 -> satisfiable by paragonie/random_compat[v2.0.0, v2.0.1, v2.0.2].
- Conclusion: don't install paragonie/random_compat v2.0.0
- Installation request for defuse/php-encryption ^2.0 -> satisfiable by defuse/php-encryption[2.0.0, 2.0.1].

**Comment by paragonie-scott** [comment]
Try this:

```sh
ack-grep --json random_compat
```

And then in every composer.json, switch the version requirement to `^1|^2`. It's hacky, but because a lot of projects erroneously pin to the v1.x branch instead of the v2.x branch (the latter which doesn't use OpenSSL), these conflicts are inevitable.

**Comment by defuse** [comment]
@paragonie-scott: Thanks again for answering these when I don't have a clue what's going on. :-)

**Comment by defuse** [comment]
Hey @dnicastro, did you get it working? I'm wondering if I can close this issue.

**Comment by achilleas01** [comment]
i verify that the described error remains in drupal 8.26 version. However, i installed the 
drupal 8.3.0-rc1 and the composer error is gone.

**Comment by paragonie-scott** [comment]
http://cgit.drupalcode.org/drupal/tree/core/composer.json?h=8.2.x#n34

Hmm....

**Comment by MandeeraK** [comment]
Mandeeras-MacBook-Pro:php-encryption-master mandeera$ composer --version
Composer version 1.7-dev (4d8b9be5b6a0bda0a3d24c0a6ff89d7ccb26f715) 2018-03-05 22:34:22
Mandeeras-MacBook-Pro:php-encryption-master mandeera$ composer require defuse/php-encryption
Using version ^2.1 for defuse/php-encryption
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package defuse/php-encryption No version set (parsed as 1.0.0) is satisfiable by defuse/php-encryption[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
.
.
.
.
Can I know what I should do to solve this error?

**Comment by defuse** [comment]
Since it's been over a year I'm assuming this problem was worked around / solved. If not, feel free to re-open.
