### ISSUE TITLE
v2.0.2 isn't available on Packagist

### ISSUE THREAD

**Issue by theodorejb** [defuse/php-encryption#307]
The most recent Packagist version is v2.0.1. See https://packagist.org/packages/defuse/php-encryption.

**Comment by defuse** [comment]
Whoops, I forgot to bump the version number up in composer.json.

**Comment by defuse** [comment]
I re-released as version 2.0.3 which is correctly showing up in Packagist: https://packagist.org/packages/defuse/php-encryption

Thank you!
