### ISSUE TITLE
Tutorial should explain the Defuse\Crypto namespace

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#310]
The code example in the Tutorial doesn't work, e.g.

```
$protected_key = KeyProtectedByPassword::createRandomPasswordProtectedKey($password);
```

should be

```
$protected_key = \Defuse\Crypto\KeyProtectedByPassword::createRandomPasswordProtectedKey($password);
```

**Comment by defuse** [comment]
It would be nice if the code in the markdown files could be tested automatically somehow. Someone ought to have thought of testable documentation already... so are there any good tools for that out there?

**Comment by timeglider** [comment]
Here here! I pulled a lot of hair off my head before I found this:
$key = \Defuse\Crypto\Key::createNewRandomKey();
instead of 
$key = Key::createNewRandomKey();

**Comment by paragonie-scott** [comment]
The tutorial has been updated. Is it better now?

**Comment by paragonie-scott** [comment]
It's been a few months since this was fixed. I hope the fix was satisfactory. I'm going to close the issue but feel free to correct me if there's still anything left to do and I will reopen it.
