### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by iyasilias** [defuse/php-encryption#315]
I encrypt this string **Dato Farizan 150.jpg**, works fine.

But to decrypt the encrypted string, I get **Fatal error**: Uncaught exception 'Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException' with message 'Integrity check failed.'

At first I thought it is due to the space in the string, but I tried **DatoFarizan150.jpg**, still the problem persists.

Please help.

**Comment by iyasilias** [comment]
Sorry my bad.

Forget to mention that I've stored the encrypted string in a database. And the reason I get the error is because I use varchar(255) to store the encrypted string, so the encrypted string not fully stored.

So, do you know exactly or estimably how long the encrypted string will be?

**Comment by paragonie-security** [comment]
> So, do you know exactly or estimably how long the encrypted string will be?

```php
$message = Defuse\Crypto\Crypto::encrypt($yourMessage, $yourKey);
var_dump(strlen($message));
```

**Comment by jimmykane** [comment]
@paragonie-scott Someone could have guessed that the length is variable.

**Comment by paragonie-security** [comment]
That's the easiest way to estimate it. (Also, maybe use `TEXT` instead of `VARCHAR(255)`.)

**Comment by iyasilias** [comment]
> Also, maybe use TEXT instead of VARCHAR(255)
Yes that's my solution for now.
