### ISSUE TITLE
Any major drawback(s) to using ~1.0 instead of ~2.0?

### ISSUE THREAD

**Issue by cbj4074** [defuse/php-encryption#317]
Hello!

I don't normally open an issue simply to ask a question, but I don't see any other avenue provided for support. Hopefully, I am in the right place.

Many otherwise-fairly-current projects still require `"paragonie/random_compat": "^1.4"` (using Laravel 5.1 LTS, in this specific case). This dependency seems to preclude the use of `"defuse/php-encryption": "~2.0"`.

Looking only at https://github.com/defuse/php-encryption/compare/v1.2.1...v2.0.0 reveals quite a long list of changes.

In essence, I am wondering whether the authors would discourage the use of the `1.0` series, or whether it should be relatively sound to deploy in a new application.

Thank you for any insight you are able to provide in this regard.

This library looks perfect for what I need; thanks for building it!

**Comment by paragonie-scott** [comment]
This is an overview of what's new: https://paragonie.com/blog/2016/05/defuse-security-s-php-encryption-library-version-2-0-0-released

Version 1 is still secure. Version 2 is just secure for more messages thanks to random HKDF salting.

**Comment by cbj4074** [comment]
Thank you for the quick reply, Scott! I really appreciate it.

Perfect; this link is everything I had hoped to see. Very thorough!

Is there a link to this post in the project documentation? If so, I apologize for making you repeat yourself. If not, it seems worthwhile to add, given how many of us are stuck with aging libraries that require us to install the 1.0 series of this library. Even the FAQ doesn't seem too prominent for a link to this info. :)

I like what I'm seeing on this project. Happy to contribute to whatever extent I'm able!
