### ISSUE TITLE
[QUESTION] Interoperability with Android Java

### ISSUE THREAD

**Issue by temuri416** [defuse/php-encryption#324]
Hi,

Thanks for the excellent library!

My question is whether this library can work to exchange encrypted data with Android device. For example, `Defuse\Crypto\hexToBin()` that's used to encode the key - is there an analogue of it in Java?

Cheers!

** EDIT ** Having looked closely at at the library source I see that the only way to make everything with Android is to write its analogue in Java. Any plans of doing that, by chance? ;)

**Comment by paragonie-scott** [comment]
It wouldn't be hard for @defuse or myself to write this in another language, given a good underlying library that provides the primitives we need (AES-256-CTR, SHA-256, HMAC) and a CSPRNG.

However, we probably don't want to do this *too* much. If we need to upgrade the protocol significantly, we'll need to coordinate to make sure that all implementations receive the update.

If you know anyone willing to sponsor this work, then maybe a plan can be drafted.
