### ISSUE TITLE
Have a C# Encrypt method then Decrypt in PHP

### ISSUE THREAD

**Issue by jonathanS8080** [defuse/php-encryption#327]
Hi,
Is it possible to Encrypt a string in C# using .NET RijndaelManaged and then Decrypt the string in your PHP-encryption? This is an example of the Encrypt method

`  RijndaelManaged myRijndael = new RijndaelManaged();
                myRijndael.BlockSize = 128;
                myRijndael.KeySize = 256;
                myRijndael.Mode = CipherMode.CBC;
                myRijndael.GenerateIV();

                // Generate a random, 8-byte salt
                byte[] randomSalt = new byte[8];
                RNGCryptoServiceProvider saltGen = new RNGCryptoServiceProvider();
                saltGen.GetBytes(randomSalt);

                // Set key
                Rfc2898DeriveBytes keygen = new Rfc2898DeriveBytes(passPhrase, randomSalt, passwordIterations);

                var str = System.Text.Encoding.Default.GetString(keygen.GetBytes(16));
                byte[] toBytes = System.Text.Encoding.ASCII.GetBytes("Nïï}€¶ARç/èÄc¿");  // PHP KEY

                myRijndael.Key = toBytes;// keygen.GetBytes(32);

                // Encrypt and encode
                string cipherText = "";
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, myRijndael.CreateEncryptor(), CryptoStreamMode.Write))
                    {
                        using (StreamWriter sw = new StreamWriter(cs))
                        {
                            sw.Write(plainText);
                        }
                    }

                    // Create a block of data of IV + Salt + Encrypted Data
                    byte[] encData = ms.ToArray();
                    byte[] encFinal = new byte[myRijndael.IV.Length + randomSalt.Length + encData.Length];

                    Buffer.BlockCopy(myRijndael.IV, 0, encFinal, 0, myRijndael.IV.Length);
                    Buffer.BlockCopy(randomSalt, 0, encFinal, myRijndael.IV.Length, randomSalt.Length);
                    Buffer.BlockCopy(encData, 0, encFinal, myRijndael.IV.Length + randomSalt.Length, encData.Length);

                    // Return message
                    cipherText = Convert.ToBase64String(encFinal);
                }

                // Return the encoded version
                return cipherText;

Does anyone know how I could change the code above to match you php-encryption?
Thanks

jon`

**Comment by defuse** [comment]
This information might be useful to you: https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md

Instead of rewriting this library in C#, I recommend using a library that's already cross-platform and has bindings in many languages: libsodium.
