### ISSUE TITLE
Using hash_hkdf() for PHP 7.1.2 and above

### ISSUE THREAD

**Issue by Oire** [defuse/php-encryption#330]
Hello,  
First of all, thanks for this great library!  
I’m tinkering with the code trying to simplify ParagonIe’s [PasswordLock](https://github.com/paragonie/password_lock) to get everything, including password hashing and authenticated encryption, to one single file without breaking the functionality and security.  
And, when looking at the `core::HKDF()` method, I found out that since PHP 7.1.2 there is a built-in [hash_hkdf](http://php.net/manual/en/function.hash-hkdf.php) method.  
Is it worth to use it with appropriate checks? I think so, but just decided to ask before making a PR.  
Thanks!

**Comment by paragonie-scott** [comment]
> Is it worth to use it with appropriate checks?

Yes, using built-in functions will (almost) always give you a non-trivial performance boost.

**Comment by defuse** [comment]
I get really annoyed by GitHub's auto-close feature. After I merge a PR I want to explicitly go back to the issue, make sure it is truly resolved, and *then* close it. I guess I need to update my process to: 

1. Review the PR
2. Look in the PR for whatever magic keywords will make GitHub do this
3. When I see them, go to the ticket and make sure that it's ready to be closed, and if not, either ask the PR creator to remove the magic words or mangle the ticket to make it actually closable once the PR is merged and then merge it.

**Comment by defuse** [comment]
Anyway in this case the issue seems to be closable.

**Comment by Oire** [comment]
@defuse, just a quick suggestion :). If you don't want to be annoyed hundred times more by those who wouldn't observe this rule, just document it either in readme.md or contributing.md, so everyone could know that you personally don't like this auto-closing feature. Thanks for merging my PR, I'm really pleased!
