### ISSUE TITLE
A little help please?

### ISSUE THREAD

**Issue by HawkonDK** [defuse/php-encryption#334]
Uncaught Defuse\Crypto\Exception\BadFormatException: Encoding::hexToBin() input is not a hex string. in phar:///Users/user/Downloads/encrypt/defuse-crypto.phar/src/Encoding.php:65 Stack trace: #0 phar:///Users/user/Downloads/encrypt/defuse-crypto.phar/src/Encoding.php(164): Defuse\Crypto\Encoding::hexToBin('keys.txt') #1 phar:///Users/user/Downloads/encrypt/defuse-crypto.phar/src/Key.php(38): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString('\xDE\xF0\x00\x00', 'keys.txt') #2 /Users/user/Downloads/encrypt/test.php(19): Defuse\Crypto\Key::loadFromAsciiSafeString('keys.txt') #3 /Users/user/Downloads/encrypt/test.php(24): loadEncryptionKeyFromConfig() #4 {main} thrown in phar:///Users/user/Downloads/encrypt/defuse-crypto.phar/src/Encoding.php on line 65

Note: I have removed my own name by /user/

**Comment by paragonie-scott** [comment]
This appears to be a duplicate of #333. Can you please check and see if that solves your problem?

**Comment by HawkonDK** [comment]
nope didn't help but find a way myself ;)

**Comment by defuse** [comment]
Oh, it looks like it was because the actual string `'keys.txt'` was being passed to `loadFromAsciiSafeString`. Yeah, that function expects the actual key string, not a file path.
