### ISSUE TITLE
How to store the key safe?

### ISSUE THREAD

**Issue by HawkonDK** [defuse/php-encryption#336]
How to store the key in a safe way? if you use a file, the hacker could use a terminal or a script to change the permission for the file, if encrypted by the user login, the owner know the key to decrypt everybody's information. 

What to do?

Oh! a litte question:
what crypt technology are used? PGP ? OpenSSL ? mcrypt?

**Comment by defuse** [comment]
What are you using the library to encrypt, and what sorts of security guarantees do you need to provide against what kinds of adversaries?

The library uses OpenSSL with some higher level stuff (e.g. HKDF) implemented in PHP itself.

**Comment by HawkonDK** [comment]
Use it to encrypt person data so the system are ready for the new Europa General Data Protection Regulation (GDPR). but after its are a shopping system the admin need to decrypt some data so they know where to send the item the have buy

**Comment by paragonie-scott** [comment]
> if you use a file, the hacker could use a terminal or a script to change the permission for the file

If an attacker is at this point, anything your PHP scripts can do, an attacker can also do. That's a game over scenario.

**Comment by defuse** [comment]
Yep, encrypting data is only useful when the total system is split into at least two parts: 1. A more-trusted less-likely-to-be-compromised system tasked with performing business logic on the data (e.g. a web server), and 2. A less-trusted more-likely-to-be-compromised system tasked with storing the data (e.g. a database server vulnerable to SQL injection in code on the web server). If a compromise of the data implies a compromise of the key, then there is no point encrypting.
