### ISSUE TITLE
[Important Feature Missing] Curve25519 for the Shared Keys

### ISSUE THREAD

**Issue by vzool** [defuse/php-encryption#337]
Hi,

I'm trying to use your library to encrypt data stream, I generate public & private keys by [Curve25519](https://github.com/lt/PHP-Curve25519) then I tried to import them into [Key](https://github.com/defuse/php-encryption/blob/master/src/Key.php) to encrypt and decrypt by the **Shared Key**.

This is how I generated **Private Key**:
```php
$secret = Key::createNewRandomKey();

$privateKey = $secret->saveToAsciiSafeString();

$publicKey = base64_encode(\Curve25519\publicKey($secret->getRawBytes()));

```

I think the private key is private, I just use what in the library and I feel fine about it, the big issue is for the "Shared Key". I think this is not right because shared key always changing while I'm testing this, and it should not do that.

Here is the snippet for how did I transform Shared Key:

```php
$sharedKey = Key::loadFromAsciiSafeString(Encoding::saveBytesToChecksummedAsciiSafeString(
	Key::KEY_CURRENT_VERSION,
	\Curve25519\sharedKey($myPrivateKey->getRawBytes(), $theirPublic)
));
```

What am I missing?

Thanks

**Comment by paragonie-scott** [comment]
> I think this is not right because shared key always changing while I'm testing this, and it should not do that.

Okay:

> `$secret = Key::createNewRandomKey();`

Your private key isn't static.

**Comment by vzool** [comment]
> Your private key isn't static.

Yes, I know that.... it should be like that, unless it will be useless. ^_^

But, I meant the **Shared Key** it does always change for the same my Private & their Public Key.
I feel that [Encoding::saveBytesToChecksummedAsciiSafeString()](https://github.com/defuse/php-encryption/blob/cf49a331740a35f028c6149c51d9a662e6aa2da5/src/Encoding.php#L121) is not designed to accept pure bytes.

What you think?

**Comment by paragonie-scott** [comment]
Can you show a test case where the same Curve25519 keys produces a different Defuse key?

**Comment by vzool** [comment]
Here is to generate **Private Key** & **Public Key**:
```php
$secret = Key::createNewRandomKey();

$privateKey = $secret->saveToAsciiSafeString();

$publicKey = base64_encode(\Curve25519\publicKey($secret->getRawBytes()));
```

And this to generate **Shared Key**:
```php
$sharedKey = Key::loadFromAsciiSafeString(Encoding::saveBytesToChecksummedAsciiSafeString(
	Key::KEY_CURRENT_VERSION,
	\Curve25519\sharedKey($myPrivateKey->getRawBytes(), $theirPublic)
));
```
In fact, the same code is running in another server.

**Comment by paragonie-scott** [comment]
So, if there is a bug, then:

```php
$sharedKey = Key::loadFromAsciiSafeString(Encoding::saveBytesToChecksummedAsciiSafeString(
	Key::KEY_CURRENT_VERSION,
	\Curve25519\sharedKey($myPrivateKey->getRawBytes(), $theirPublic)
));
$sharedKeyTwo = Key::loadFromAsciiSafeString(Encoding::saveBytesToChecksummedAsciiSafeString(
	Key::KEY_CURRENT_VERSION,
	\Curve25519\sharedKey($myPrivateKey->getRawBytes(), $theirPublic)
));
var_dump(\hash_equals($sharedKey->getRawBytes(), $sharedKeyTwo->getRawbytes());
```

...then that last `var_dump()` is going to produce `bool(false)`?

Otherwise: a non-static keypair is going to produce a non-static shared secret.

**Comment by vzool** [comment]
Ha ha ha, it does work just fine. 

Here is the [complete test](https://gist.github.com/vzool/5f44f44f2a9bdf62e569d296fede7140).
This is why testing is always matter specially in cryptography.

I'm sure now that I missed something important in my code.

Thanks for your help ^_^

**Comment by defuse** [comment]
It seems like you're re-using the same key for two different purposes, once as a Curve25519 private key and again as a key to do encryption with this library. Is that what's happening? That *might* be safe, but using the same key for two different purposes is dangerous since there might be weird interactions between Curve25519 and the crypto in this library that makes it insecure.

**Comment by vzool** [comment]
Yes, I used the same key in two different purposes(**Encryption & Exchange**), but I generated the private keys by the same library which will encrypt & decrypt later, and I think this is important somehow.
Private keys are different and still private for any server, and the main purpose to use Curve25519 is to exchange keys between the servers.
I'm always looking for the best & **Pure PHP Implementation**, but now I'm just aware of this way to exchange the keys, do you have any good alternatives for me? ^_^

Thanks

**Comment by vzool** [comment]
Hay guys,  

I added encrypt & decrypt to  [complete test](https://gist.github.com/vzool/5f44f44f2a9bdf62e569d296fede7140) and it fails. :(

How can I solve this gentlemen?  ^_^

Thanks

**Comment by vzool** [comment]
Error Message:

```
Fatal error: Uncaught exception 'Defuse\Crypto\Exception\EnvironmentIsBrokenException' 
in /opt/lampp/htdocs/test/ExchangeProtocol/vendor/defuse/php-encryption/src/RuntimeTests.php:105 Stack trace: 
#0 /opt/lampp/htdocs/test/ExchangeProtocol/vendor/defuse/php-encryption/src/RuntimeTests.php(60): Defuse\Crypto\RuntimeTests::testEncryptDecrypt() 
#1 /opt/lampp/htdocs/test/ExchangeProtocol/vendor/defuse/php-encryption/src/Crypto.php(178): Defuse\Crypto\RuntimeTests::runtimeTest() 
#2 /opt/lampp/htdocs/test/ExchangeProtocol/vendor/defuse/php-encryption/src/Crypto.php(26): Defuse\Crypto\Crypto::encryptInternal('Salam, Hello & ...', Object(Defuse\Crypto\KeyOrPassword), false) 
#3 /opt/lampp/htdocs/test/ExchangeProtocol/test1.php(55): Defuse\Crypto\Crypto::encrypt('Salam, Hello & ...', Object(Defuse\Crypto\Key)) 
#4 {main} thrown in /opt/lampp/htdocs/test/ExchangeProtocol/vendor/defuse/php-encryption/src/RuntimeTests.php on line 105
```

**Comment by vzool** [comment]
I revised your installation steps, and after I used `require_once('defuse-crypto.phar');` all tests passed just fine.

Is this okey?

**Comment by paragonie-scott** [comment]
Earlier @defuse said,

> It seems like you're re-using the same key for two different purposes, once as a Curve25519 private key and again as a key to do encryption with this library. Is that what's happening? That might be safe, but using the same key for two different purposes is dangerous since there might be weird interactions between Curve25519 and the crypto in this library that makes it insecure.

I'd strongly recommend not doing that. Instead, use the ECDH output (along with both public keys) as an input to a strong cryptographic hash function and use the output as your encryption key.

```php
$clientSharedKey = \ParagonIE_Sodium_Compat::crypto_generichash(
    \ParagonIE_Sodium_Compat::crypto_scalarmult($clientSecret, $serverPublic) .
    $clientPublic .
    $serverPublic
);
$serverSharedKey = \ParagonIE_Sodium_Compat::crypto_generichash(
    \ParagonIE_Sodium_Compat::crypto_scalarmult($serverSecret, $clientPublic) .
    $clientPublic .
    $serverPublic
);
```

The same general strategy of encoding then supplying to `Key::loadFromAsciiSafeString()` is fine. Please don't reuse cryptographic secrets for vastly different protocols.
