### ISSUE TITLE
Feature proposal: command line tool for generating a new key

### ISSUE THREAD

**Issue by chriseskow** [defuse/php-encryption#338]
In one of our projects that uses this library, we have a small PHP script `bin/generate-key.php` which simply generates a new key and prints it out:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$key = Defuse\Crypto\Key::createNewRandomKey();
echo $key->saveToAsciiSafeString(), "\n";
```

I imagine others would have a similar need. Perhaps something like this could be added to this project as a [Composer vendor binary](https://getcomposer.org/doc/articles/vendor-binaries.md) so that one would simply need to run `vendor/bin/generate-defuse-key` (or whatever) to generate a new key.

Thoughts?

**Comment by defuse** [comment]
I think that's a great idea!

**Comment by chriseskow** [comment]
Well, I took an initial stab at creating the script in #342. Bare-bones, but it serves my need.

Should probably update the documentation - I noticed the [tutorial](https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md) has instructions for creating this exact sort of script, so that can be updated. Also, not sure if any sort of tests are necessary.
