### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#339]

**Comment by defuse** [comment]
"Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API." so the next version will be 2.1.0.

**Comment by paragonie-scott** [comment]
Before we tag 2.1.0, can I send a PR to get #322 resolved? I'd also like to make `vimeo/psalm` part of the Travis CI tests (like I do with sodium_compat) so our docblocks are verifiably type safe.

**Comment by defuse** [comment]
Yes, that would be great!

**Comment by defuse** [comment]
Are we ready to release 2.10 or is there anything else that should go in?

**Comment by paragonie-scott** [comment]
I think we're ready.

**Comment by defuse** [comment]
Done, hopefully I did it right: https://github.com/defuse/php-encryption/releases/tag/v2.1.0
