### ISSUE TITLE
Version Tagging

### ISSUE THREAD

**Issue by sarciszewski** [defuse/php-encryption#34]
This is a nice-to-have in case anyone wants to encrypt with version 1.x of this library in 2015 then decrypt it with version 3.x in 2025.

**Comment by defuse** [comment]
+1, there should definitely be version tagging (even if all we do right now is check that it's equal to a constant).

**Comment by sarciszewski** [comment]
So, how would we put it in here? In my own toy implementation, ciphertexts looked like this:

`"A1:[base64IV]:[base64ciphertext]:[base64hmac]"`

**Comment by paragonie-scott** [comment]
I'd like to propose a migration path.

1. Make sure #63 is good, merge it.
2. Copy `Crypto.php` into `Legacy.php`
3. Add version tagging to `Crypto.php`
4. Add version tagging to `File.php`
5. Make sure the documentation (see #52) explains the migration path.

The final result should be released as `2.0.0`.

Thoughts?

**Comment by defuse** [comment]
This is done.

**Comment by DerMika** [comment]
Hi, I have a question.

I've started implementing an application which uses this encryption library to store encrypted values in a database. 

I have added a ~1.2.0 dependency to your library in Composer, but of course I do not want to fall behind on encryption. 

Will I run into problems with my encrypted data when I upgrade to the 2.0.0 release, or will there be a way to migrate my data when upgrading? 

For an application that will go live in one or two months time, what do you suggest I do: work with the 1.2 release and migrate later, or should I rather use the v2.0 branch in my project to avoid problems in the future?
