### ISSUE TITLE
Encrypt/Decrypt from/to app

### ISSUE THREAD

**Issue by AeonDave** [defuse/php-encryption#343]
hello,
is possible, and how i can encrypt a message on a c# app and decrypt with crypto/decrypt sent to an api?
is the algorythm aes or something?
i need to replicate the functions with a library called AArnott/PCLCrypto otherwise app and server can't comunicate.

thank you

**Comment by defuse** [comment]
The encryption details are [here](https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md) although I advise against rewriting this library in C#, there are a lot of nuanced security problems that must be dealt with. Instead I recommend using a library like libsodium which you can get [for php](https://github.com/jedisct1/libsodium-php) and [for C#](https://github.com/adamcaudill/libsodium-net).
