### ISSUE TITLE
Needs an autoloader

### ISSUE THREAD

**Issue by GregJohnStewart** [defuse/php-encryption#344]
Could use an auto loader to include the appropriate files in one file (and in the right order) rather than having to include them all separately.

Code that worked for me as an example (file placed in root of php-encryption project):

    require_once "src/Exception/CryptoException.php";
    require_once "src/Exception/IOException.php";
    require_once "src/Exception/BadFormatException.php";
    require_once "src/Exception/EnvironmentIsBrokenException.php";
    require_once "src/Exception/WrongKeyOrModifiedCiphertextException.php";
    require_once "src/Core.php";
    require_once "src/Crypto.php";
    require_once "src/DerivedKeys.php";
    require_once "src/Key.php";
    require_once "src/KeyOrPassword.php";
    require_once "src/Encoding.php";
    require_once "src/RuntimeTests.php";

**Comment by GregJohnStewart** [comment]
Code that worked for me as an example (file placed in root of php-encryption project):

    require_once "src/Exception/CryptoException.php";
    require_once "src/Exception/IOException.php";
    require_once "src/Exception/BadFormatException.php";
    require_once "src/Exception/EnvironmentIsBrokenException.php";
    require_once "src/Exception/WrongKeyOrModifiedCiphertextException.php";
    require_once "src/Core.php";
    require_once "src/Crypto.php";
    require_once "src/DerivedKeys.php";
    require_once "src/Key.php";
    require_once "src/KeyOrPassword.php";
    require_once "src/Encoding.php";
    require_once "src/RuntimeTests.php";

**Comment by paragonie-scott** [comment]
There is one already, provided by Composer.

```sh
composer require defuse/php-encryption
```

Then

```php
require "vendor/autoload.php";
```

See #297

**Comment by GregJohnStewart** [comment]
What if one isn't using composer? It really can't hurt to have it..

**Comment by paragonie-scott** [comment]
If one isn't using Composer, one probably wrote their own autoloaders anyway and this is a trivial suggestion.

Here you go. https://gist.github.com/paragonie-scott/949daee819bb7f19c50e5e103170b400
