### ISSUE TITLE
Question Encryption

### ISSUE THREAD

**Issue by belukas** [defuse/php-encryption#348]
Hi everyone,
first of all let me say thanks for developing this class!!

I experimented the last days with this class and it works fine. I want to encrypt parts of my mysql Database with it. Now my question: when I encrypt e.g. "Hello World!" several times with the same password protected key, I am always getting a different encrypted value... Am I doing something wrong or is this intentionally?

If it is intentionally, I am having a problem, because I am not able to search in my database any more. For the search I wanted to encrypt the "search term" and then search for this encrypted value. But when the same string gets another encrypted value everytime I encrypt it, this kind of search is not possible.

How do you handle this kind of problem - or what do I do wrong?

Thanks a lot in advance for your answer!!

have a good afternoon!!

**Comment by paragonie-scott** [comment]
> I am always getting a different encrypted value... Am I doing something wrong or is this intentionally?

This is intentional.

> If it is intentionally, I am having a problem, because I am not able to search in my database any more.

https://paragonie.com/white-paper/2015-secure-php-data-encryption#index-encrypted-information

**Comment by paragonie-scott** [comment]
Actually, this might be more helpful than a one paragraph blurb in a two year old paper: https://paragonie.com/blog/2017/05/building-searchable-encrypted-databases-with-php-and-sql

(I just published it. I'm not being forgetful.)
