### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by NicolasCARPi** [defuse/php-encryption#353]
Hello,

I couldn't find any changelog. Could you maybe add one? It's nice to see what are the changes before updating.

Thanks.

~Nico

**Comment by defuse** [comment]
Good point!

I think your best and most accurate source of information for high-level descriptions of changes would be the [merged pull requests](https://github.com/defuse/php-encryption/pulls?q=is%3Apr+is%3Aclosed), but from that search view it's hard to figure out which versions the PRs went into. Maybe using the [compare feature](https://github.com/defuse/php-encryption/compare/v2.0.3...v2.1.0) on the version tags would be more informative. The [releases](https://github.com/defuse/php-encryption/releases) page contains something like a changelog in the description of each release, but there are definitely non-publicly-visible changes that aren't mentioned in there.

Maybe going forward we should have a CHANGELOG.md file and require each pull request to add a link to itself in the changelog file alongside a short description.

**Comment by defuse** [comment]
I couldn't [find any way](https://help.github.com/articles/searching-issues/) to search for pull requests that got merged between two tags, but we can approximate it using the release dates: https://github.com/defuse/php-encryption/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20base%3Amaster%20merged%3A%222016-10-10%20..%202017-05-19%22

**Comment by sethbattin** [comment]
This works fairly well, once silly commits are trimmed out:
https://github.com/defuse/php-encryption/compare/v2.0.3...v2.1.0

**Comment by sethbattin** [comment]
...for merges: `git log --oneline --merges v2.0.3...v.2.1.0`

**Comment by NicolasCARPi** [comment]
Yes, it would be great to have a CHANGELOG.md file. I'm using a service that tells me when a new version is available and it can detect the changelog file and provide me with a link. I think what is important is also to differentiate the fixes from the new features. Just the commit message is not enough imho (unless it begins with Fix or Add…).

**Comment by defuse** [comment]
I'll consider adding a changelog starting with the next major version. 

For now, [semantic versioning](https://semver.org/) applies: if you're on 2.x, you should be able to update to 2.(x+1) without anything breaking as long as you only use documented features, except that the minimum-supported PHP version will increase to the minimum version of PHP that still gets security fixes (so it might not run on older versions). You should assume there are minor bugfixes in a new minor release, but any security-critical (e.g. security vulnerability was found and fixed) will definitely be announced upfront in the README.

**Comment by defuse** [comment]
I agree that this is a good idea and should be there, but I don't have the extra energy to do it so I'm closing this ticket. Thanks for the suggestion!
