### ISSUE TITLE
Run a Usability Study (With Actual Humans)

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#354]
We should do a usability study with real humans. Here are some things I think we can understand better by doing this:

1. Given a task that will need a crypto library, how do real people select which library they are going to use? Do they end up using this library or something else (e.g. built-in PHP functions)?
2. Given a task and told to use this library for it, how do they approach the library and learn how to use it? What problems do they encounter as they're installing the library for use in their project, or while writing code that uses the library? Etc.
3. Given a task for which this library is not suitable (e.g. one that requires asymmetric cryptography), do people realize it and find something else or do they make something broken?

**Comment by SimonEast** [comment]
Great idea. I don't see many open source libraries doing this. 

I was recently made aware of this library after searching StackOverflow for encryption examples. Man there's some awful examples there, but good to see this library noted highly in some of them. My initial impression is that this is a very well constructed and documented library, however I'm not sure what third parties would vouch for it or what popular libraries use it. Is there a list of notable users?

**Comment by paragonie-scott** [comment]
Of particular note: It's used by Joomla since version 3.5, which covers ~3% of websites on the Internet.

**Comment by defuse** [comment]
Here's a good paper to mine for references to related work and study design ideas: https://arxiv.org/abs/1708.08759

**Comment by defuse** [comment]
Some academic research on crypto library API usability exists already: https://www.cl.cam.ac.uk/~rja14/shb17/fahl.pdf (I think I read this a long time ago but I don't remember what the conclusions were). In any case, this library has probably been used enough we can just look at code that's using it to see what the common pitfalls are.
