### ISSUE TITLE
EnvironmentIsBrokenException - how to repair?

### ISSUE THREAD

**Issue by przemek980** [defuse/php-encryption#357]
Hi, I've changed the server, I've change the DNS on domain panel and....:

> in Core.php line 110: Your system does not have a secure random number generator.

Website: www.cloee.pl
Can anyone help?

**Comment by paragonie-scott** [comment]
Please see https://github.com/paragonie/random_compat/issues/112#issuecomment-235025966 which may provide an answer to your question. If not, that snippet may reveal a vital clue.
