### ISSUE TITLE
Shorter encryption string to fit DB constraints

### ISSUE THREAD

**Issue by boris-lapouga** [defuse/php-encryption#361]
Hi,

This is less an issue and more a question/request.
Is there an option to limit the encrypted string length? I'm fine with less security and shorter KEY, but some data that I need to encrypt must fit into a 45 characters length due to DB constraints which I cannot alter.

Thanks

**Comment by defuse** [comment]
Any good encryption scheme would need an overhead of at least 16 bytes for a nonce/IV and at least 16 bytes for an authentication tag (32 bytes total). That would limit you to a maximum message size of 13 bytes, which probably isn't that useful.

Why can't the length be altered? Maybe you could add a separate table for the ciphertexts, and in that 45-character column store the ID of the ciphertext in the ciphertext table?

**Comment by boris-lapouga** [comment]
I see, thanks for clarification.
I can't alter the tables because this is provider's DB, I want to encrypt my customers data that is stored on their side, a mediator DB is an option, but I want to avoid this overhead and encrypt/decrypt on the fly upon request. Will revert to something simple, hopefully script kiddies will not crack it fast. :)

This can be closed, thank you.
