### ISSUE TITLE
README: When is version 2.1.0 supported until?

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#362]
I just realized the README specifies 2.0.0, but really it should be 2.0.x.

Do we extend 2.1.x support until 2019-01-01, or further than that?

**Comment by defuse** [comment]
Here's a support policy I just invented:

1. If new major release comes out (first number in the version changes), we support the old major release for 6 months (with possible exceptions in case of security problems).
2. We promise support for the newest release until FirstNewYearsDayAfter(<release date> + 2 years).
3. A year before that promise expires we extend it by a year.

This has three goals:

- Encourage people to stay with the current version, allowing enough time to upgrade.
- If we disappear, the promise will expire and people will know not to use the library.
- Makes people feel comfortable knowing the library will be supported for at least 1 year into the future.

**Comment by defuse** [comment]
What do you think about that?

**Comment by paragonie-scott** [comment]
I like it. I'm not 100% sure how to codify it in an intuitive way to understand.

**Comment by defuse** [comment]
I think we can just say "The current release is BLAH. It will be maintained until (at least) BLAH." I don't think we need to (or want to) advertise the fact that old versions may be supported.

**Comment by defuse** [comment]
Oh yeah we should update the release instructions to remind ourselves to change the version number in the README.

**Comment by defuse** [comment]
Turned this into a closeable ticket: #387.
