### ISSUE TITLE
What's the best way to check if the key is correct?

### ISSUE THREAD

**Issue by Schnoffel** [defuse/php-encryption#366]
I use an UUID for checking if the AES key, which is provided by the end user, is correct so he does not accidentally use a wrong key to encrypt his files.

The key is stored as `index => hex(UUID . Key)` on user side and as `index => hex(UUID)` on server side.

But I also thought about another possibility: What about decrypting a test file? Isn't that also a proper solution for checking if the encryption key is correct? Maybe a better solution?

**Comment by defuse** [comment]
Decrypting a test file would be a better test. The UUID test could fail if for some reason the client sends up `hex(UUID. DifferentKey)` for the wrong key, but the decrypt test would catch that.
