### ISSUE TITLE
Safe Failure Tests on 5.2 and 5.3.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#37]
Switching to OpenSSL broke 5.2 and 5.3. We don't want to support those versions any more, but we should at least be sure we're not *dangerous* on those versions. Add travis tests for those versions that make sure they fail somehow safe (e.g. by throwing an exception).

https://github.com/defuse/php-encryption/pull/36

**Comment by sarciszewski** [comment]
I think this one should be closed now too.

**Comment by defuse** [comment]
In #74, we removed the 5.2 and 5.3 tests. Re-add them with tests that check that the library isn't doing something dangerous (i.e. it should always throw an exception) on those versions.

**Comment by defuse** [comment]
This is like worrying if the color of your bike shed will make it more likely to get broken into. Closing.
