### ISSUE TITLE
After updating to tls v1.2 loading defuse-crypto.phar causes internal server error

### ISSUE THREAD

**Issue by chrisloughnane** [defuse/php-encryption#370]
PHP 5.6.31
tls, tlsv1.0, tlsv1.1, tlsv1.2

My code continues to work in my dev environment and worked on production until we updated tls. Unfortunately I have no idea where to start to address this issue, has anyone else experienced this?

**Comment by paragonie-security** [comment]
When you say you "updated TLS" do you mean:

* You swapped out OpenSSL for GnuTLS by issuing an OS command to upgrade packages and it swapped one out for the other?
* You changed your OpenSSL version?
* You changed your Apache configuration?
