### ISSUE TITLE
"Cannot initialize a hash context." in PHP 7.2

### ISSUE THREAD

**Issue by julesjanssen** [defuse/php-encryption#374]
Trying to encrypt a file in PHP 7.2 causes the "`Cannot initialize a hash context.`" error.
I created a new key (`Key::createNewRandomKey()`), as the old one was created in PHP 7.1, but that doesn't solve it.

I'm on MacOS 10.13.2 (High Sierra), installed PHP 7.2.0 through homebrew, with v2.1.0 of this library.

Any idea what may cause this problem?

**Comment by paragonie-scott** [comment]
I suspect the change to `HashContext` instead of a `resource` in PHP 7.2's changelog is the culprit.

**Comment by julesjanssen** [comment]
That was fast. And yes, it does look like that's the issue.
Why did I just assume it was `null` or `false`? It is indeed a `HashContext` object.

**Comment by paragonie-scott** [comment]
I can get a patch written tonight, but I don't know when Taylor will be available to review it.

**Comment by julesjanssen** [comment]
No rush. Thank you very much.

**Comment by mbardelmeijer** [comment]
@paragonie-scott did you found some time write a patch? Ran also into this issue :)

**Comment by paragonie-scott** [comment]
It's half-finished because I was focused on other things. Getting tests to pass is a bit tricker than it seemed.

**Comment by sapphirecat** [comment]
Hi, I ran into this bug today, the exception definitely points to src/File.php:522 in a check for `is_resource`.  (We upgraded to PHP 7.2 last week.  This usage happens to be in a system that was recently revived, and so missed all the testing.)

Version 2.1.0, `composer update` indicates we are up-to-date.  What's left to do here?

**Comment by mbardelmeijer** [comment]
We've published our fork with the PHP 7.2 stuff to [`enflow-nl/php-encryption`](https://packagist.org/packages/enflow-nl/php-encryption). Feel free to use that one until it's fixed here.

**Comment by sapphirecat** [comment]
Thanks @mbardelmeijer, I ultimately decided to roll back to PHP 7.1 for this particular system, and I even managed to do it without disrupting anything else we are running.

I decided not to go with your fork, because your last commit removes the backslashes for unspecified “weird behavior” and I suspect that allows someone to define `\Defuse\Crypto\is_resource` to hijack that code.  Say they take the hash context by reference and replace it…

I want to be very careful here.

**Comment by defuse** [comment]
This was fixed by #378.
