### ISSUE TITLE
Failed opening required autoload.php

### ISSUE THREAD

**Issue by ryanapil** [defuse/php-encryption#376]
`Fatal error: require(): Failed opening required 'phar://PATH/library/defuse-crypto.phar/vendor/autoload.php' (include_path='.:/opt/sp/php7.1/lib/php') in PATH/library/defuse-crypto.phar on line 9`

When require_once.

**Comment by defuse** [comment]
Could you provide more details (which version of the library, which version of PHP, your exact code to require the `.phar`, where the `.phar` is on your filesystem, etc.). I just double checked with PHP 5.6 and 5.7 and it worked for me.

**Comment by WebDragon** [comment]
having similar issue here suddenly. PHP 7.1, latest library version 2.2.1, WWWROOT/res/includes is in the $PATH so both 4:require_once("res/includes/defuse-crypto.phar");
 and 11:require_once("defuse-crypto.phar"); are in use, and were previously functional and tested as such.

**Comment by WebDragon** [comment]
bumping server to PHP 7.2 appears to have resolved the issue -- the hosting company may have twiddled some bit on their end that caused things to stop working. Fortunately the remainder of the site is or at least appears to be 7.2-ready.

**Comment by paragonie-scott** [comment]
> Failed opening required 'phar:///home/PATH/public_html/res/includes/defuse-crypto.phar/vendor/autoload.php' 

Interesting. 

(Why can't you just use Composer? You can install locally and then SFTP your `vendor` directory if your hosting provider doesn't let you run `composer update` on their server.)
