### ISSUE TITLE
[Question] Could KeyProtectedByPassword be put in a JWT?

### ISSUE THREAD

**Issue by lifewcody** [defuse/php-encryption#379]
Hello,

Just wondering on security wise, if the user logged in, then their password was used and I got a Key via:

```php
$protected_key = KeyProtectedByPassword::createRandomPasswordProtectedKey($password);
$protected_key_encoded = $protected_key->saveToAsciiSafeString();
```

Is the $protected_key_encoded unique (if a user logs in twice, will the $protected_key_encoded be different?)

I was thinking of referencing it in a MongoDB database with expiring TTL on each document, so when the JWT expires, the protected key expires as well.

I don't want to have the user enter their password every time, that is why I am handing out JWT tokens. I know it would be horrendous to embed the $protected_key_encoded directly in the JWT, but would referencing it in a database be okay, or is there another way for this approach?

**Comment by defuse** [comment]
Yes, the `$protected_key_encoded` will be unique. I don't quite understand the second question, since you will still need the password to recover the `Key` from the `KeyProtectedByPassword`.
