### ISSUE TITLE
Will decrypt be backward compatible in the future?

### ISSUE THREAD

**Issue by mschop** [defuse/php-encryption#380]
Hi all,

Since version 2 of php-encryption, Core::CURRENT_VERSION is prepended to $ciphertext.

Currently, if the version of the cipher is another than the current, an WrontKeyOrModifierCiphertextException is thrown. See:

```
$header = Core::ourSubstr($ciphertext, 0, Core::HEADER_VERSION_SIZE);
if ($header !== Core::CURRENT_VERSION) {
  throw new Ex\WrongKeyOrModifiedCiphertextException(
    'Bad version header.'
  );
}
```

Will php-encryption support decrypting values, generated with an older version than the current? Currently, the code does not support it (I guess, because you didn't change the algo since v2).

Thanks right now!
Best Regards
mschop

**Comment by defuse** [comment]
Yes, it will always be possible to decrypt past versions. The worst case scenario is that you'd have to call a separate function that's specific to decrypting old versions, which would happen if a severe security vulnerability were found in the current decryption function.
