### ISSUE TITLE
Investigate Miscellaneous Possible Issues

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#382]
From the email quoted in #381:

```
PS...
OTHER MINOR ISSUES FOUND:
PHP VERSION REQ: Your documents state a minimum requirement of php5.4. 
However,
the error handling class typeError() (in crypto.php) was not introduced
until php7.
The alternate short array definition (name[elements]) used elsewhere was
not recognised until php5.5.

NO OPENSSL VERSION REQ: Also, the -CTR mode is not supported in openSSL
v0.9.8zf
(what came with php5.4).  I had to figure out that even though openSSL
documents
say aes-ctr-mode support was added in 0.9.7, it appears it wasn't
functional or
truely supported until sometime after 0.9.8.  I updated php to openSSL
1.0.2n,
which does support this mode.  I had to manually overwrite the
libeay32.dll and
ssleay32.dll library files with those from 1.0.2n.  It might prove helpful to
specify a minimum required version of openSSL.  (It might be beyond the
call of
duty, but very helpful, to tell folks how to update these two library
files, if
needed.  )
```

**Comment by paragonie-scott** [comment]
It should be safe to do AES-ECB and polyfill AES-CTR that way.

**Comment by defuse** [comment]
For the `typeError` issue: It's confusing to me that it works at all with PHP 5.4 on Travis-CI. I guess PHP can't determine that it has no idea what a `TypeError` is as it's parsing the file? Apparently, yes...

```
taylor@defuse:~$ php -v
PHP 5.6.33-0+deb8u1 (cli) (built: Jan  5 2018 15:46:26) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
taylor@defuse:~$ php test.php 
PHP Fatal error:  Class 'TypeError' not found in /home/taylor/test.php on line 2
```

Okay, this one's my fault because I missed it in my review of https://github.com/defuse/php-encryption/pull/350 (I erroneously assumed "tests passing on PHP 5.4" = "all code paths, even the ones the tests don't cover, will at least run on PHP 5.4"). Any ideas how to avoid having this problem in the future without having to manually look up the supported versions for every single use of a core language feature in every single pull request?

For the short array issue, let's bump the minimum officially-supported version to 5.6, since 5.4 and 5.5 are not receiving security updates anymore.

Does bumping the minimum version to 5.6 also solve the OpenSSL problem? I don't want to add and maintain a CTR polyfill so if not I think I'll just specify a minimum OpenSSL version.

**Comment by defuse** [comment]
I opened separate issues for these items: #383, #384, #385, #386.
