### ISSUE TITLE
Clean up the convoluted bash scripts for getting and running PHPUnit

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#397]
These got ugly in the 2.2 release because of the second parameter needed to tell `phpunit.sh` whether or not to save code coverage (which should only happen for `src/` not the the .phar).

**Comment by nikic** [comment]
To save the next person some time: The way to manually run the tests is to edit composer.json to remove PHPUnit 6 and 7, which are not actually supported by the test suite, and then run `vendor/bin/phpunit --bootstrap vendor/autoload.php test`.

**Comment by defuse** [comment]
Long live the kludge!
