### ISSUE TITLE
Add running Psalm to the release instructions

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#399]
This will save some time trying to fix failures on Travis

**Comment by paragonie-scott** [comment]
Do this locally.

```
composer require --dev "vimeo/psalm:dev-master"
vendor/bin/psalm
```

Psalm won't install on PHP 5.4 or 5.5, that's why it's not a dependency.

**Comment by defuse** [comment]
This has already been done: https://github.com/defuse/php-encryption/blob/master/docs/InternalDeveloperDocs.md#getting-and-using-psalm
