### ISSUE TITLE
Speed up the tests

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#400]
Ideally, the tests should take less than 60 seconds to run. It's probably fine to sacrifice test cases (e.g. encrypting super huge files) to speed up the tests, as long as we're sure it won't lose any line-coverage.

**Comment by paragonie-scott** [comment]
Suggestion: Conditionally mark slow tests as skipped rather than deleting them. https://phpunit.de/manual/6.5/en/incomplete-and-skipped-tests.html

**Comment by defuse** [comment]
Closing because the performance is acceptable
