### ISSUE TITLE
Upgrade from 1.2 to 2.2 without changing encryption key?

### ISSUE THREAD

**Issue by msarris** [defuse/php-encryption#404]
Is it possible to upgrade from version 1.2 to 2.2 without changing the encryption key? If not I'd have to first decrypt a lot of data, then upgrade the library, and then encrypt all the data again with a new key, which wouldn't be a very easy process.

If it's not possible, what other options do I have?

**Comment by defuse** [comment]
The new version will let you decrypt data from the old version using the `legacyDecrypt` function. It won't let you encrypt new data with the old key. So what you can do is upgrade, use `legacyDecrypt` to decrypt anything that's still encrypted with the old version, and then anything new that you encrypt will have to be encrypted with a new key. Here's some more info:

https://github.com/defuse/php-encryption/blob/master/docs/UpgradingFromV1.2.md
