### ISSUE TITLE
PHP 5.6 type error

### ISSUE THREAD

**Issue by dloewen** [defuse/php-encryption#407]
When using PHP 5.6 I get this error:

> Fatal error: Default value for parameters with a class type hint can only be NULL

Coming from line 43 of /paragonie/constant_time_encoding/src/Base32.php

The README says PHP 5.6 is supported, is that still the case?

**Comment by defuse** [comment]
PHP 5.6 is definitely supported. The tests appear to pass for PHP 5.6 on Travis (https://travis-ci.org/defuse/php-encryption/builds/370255505), so I wonder what's going on here. Hmm.

**Comment by defuse** [comment]
`php-encryption` doesn't depend on `paragonie/constant_time_encoding` so I wonder where that's coming from in your project. Could it be coming in as a dependency of something other than `php-encryption`?

**Comment by dloewen** [comment]
Ah, my mistake. Must have installed that separately.
