### ISSUE TITLE
invalid hex encoding loading from string or file

### ISSUE THREAD

**Issue by revmitcz** [defuse/php-encryption#411]
Based on your tutorial, I ran this command from the console :
`vendor/bin/generate-defuse-key`

It generated :
def000003d71bfd447036e8cc700fd437e8dc28bc4461fed7715af766bb314a805299b2b206ff08008aaf165c28e1817180fee784166e73f2045edeb5e44d2c04d04a0c4

I pasted that into a key.txt file and loaded it as per your example :
```
function loadEncryptionKeyFromConfig() {
    $keyAscii = file_get_contents(ROOT . 'public/key.txt');
    return Key::loadFromAsciiSafeString($keyAscii);
  }
```

And I get a 500 error of "Ciphertext has invalid hex encoding". I've also tried skipping the `file_get_contents` and using the key as a string directly :

```
function loadEncryptionKeyFromConfig() {
    $keyAscii = 'def000003d71bfd447036e8cc700fd437e8dc28bc4461fed7715af766bb314a805299b2b206ff08008aaf165c28e1817180fee784166e73f2045edeb5e44d2c04d04a0c4';
    return Key::loadFromAsciiSafeString($keyAscii);
  }
```

Is there a step I'm missing? Some other way I should be reading the file?

**Comment by paragonie-scott** [comment]
If this is indeed the problem: `vendor/bin/generate-defuse-key > key.txt` may alleviate errors caused by copying/pasting whitespace. You could also throw in an `rtrim()` after `file_get_contents()`.

**Comment by revmitcz** [comment]
@paragonie-scott that was the ticket. I didn't see any whitespace when I pasted it in as a string, but outputting to key.txt and using `rtrim(file_get_contents('key.txt'))` worked.

Thanks!
