### ISSUE TITLE
Disabling / hiding thrown exceptions

### ISSUE THREAD

**Issue by MisterBE2** [defuse/php-encryption#412]
Hello,

I have php code, which loads encrypted data before showing page. Data can be supplied by use via get request. So sometimes inputet string might not be decryptable, and when that happens I get php exception instead of my page. 

Is it possible to disable them?
I tried try catch, not working.

code example:

```
if(isset($_GET['recovery'])){
    if($_GET['trecovery'] != null && strlen($_GET['recovery']) > 0){
        $dataEncrypted = Crypto::decrypt($_GET['test_recovery'], $key);
        $data = json_decode($dataEncrypted, true);

        //Do stuff...
    }
}
```

**Comment by defuse** [comment]
What kind of exception does the code generate? Can you give a stack trace?

**Comment by defuse** [comment]
I just noticed in the
