### ISSUE TITLE
Composer dependencies problem with random_compat

### ISSUE THREAD

**Issue by pawelmysior** [defuse/php-encryption#413]
Hi,

I'm working on PHP version 7.1.19. I have a project that already has _paragonie/random_compat_ as a dependency, namely _ramsey/uuid_, which requires _paragonie/random_compat_ with version constraints as follows: _^1.0|^2.0|9.99.99_. Because I'm on PHP 7, when the _ramsey/uuid_ package was installed, the version _9.99.99_ of _paragonie/random_compat_ was installed.

Now I'm trying to install _league/oauth2-server_ in the same project. It requires _defuse/php-encryption_. But this package requires _paragonie/random_compat_ version _~2.0_. I already have the _9.99.99_ version of this package installed and Composer fails.

Would it be possible to change the version constraint of _paragonie/random_compat_ to _^2.0|9.99.99_ or maybe _>=2.0_?

**Comment by Buroob** [comment]
Hello,

Same here, problem when installing Laravel/Passport.

Thanks.

**Comment by paragonie-scott** [comment]
https://github.com/defuse/php-encryption/pull/408 <- there's already a PR for this :)

**Comment by pawelmysior** [comment]
Duh, sorry! I don't know how I missed that.
