### ISSUE TITLE
question: Can we use multiple encryption like this?

### ISSUE THREAD

**Issue by aerodynedev** [defuse/php-encryption#415]
`function secureSalary($basic_salary = 0, $allowance  = 0, $gross_salary  = 0, $total_deduction  = 0, $bonus  = 0, $claim  = 0, $net_salary  = 0)
  {
    $secret = getKey();
    $secret = Key::loadFromAsciiSafeString($secret);
 
    $encrypted_salary['basic_salary'] = Crypto::encrypt($basic_salary, $secret);
    $encrypted_salary['allowance'] = Crypto::encrypt($allowance, $secret);
    $encrypted_salary['gross_salary'] = Crypto::encrypt($gross_salary, $secret);
    $encrypted_salary['bonus'] = Crypto::encrypt($bonus, $secret);
    $encrypted_salary['claim'] = Crypto::encrypt($claim, $secret);
    $encrypted_salary['net_salary'] = Crypto::encrypt($net_salary, $secret);
    
    return $encrypted_salary;
  }`

**Comment by aerodynedev** [comment]
Well i guess i just answer this myself. 

Sure it can be use multiple times but the value cannot be 0.

If it is 0 make sure to stringfy it like this "0". 

Thanks.

**Comment by defuse** [comment]
Yes, you can encrypt multiple strings like that. But, you should be aware that there's nothing preventing someone with access to the ciphertext from swapping around the values (e.g. if they copied the `net_salary` ciphertext overtop of the `bonus` one, then they might get a really big bonus.)

**Comment by paragonie-scott** [comment]
Also: The easy way to work around that is to use a distinct key for each field.
