### ISSUE TITLE
hash_update() extremely slow

### ISSUE THREAD

**Issue by etkaar** [defuse/php-encryption#416]
I noticed that _hash_update()_ from PHP which is used in _File::decryptResourceInternal()_ is extreme slow. I have a file which is about 42 MiB large and in total the HMAC verification process needs more than 0.5 seconds.

I use a i7-4930K with 32 GB of RAM.

Here I only measured the verification process at step #2 which gives me about 0.25 seconds:
```
$total = 0;
[...]
$start = \microtime(true);
			
/* Recalculate the MAC (so far) and compare it with the one we
* remembered from pass #1 to ensure attackers didn't change the
* ciphertext after MAC verification. */
\hash_update($hmac2, $read);

$total += \microtime(true) - $start;
```

Is that normal?

**Comment by defuse** [comment]
[A different library's implementation of SHA256](https://www.cryptopp.com/benchmarks.html) can process 275MB/s with a less-fast CPU, so maybe there's some room for PHP's implementation of SHA256 to be improved. I'll come back to this in a couple weeks to make sure it's not something specific to this library.

**Comment by Kaulkwappe** [comment]
Are there any news? :)

**Comment by defuse** [comment]
No news yet. Clearly when I say "a couple X", the reader should multiply X by 10 :laughing:

**Comment by Kaulkwappe** [comment]
Since PHP 7.2 (and so libsodium) is more widely available now, what do you think about using BLAKE2? ☺️ Of course for those, who are still using an older PHP version we would need a polyfill. However, it would be very interesting because BLAKE2 should be way faster than SHA-256.

**Comment by defuse** [comment]
BLAKE2 would be a great option. This is low-priority for now (it might go in the next major release if there is one).

**Comment by defuse** [comment]
I'm closing this because I don't want to do a v3.0 release of this library. For anyone blocked by these performance issues I would suggest looking into alternatives like [Halite](https://github.com/paragonie/halite).

**Comment by etkaar** [comment]
The defuse library is pure art, but unfortunately I need to agree. Nowadays in new projects libsodium with its [\sodium_crypto_generichash()](https://www.php.net/manual/de/function.sodium-crypto-generichash.php) (using BLAKE2b) is the way to go.

**Comment by defuse** [comment]
I completely agree as well!
