### ISSUE TITLE
Question Loading the defuse..?

### ISSUE THREAD

**Issue by leolems** [defuse/php-encryption#419]
I had some trouble loading it properly..
I find it a bit odd to do it like this... i mean i have an autoloader in place, but all 
classes that are deeper are not initiated by the autoloader since they do not use the **new** keyword to create an object (and therefore are not automatically loaded).
Is that just my lack of knowledge, can someone please explain ... :)

so i made a helper called loadDefuse.php:

```
$basedir = __DIR__ . '/';
require_once($basedir.'Core.php');
require_once($basedir.'Crypto.php');
require_once($basedir.'DerivedKeys.php');
require_once($basedir.'Encoding.php');
require_once($basedir.'File.php');
require_once($basedir.'Key.php');
require_once($basedir.'KeyOrPassword.php');
require_once($basedir.'KeyProtectedByPassword.php');
require_once($basedir.'RuntimeTests.php');
require_once($basedir.'Exception/CryptoException.php');
require_once($basedir.'Exception/BadFormatException.php');
require_once($basedir.'Exception/EnvironmentIsBrokenException.php');
require_once($basedir.'Exception/IOException.php');
require_once($basedir.'Exception/WrongKeyOrModifiedCiphertextException.php');
```

to run it:
```
	require_once('./phpext/Defuse/loadDefuse.php');
	$Crypto = new Defuse\Crypto\Crypto;
	$pw = "somesecretkey";
	$ciphertext = $Crypto->encryptWithPassword("hello how are you, this is classified code", $pw);
```

**Comment by defuse** [comment]
Thanks! Yeah, we used to have an autoloader script included, but now there are [two supported ways of using this library](https://github.com/defuse/php-encryption/blob/master/docs/InstallingAndVerifying.md), the `.phar` file and composer.
