### ISSUE TITLE
Is it possible to do a SELECT in Mysql based on an encrypted value?

### ISSUE THREAD

**Issue by kramer65** [defuse/php-encryption#423]
I've got an existing code base which has been using this library for years. I now need to be able to select a record from the DB based on an encrypted value. I can do this by simply looping over al records in the DB and decrypting them:
```
$records = TheModel::all();
foreach ($records as $record){
    if ($record->thefield == $value) {  // thefield is decrypted in the model definition
        print $record->id;
    }
}
```
Unfortunately this isn't very scalable. The DB is still quite small, but growing quick so I need to change this code to actually do a query.

So I tried the following code:
```
$encryptedValue = \App\Crypt::encryptData($value);  // This uses \Defuse\Crypto\Crypto::encrypt()
$records = TheModel::where('thefield', $encryptedValue)->get();
foreach ($records as $record){
    print $record->id;
}
```
But this doesn't return anything. 
I found [this SO question](https://stackoverflow.com/questions/14505673/sql-query-with-binary-data-php-and-mysql) in which some ideas are suggested (adding '0x', wrap it in `BIN2HEX()` or `HEX()` or add an x before it (like `x'abcd'`).

I tried adding '0x' (which doesn't work), but I'm not sure how I could incorporate the other ideas in my code.

And mainly, I also wonder whether this is at all possible with this encryption. Could any brighter and more informed soul than me give me a hint on whether this is possible, and if so, how?

**Comment by paragonie-scott** [comment]
No, you can't. At least, not initially.

You could use [CipherSweet](https://github.com/paragonie/ciphersweet) to build blind indexes ([reference document](https://paragonie.com/blog/2017/05/building-searchable-encrypted-databases-with-php-and-sql)) from the plaintext in a quick and secure way, without having to migrate over to CipherSweet's encryption.

The problem you're going to run into is that **properly-implemented encryption uses [initialization vectors](http://www.cryptofails.com/post/70059609995/crypto-noobs-1-initialization-vectors)** which make the ciphertext indistinguishable from randomness. If you encrypt the same message twice, you get a different ciphertext.

You could store hashes (or KDFs), and optionally truncate them, but that's tantamount to rolling your own crypto and a working solution is already provided above, so it's probably not worthwhile to pursue a homebrew solution. (However, if you want to play with the searchable encryption design to learn, by all means please do so.)
