### ISSUE TITLE
Migrate from mcrypt

### ISSUE THREAD

**Issue by michaelbenker** [defuse/php-encryption#428]
Hey guys, first of alle, thanks for your good job.

Because of upgrading my software project to php 7.2, I´d like to encrypt secure secrets like e.g. paypal secrets in the future with php-encryption. This works. 

But in the passed I used mcrypt and so there are several mcrypt-encrypted strings in my database.
Everytime I load this data, I got a exception with "Ciphertext has invalid hex encoding."

Is there a way to migrate these "old" data? 
Thanx!

**Comment by paragonie-scott** [comment]
Write a migration script that does the following:

1. Use https://github.com/phpseclib/mcrypt_compat
2. Decrypt the old message into plaintext
3. Re-encrypt using this library
