### ISSUE TITLE
Question about shared encrypted data

### ISSUE THREAD

**Issue by nilsteampassnet** [defuse/php-encryption#429]
Dear team,

I have a question regarding the seckey.
I'm using defuse to encrypt some data that are shared by several users.
For this, I've created a seckey file that contains the key used for encryption and decryption.
THis file is store one a safe place on the server.
As the data is shared, I have not found any other way than using this common key file.
Of course, this is not perfect as if an attacker takes control on the server, he could potentially uncrypt all the data stored in the database (as he has the key and knows the program is using defuse).

I would like to know if you have a suggestion to improve this and if you have an idea of a kind of deviation of user key and the main seckey, that would permit such threat to not be possible.

Thank you for your nice library.

**Comment by defuse** [comment]
There are three approaches to this that are coming to mind.

The first and simplest is to just encrypt the same data multiple times with each users' different key. Or, more efficiently, encrypt the actual key with separate keys for each user so they decrypt the actual key and then use that to decrypt the data. 

The second is to have some sort of trusted service implementing access control to the data. The service verifies the user is authenticated and then decrypts the data itself and provides the decrypted data to the user over a secure connection. This will let you do things like audit access, revoke access in the future, have a central source for who supposedly has access to what, etc. The downsides are it's complex and it's a central point of failure.

Another is to treat the encryption key as if it's a token that grants the holder permission to access the data. Then, if a user wants to share that data with someone else, they just give them the encryption key. You can control read and write access separately using this approach by having different keys for signing and decrypting.

Which approach to use depends on the relationship between users' and the data. If it's always the exact same data shared among all users, then just giving every user the key is the way to go.

It sounds like this is all happening on the same server and you're looking for some level of security even if it gets hacked, so a service that implements access control wouldn't be a good option. It would be better to go with something like the third option where each user would log in, use their own key to decrypt a list of keys for everything they have access to, and then use those keys to access the data.

But if we're working in a model where the server is fully compromised, then the attacker will have ways around this (e.g. just sit there and wait for users to log in and steal the keys). The only way to fix that is to make sure the attacker never breaks in to the thing that has the keys -- whether that's an HSM plugged into the server or a separate server that exposes an authenticated, logged, monitored, and rate-limited API for doing the decryption. It will really depend on what your application is and how much budget/time you have for developing that kind of a system vs. the value of investing that budget/time into improving other aspects of your application's security.
