### ISSUE TITLE
getting blank pages...

### ISSUE THREAD

**Issue by jamieduk** [defuse/php-encryption#432]
I dont know how to get working im just getting blank pages and error checking reveals this
 Fatal error: Class 'PHPUnit_Framework_TestCase' not found in php-encryption/test/unit/CryptoTest.php on line 11

dont know how to fix this!!!!!

**Comment by larowlan** [comment]
Hi, that is a test, so unless you're running tests, you shouldn't be getting blank pages.

**Comment by Kaulkwappe** [comment]
> Fatal error: Class 'PHPUnit_Framework_TestCase' not found in php-encryption/test/unit/CryptoTest.php on line 11
This error message is from _PHPUnit_, not from _defuse_.

**Comment by larowlan** [comment]
These two statements contradict.

> I'm just getting blank pages

> The error message is from PHPUnit

Can you provide more info

* what you're trying to do
* what isn't working
