### ISSUE TITLE
2.2.1 Phar not working

### ISSUE THREAD

**Issue by slawn** [defuse/php-encryption#433]
Hi. I was using version 2.2.0 (phar file) without any issues. I've upgraded to 2.2.1 using composer and that was working fine, but now I wanted to switch to using phar again (2.2.1) but it's not working. This is the error I'm getting:

`[Fri Mar 29 14:04:53 2019] [error] [pid 2487] sapi_apache2.c(325): [PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\EnvironmentIsBrokenException' in phar:///defuse.encryption/defuse-crypto.phar/src/Core.php:259\nStack trace:\n#0 phar:///defuse.encryption/defuse-crypto.phar/src/Core.php(244): Defuse\\Crypto\\Core::ensureTrue(false)\n#1 phar:///defuse.encryption/defuse-crypto.phar/src/Core.php(101): Defuse\\Crypto\\Core::ensureFunctionExists('random_bytes')\n#2 phar:///defuse.encryption/defuse-crypto.phar/src/Key.php(26): Defuse\\Crypto\\Core::secureRandom(32)\n#3 phar:///defuse.encryption/defuse-crypto.phar/src/RuntimeTests.php(83): Defuse\\Crypto\\Key::createNewRandomKey()\n#4 phar:///defuse.encryption/defuse-crypto.phar/src/RuntimeTests.php(61): Defuse\\Crypto\\RuntimeTests::testEncryptDecrypt()\n#5 phar:///defuse.encryption/defuse-crypto.phar/src/Crypto.php(291): Defuse\\Crypto\\RuntimeTests::runt in phar:///defuse.encryption/defuse-crypto.phar/src/Core.php on line 259`

I've also noticed based on commits that the code didn't change that much while the phar version 2.2.0 was 62KB and the 2.2.1 is only 49.6KB - so much smaller and there were only 6 commits that wouldn't justify such file size change? Any suggestions?

**Comment by paragonie-scott** [comment]
I downloaded `v2.2.1` and rebuilt it from source, then compared the two Phars with [Pharaoh](https://github.com/paragonie/pharaoh). The only significant difference was the autoloader nonce:

```diff
diff --git a/tmp/phr_rMlQWD/vendor/autoload.php b/tmp/phr_Xvbouz/vendor/autoload.php
index fb0d87e..75d8707 100644
--- a/tmp/phr_rMlQWD/vendor/autoload.php
+++ b/tmp/phr_Xvbouz/vendor/autoload.php
@@ -4,4 +4,4 @@
 
 require_once __DIR__ . '/composer/autoload_real.php';
 
-return ComposerAutoloaderInit40d8adaf32b78561b9f4e4b36b0cc9a8::getLoader();
+return ComposerAutoloaderInit7aa4440d920cc9c31fcadfaafb59c91e::getLoader();
diff --git a/tmp/phr_rMlQWD/vendor/composer/ClassLoader.php b/tmp/phr_Xvbouz/vendor/composer/ClassLoader.php
index f474f51..6402a90 100644
--- a/tmp/phr_rMlQWD/vendor/composer/ClassLoader.php
+++ b/tmp/phr_Xvbouz/vendor/composer/ClassLoader.php
@@ -377,7 +377,7 @@ if (isset($this->prefixLengthsPsr4[$first])) {
 $subPath = $class;
 while (false !== $lastPos = strrpos($subPath, '\\')) {
 $subPath = substr($subPath, 0, $lastPos);
-$search = $subPath.'\\';
+$search = $subPath . '\\';
 if (isset($this->prefixDirsPsr4[$search])) {
 $pathEnd = DIRECTORY_SEPARATOR . substr($logicalPathPsr4, $lastPos + 1);
 foreach ($this->prefixDirsPsr4[$search] as $dir) {
diff --git a/tmp/phr_rMlQWD/vendor/composer/autoload_real.php b/tmp/phr_Xvbouz/vendor/composer/autoload_real.php
index eb9b477..6656957 100644
--- a/tmp/phr_rMlQWD/vendor/composer/autoload_real.php
+++ b/tmp/phr_Xvbouz/vendor/composer/autoload_real.php
@@ -2,7 +2,7 @@
 
 
 
-class ComposerAutoloaderInit40d8adaf32b78561b9f4e4b36b0cc9a8
+class ComposerAutoloaderInit7aa4440d920cc9c31fcadfaafb59c91e
 {
 private static $loader;
 
@@ -19,15 +19,15 @@ if (null !== self::$loader) {
 return self::$loader;
 }
 
-spl_autoload_register(array('ComposerAutoloaderInit40d8adaf32b78561b9f4e4b36b0cc9a8', 'loadClassLoader'), true, true);
+spl_autoload_register(array('ComposerAutoloaderInit7aa4440d920cc9c31fcadfaafb59c91e', 'loadClassLoader'), true, true);
 self::$loader = $loader = new \Composer\Autoload\ClassLoader();
-spl_autoload_unregister(array('ComposerAutoloaderInit40d8adaf32b78561b9f4e4b36b0cc9a8', 'loadClassLoader'));
+spl_autoload_unregister(array('ComposerAutoloaderInit7aa4440d920cc9c31fcadfaafb59c91e', 'loadClassLoader'));
 
 $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
 if ($useStaticLoader) {
 require_once __DIR__ . '/autoload_static.php';
 
-call_user_func(\Composer\Autoload\ComposerStaticInit40d8adaf32b78561b9f4e4b36b0cc9a8::getInitializer($loader));
+call_user_func(\Composer\Autoload\ComposerStaticInit7aa4440d920cc9c31fcadfaafb59c91e::getInitializer($loader));
 } else {
 $map = require __DIR__ . '/autoload_namespaces.php';
 foreach ($map as $namespace => $path) {
diff --git a/tmp/phr_rMlQWD/vendor/composer/autoload_static.php b/tmp/phr_Xvbouz/vendor/composer/autoload_static.php
index 3b47fb3..5d89821 100644
--- a/tmp/phr_rMlQWD/vendor/composer/autoload_static.php
+++ b/tmp/phr_Xvbouz/vendor/composer/autoload_static.php
@@ -4,7 +4,7 @@
 
 namespace Composer\Autoload;
 
-class ComposerStaticInit40d8adaf32b78561b9f4e4b36b0cc9a8
+class ComposerStaticInit7aa4440d920cc9c31fcadfaafb59c91e
 {
 public static $prefixLengthsPsr4 = array (
 'D' => 
@@ -23,8 +23,8 @@ array (
 public static function getInitializer(ClassLoader $loader)
 {
 return \Closure::bind(function () use ($loader) {
-$loader->prefixLengthsPsr4 = ComposerStaticInit40d8adaf32b78561b9f4e4b36b0cc9a8::$prefixLengthsPsr4;
-$loader->prefixDirsPsr4 = ComposerStaticInit40d8adaf32b78561b9f4e4b36b0cc9a8::$prefixDirsPsr4;
+$loader->prefixLengthsPsr4 = ComposerStaticInit7aa4440d920cc9c31fcadfaafb59c91e::$prefixLengthsPsr4;
+$loader->prefixDirsPsr4 = ComposerStaticInit7aa4440d920cc9c31fcadfaafb59c91e::$prefixDirsPsr4;
 
 }, null, ClassLoader::class);
 }
```

What probably happened is that the Phar included all of random_compat in v2.2.0, but it included v9.99.99 (which is a NOP version) in v2.2.1.

**Comment by paragonie-scott** [comment]
Unrelated: #434 will eliminate this noise for future diagnoses.

**Comment by slawn** [comment]
So can you tell me what is the best way to make the latest phar work? Like you said building from source produces similar result so don't think that will fix it as the only difference is the autoloader nonce? I'm in no rush - I can use composer version for now, but want to move to phar at some point. thanks

**Comment by paragonie-scott** [comment]
It just needs to be built on a PHP 5 machine. I can build one but I don't have access to Taylor's signing keys.

**Comment by paragonie-scott** [comment]
I've update the release with a file called `defuse-crypto-php5.phar`. Can you please verify that it works for you?

**Comment by slawn** [comment]
Just tried it - works as it should... thanks
