### ISSUE TITLE
Get Crypto.php on Composer

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#44]

**Comment by mfn** [comment]
Sorry, in part repeated what I wrote in https://github.com/defuse/php-encryption/issues/48#issuecomment-77101644 .

Additionally, the following symbols should probably be namespaced/prefixed too:
- `CannotPerformOperationException`
- `InvalidCiphertextException`

**Comment by defuse** [comment]
This is super high priority now as not being available on composer is stopping people from using it and forcing them to roll their own: https://github.com/Webiny/Framework/issues/39#issuecomment-80329052

In fact, I consider it a security vulnerability if people are rolling their own instead of using this, so I've added the security label.

**Comment by defuse** [comment]
Okay, it's now on composer: https://packagist.org/packages/defuse/php-encryption

I didn't do any namespacing due to the urgency of getting this out, but I opened #50 to do that.
