### ISSUE TITLE
project life

### ISSUE THREAD

**Issue by elovin** [defuse/php-encryption#452]
> The current version of php-encryption is v2.2.1. This library is expected to remain stable and supported by its authors with security and bugfixes until at least January 1st, 2021.

Does this only refer to the version 2.2.1 or will you abandon the "php-encryption" project after January 1st 2021 ?

**Comment by defuse** [comment]
The intent is to say "this library will receive security & bugfix updates until *at least* January 1st, 2021" (meaning the library as a whole, not just v2.2.1). I may decide to extend the lifetime by changing the README to say a later date but I haven't decided on that yet.

**Comment by elovin** [comment]
Thank you, for this clarification and your project.
