### ISSUE TITLE
Decryption too slow

### ISSUE THREAD

**Issue by tomason16** [defuse/php-encryption#453]
Hi,

I'm trying to figure out if there is a way to support very quick decryptions.
My use case: I'm keeping many sensitive encrypted entries in the database for each user. When the user logs in, we fetch those entries from the database, decrypt each of them and return them to the web interface.
As each decryption can take 7-10ms, having thousands or tens of thousands of such entries per user, means the user needs to wait 10-60 seconds (depends on the amount) for the data to return.

Sample code of how we are using the library:
To encrypt:
```
$this->key = Key::loadFromAsciiSafeString(...);
Crypto::encrypt($entry, $this->key); // To encrypt
```

To decrypt:
```
$this->key = Key::loadFromAsciiSafeString(...);
Crypto::decrypt($data, $this->key); // This can be executed in a loop thousands of times to return the data we need.
```

Any help will be very much appreciated. Thank you.

**Comment by defuse** [comment]
This is a side-effect of the encryption being written in PHP for backwards-compatibility and cross-system compatibility reasons. There are no current plans to optimize / speed up this library, I would suggest looking into alternatives like [Halite](https://github.com/paragonie/halite).
