### ISSUE TITLE
Release Tarballs

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#46]

**Comment by sarciszewski** [comment]
https://github.com/defuse/php-encryption/releases This one can be closed ;)

**Comment by defuse** [comment]
Sweet. I'll still need to sign them though. I don't think github lets you upload signatures to be displayed on that page?

**Comment by paragonie-scott** [comment]
http://fabien.potencier.org/signing-project-releases.html

**Comment by defuse** [comment]
Closing this because it's really unnecessary to publish tarballs. People can get it off github (signed tags) or composer.
