### ISSUE TITLE
How do i use this i wish to encrypt 1 file why is this so comlicated?

### ISSUE THREAD

**Issue by jamieduk** [defuse/php-encryption#462]
all i need to know s what file to include and how to use the comands below?

```
File::encryptFileWithPassword($inputFilename, $outputFilename, $password)

File::decryptFile($inputFilename, $outputFilename, Key $key)
```

also what the hell is key $key mean do i need to say key $key or just $key ? this is way too confusing! you need a proper how to! or a encrypt_file_test_example.php file so i can see how to use it instead of expecting ppl to guess how!!!

**Comment by etkaar** [comment]
With all due respect, but defuse is meant for programmers. This is not like HTML. You need to invest more time into PHP before using such stuff or you need another solution for your problem.

**Comment by defuse** [comment]
If you're looking for a tool to let you encrypt and decrypt files in a user-friendly way, I'd recommend https://github.com/FiloSottile/age.
