### ISSUE TITLE
Publicity / Advocacy

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#48]
We need to start some sort of campaign to get people using this library instead of either rolling their own or using an existing broken one.

Before we do this, though, we need to:

1. Get Crypto.php on Composer - #44. **[DONE]**
2. Get Crypto.php on PEAR - #45.
3. Release versioned downloadable tarballs (possibly through github) - #46.
4. Cryptographically sign releases - #47.
5. Version tagging - #34.

**Comment by mfn** [comment]
As part of #44 may I suggest to also adopt a namespace for it? A global `Crypto` doesn't sound uncommon. Something like `Defuse/Crypto/Crypto.php` maybe? thx for the library!

**Comment by sarciszewski** [comment]
The purpose of the library was, originally, to be a drop-in. Just copy Crypto.php to your project and use it. Autoloading, namespaces, etc. are an additional layer of complexity. Do we want this?

(I'd say yes, but I would also say branch/release/tag the pre-namespaced version before the change is made.)

**Comment by mfn** [comment]
Yes, I apologize for this straight suggestion. Only later, after reading the source code more thoroughly, the actual intention of the library occurred to me.

I think a major pro for something like composer is the benefit of easy/automatic updating of the users of this library. Not saying there are bugs in it, but especially for security, being up to date is very important.

**Comment by defuse** [comment]
Opened #50 about namespaces.

**Comment by xandersherry** [comment]
Once there is support for password-based usage, it should be proposed as an answer to this [How to encrypt in PHP, properly?](http://security.stackexchange.com/q/80888/12) on security.stackexchange.com so it can be socialized to the entire stackoverflow/stackexchange ecosystem.

**Comment by sarciszewski** [comment]
https://github.com/lizardhq/php_bcrypt_aes uses this and `password_compat()` :)

**Comment by sarciszewski** [comment]
Also, would you like to submit this to The League of Extraordinary Packages? https://thephpleague.com/

**Comment by paragonie-scott** [comment]
Would this project benefit from its own website?

**Comment by sarciszewski** [comment]
https://github.com/search?l=PHP&o=desc&q=encryption&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by Darkheir** [comment]
I also agree that submit the project to The League of Extraordinary Packages will give you a good publicity.

**Comment by defuse** [comment]
Everything mentioned in this ticket now has its own ticket, so I'm closing this one.
