### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by LocalHeroPro** [defuse/php-encryption#492]
Will that package compatible with coming PHP 8.1 changes: https://github.com/php/php-src/blob/php-8.1.0RC6/UPGRADING?

**Comment by NicolasCARPi** [comment]
It's working fine with php 8.1.

**Comment by defuse** [comment]
Yes, PHP 8.1 is supported (on master at least, but in case it doesn't work with the latest actual release, I'll be putting out a new release of master soon).

**Comment by defuse** [comment]
There's now a formal release supporting PHP 8.1: https://github.com/defuse/php-encryption/releases/tag/v2.4.0
