### ISSUE TITLE
Not compatible with PHP8.0 

### ISSUE THREAD

**Issue by Betacarotin** [defuse/php-encryption#496]
Can you please review/test/merge 495 for PHP8 compatibility?

**Comment by hamrak** [comment]
Is this project still alive? Last commit was on  28 Sep 2021. PHP 8.1 is now stable and 8.2 is comming very soon :)

**Comment by slawn** [comment]
> Is this project still alive? Last commit was on 28 Sep 2021. PHP 8.1 is now stable and 8.2 is comming very soon :)

I can see pull request with PHP 8 fix was approved now - not merged though. Did you tried it on PHP 8.1 or 8.2 by any chance? It says that this lib will be supported until at least Jan 2024 - so would hope it is or it will be...

**Comment by defuse** [comment]
The master branch currently works with PHP 8.0+, I'll be putting out a new formal release soon which should fix any issues for those using the latest release (which is now pretty old, sorry about that!)

**Comment by defuse** [comment]
There's now a formal release supporting PHP 8.0 and beyond: https://github.com/defuse/php-encryption/releases/tag/v2.4.0
