### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#50]
Include the crypto class and exception classes inside a namespace so we're less likely to conflict with other code.

**Comment by defuse** [comment]
This is blocking adoption: https://github.com/Webiny/Framework/issues/39#issuecomment-80982903

**Comment by sarciszewski** [comment]
Do you want to just use `namespace Defuse/Crypto`?

**Comment by mathewpeterson** [comment]
I would like to suggest complying with PSR-4 instead of just adding a namespace: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md

By adopting psr-4, it would also require separating out the symbols (classes, exceptions) into their own file.

**Comment by sarciszewski** [comment]
PSR-4 entails a slight refactor. Feel free to assign this to me ;)

**Comment by sarciszewski** [comment]
- Rule #4: The library should consist of a single PHP file and nothing more.

    > Some PHP encryption libraries, like libsodium-php [1], are not
    > straightforward to install and cannot packaged with "just download and
    > extract" applications. This library will always be just one PHP file
    > that you can put in your source tree and require().

PSR-4 is not compatible with this goal. PSR-4 compatible namespacing (`Defuse\Crypto\Crypto`) is though.

**Comment by josephdpurcell** [comment]
@sarciszewski / @defuse, forgive my ignorance, but is there a security reason to not follow PSR standards?

The reason for goal #4 (keeping all classes in a single file) appears to be for ease of use. But, "ease" is not determined by what is easy for `require()` but what is easy for an autoloader. The trend in PHP is to use an autoloader and the composer implementation which follows PSR is already widely adopted.

**Comment by sarciszewski** [comment]
There are a couple of ways we can do this:

1. Maintain two branches (e.g. `v.1` and `v.2`), the latter which is in PSR-4 format.
2. Fork the project to use PSR-4.
3. Forsake the original Rule 4, acknowledge that everyone is moving towards composer/PSR-4, get with the trends.

I'll leave this decision with @defuse, but I'm fine with either of the three.

**Comment by anlutro** [comment]
You could use a script that concatenates all classes/functions + a simple bootstrap.php into a single PHP file and distribute that as a binary file with each Github release, or just put it in a dist directory.

**Comment by defuse** [comment]
I haven't looked at it, but I think we should follow PSR-4. The intent of Rule #4 is not to keep it all in one file, rather it is to make sure you can just place the file (or files) alongside your code and use them. The intent is to avoid having to edit system-wide configurations, install extra software, etc.

So I'm happy with splitting it into multiple files.

**Comment by sarciszewski** [comment]
> You could use a script that concatenates all classes/functions + a simple bootstrap.php into a single PHP file and distribute that as a binary file with each Github release, or just put it in a dist directory.

Coming soon: Crypto.phar

Joking aside, I'll get on this ASAP.

**Comment by mathewpeterson** [comment]
Awesome, thank you all for the comments!

**Comment by paragonie-scott** [comment]
I'm happy to say that namespaces have bene implemented.

**Comment by mathewpeterson** [comment]
@paragonie-scott This looks pretty good.

I did leave a few minor comments in the PR though. 

Thanks to everyone who made this happen!
