### ISSUE TITLE
Move to AEAD (e.g. AES-GCM)

### ISSUE THREAD

**Issue by sarciszewski** [defuse/php-encryption#51]
Since we're using OpenSSL, can we switch from CBC + HMAC-SHA256 and instead use a built-in AEAD mode? (GCM is the one that I'm envisioning)

**Comment by xandersherry** [comment]
Unfortunately, the current PHP extension for OpenSSL does not support AEAD modes like GCM, as it has no mechanism to set or return the tag.

**Comment by sarciszewski** [comment]
http://3v4l.org/CHtkC

You're right. That's very annoying.
