### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#52]
The documentation shouldn't be a massive comment at the top of the file (that nobody will read anyway).

**Comment by paragonie-scott** [comment]
We have a couple options:

* [The Github Wiki](https://github.com/defuse/php-encryption/wiki)
* [Gitbook](https://www.gitbook.com/)

I'd like to see what other people prefer working with more.

**Comment by goldsky** [comment]
I'd suggest Github Wiki.

**Comment by Darkheir** [comment]
I just discovered this github repository but I'd suggest to use the github wiki for the documentation and create a github page to describe the projet : https://pages.github.com/

**Comment by NicolasCARPi** [comment]
:+1:

**Comment by wheelsandcogs** [comment]
A lot of projects just put example usage in their README which is usually enough for small libraries. A link to example.php would probably be enough to get peeps started.

**Comment by wheelsandcogs** [comment]
Also, it really needs some basic advice on how to safely store the encryption keys. In real-world usage the ciphertext is going to either be stored between requests or sent across the wire, so the key (or something that can generate the key) is eventually going to have to be stored in a config file / db.

I found #60 but there doesn't seem to be a conclusion?

**Comment by defuse** [comment]
@sarciszewski We have some things in `/doc/` now -- is that some standardized documentation thing?

**Comment by paragonie-scott** [comment]
It's a *start*. I wouldn't call it anywhere near complete.

**Comment by defuse** [comment]
Make sure we document that only PHP >= 5.4 is supported, since that's what we're testing.

**Comment by defuse** [comment]
Make sure to document the stacktrace-leaks-your-keys thing, now that the exception handler hack is gone.

**Comment by defuse** [comment]
See this comment: https://github.com/defuse/php-encryption/issues/94#issuecomment-166364380

**Comment by defuse** [comment]
See this too: https://github.com/defuse/php-encryption/issues/168

**Comment by defuse** [comment]
And see: https://github.com/defuse/php-encryption/issues/161

**Comment by defuse** [comment]
Things we need to document:

- Development environment: "What do I need to do before being able to make changes to the code in this library?"
- Dependencies: "What do I need to install to use this library?"
- Behavior: "What does this library do, what does it guarantee, etc."
- Usage: "How do I use this library to do certain things, example use cases like deriving a key from the user's login password and encrypting their data with that.?"

**Comment by defuse** [comment]
Copying this down so I can erase my whiteboard:

```
docs/
    Installing.md: How to verify signatures and install (two ways: .phar, composer)
    Class-Crypto.md
    Class-Key.md
    Class-*.md (one for every public-facing class)
    ImplementationDetails.md: Explain to a non-code-reading cryptographer how it works.
    example/encutil.php: The command-line file enc/dec utility I'm writing as an example.
```

Maybe more? FAQ, etc.? Things to address those comments I linked above?

**Comment by defuse** [comment]
Make sure to use the term "LTS" instead of "maintenance mode." Also, be specific about the end of life date. I can commit to security/bugfixes for v2 until Jan 1 2019 (with time extensions possible).

**Comment by defuse** [comment]
This will be a great test of our documentation and usability: https://github.com/defuse/php-encryption/issues/217#issuecomment-207136688

**Comment by defuse** [comment]
Make sure to document how to upgrade from 1.2 to 2.0. https://github.com/defuse/php-encryption/pull/226#issuecomment-208080699

**Comment by defuse** [comment]
Last nontrivial ticket!

**Comment by defuse** [comment]
Okay, just have to document the `File` class which will be a lot of copy-and-paste, then write the instructions to install/verify the code.

**Comment by defuse** [comment]
Done! Ready for review.

**Comment by defuse** [comment]
Doc review finished.
