### ISSUE TITLE
Best Mysql field type to store encrypted data

### ISSUE THREAD

**Issue by bab55z** [defuse/php-encryption#56]
Hello!
I am wondering about what is the best type i should choose for the field i use to store the encrypted data, i chose varchar but encrypted data seems to be corrupted after it is stored in mysql. i Planing to use a blob type, is this a good choice and what size should choose also. I planning to encrypt integers only which should not exceed 8 or 9 digits,
my Mysql database uses innoDB engine with utf8_general_ci

thanks

**Comment by paragonie-scott** [comment]
MySQL tends to munge everything, so I would definitely `base64_encode()` it before storing and `base64_decode()` after retrieving.

**Comment by bab55z** [comment]
works great! thanks @paragonie-scott

**Comment by goldsky** [comment]
this should be in the doc

**Comment by paragonie-scott** [comment]
@goldsky That's a fair point. We're going to be discussing documentation in #52 if you would like to follow that discussion and weigh in with your own opinions.
