### ISSUE TITLE
Storing & Retrieving Encrypted Data

### ISSUE THREAD

**Issue by dhope0000** [defuse/php-encryption#59]
Hello this is my first time posting on Github so excuse me if i format the issue wrong!

 Using the "example.php" provided with the current version i added the following code/statements;

<Generate keys & encrypt the text>

$encode = base64_encode($ciphertext);
 
$stmt = "INSERT INTO test (test) VALUES (:test)";
		
$y = $pdo->prepare($stmt);
$y->execute(array(
':test'=> $encode
));

$sth = $pdo->prepare("SELECT test from test where id = '1' ");
	$sth->execute();
	$result = $sth->fetch();
	$data = $result['test'];
 
$decode = base64_decode($data);

<Decrypt >

This returns;

"DANGER! DANGER! The ciphertext has been tampered with!" 

This could be just me being new to using encryption with PHP or it could be an issue with the code itself but i was told i should bring it up here;

"http://stackoverflow.com/questions/30226517/encrypting-data-using-the-defuse-php-encryption?noredirect=1#comment48595894_30226517"

Thanks again.

**Comment by sarciszewski** [comment]
Before the insert query, what is `strlen($encode)`?

After the select query, what is `streln($data)`?

**Comment by dhope0000** [comment]
They both have the strlen "88"

**Comment by paragonie-scott** [comment]
Could you pull the latest version and `var_dump()` them?

**Comment by defuse** [comment]
Closing this because I'm certain it's not a problem with the library. It's amazing how often issues like these come up and it always results from the ciphertext getting corrupted somehow.
