### ISSUE TITLE
Searching on Encrypted Database

### ISSUE THREAD

**Issue by goldsky** [defuse/php-encryption#65]
I've [googled](https://www.google.com/search?q=search+on+encrypted+database) and found theories and [CryptDB](http://css.csail.mit.edu/cryptdb/).

The most sensible approach I found is by indexing keywords and connecting them to the encrypted records, so the searching is actually getting data from those index db, without decrypting the records.

I'd like to hear some thought of the practical way of doing this, or not.
Especially, because this repo is about (en|de)cryption and followed by implementers.

This can be a challenging topic for [Documentation](https://github.com/defuse/php-encryption/issues/52).

**Comment by defuse** [comment]
Despite how interesting (and important) searching encrypted databases is, I think it's out of scope for this library at the moment, so I'm going to close this issue.
