### ISSUE TITLE
Use random_bytes() for key generation!

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#68]
For PHP 7.0.0 and above, [`random_bytes()`](https://secure.php.net/random_bytes) should be used instead of [`openssl_random_pseudo_bytes()`](https://github.com/paragonie/random_compat/issues/5) (see issue).

We've written a polyfill called [random_compat](https://github.com/paragonie/random_compat) which should polyfill both APIs here. Would it make sense to consolidate all of the CSPRNG effort into that project instead and just add it as a dependency?

**Comment by defuse** [comment]
What would adding `random_compat` as a dependency look like? How much harder would it make it to get/use this library (both in the case where the user is extracting zip files and in the case where they're using a tool like composer)?

**Comment by paragonie-scott** [comment]
Composer: Easy, one-line patch.

Zip file: Would require some copypasta and adding a line to the autoloader.

**Comment by paragonie-scott** [comment]
To clarify: I can package random_compat v1.0.0 with the php-encryption v2.0.0 tarball when it's released, and just add it to the composer.json file for Composer users.

(More PHP developers are going to be using Composer as time goes on.)

**Comment by paragonie-scott** [comment]
random_compat v1.0.0 is available if you would like to review it before considering its inclusion.

**Comment by paragonie-scott** [comment]
And by that, I of course mean v1.0.6. :)

**Comment by defuse** [comment]
Unfortunately, I think using `random_compat` would make it too hard to "copy paste" this library. You'd need to use composer, right?

Is there any security reason not to use `openssl_random_pseudo_bytes()`?

**Comment by defuse** [comment]
Oh, we could have a script bundle it into a zip file... Hmm... We'll have to think about this (but for now I say no, not in v2.0).

**Comment by paragonie-scott** [comment]
(I can make the .phar builder include this in the bundle, too.)

**Comment by defuse** [comment]
Let's plan to support it for 2.1 but not do it quite yet.

**Comment by paragonie-scott** [comment]
Last year:

> Is there any security reason not to use `openssl_random_pseudo_bytes()`?

It turns out, yes!

https://github.com/ramsey/uuid/issues/80

**Comment by defuse** [comment]
[rant]Oh for fuck's sakes. I'm going to enjoy my two-year vacation to study quantum computing so much. I am sick of shit like this and can't wait to take a break from it.[/rant]

We need to reconsider this for 2.0.

**Comment by defuse** [comment]
A prerequisite is that I should do a quick audit of random_compat.

**Comment by defuse** [comment]
I kind of wonder if the wording in the openssl documentation is just like the comparison between "/dev/urandom" and "/dev/random" ... but unless RAND_bytes() blocks I doubt it's the same comparison.

**Comment by defuse** [comment]
I wonder how this interacts with the .phar stuff... would the .phar include random_compat?

**Comment by paragonie-scott** [comment]
random_compat.phar is only ~40KB in size.

**Comment by defuse** [comment]
Done.
