### ISSUE TITLE
Base exception class (and better error messages)

### ISSUE THREAD

**Issue by chriseskow** [defuse/php-encryption#70]
Any reason why there isn't a base exception class (or marker interface) that all of the library-specific exceptions inherit from? That would make it trivial to catch any crypto-related exception at once, if we don't care about the details of what happened.

On the same topic, it would be nice if the exceptions were either more numerous and specific to the individual error case, and/or had better error messages. There are a lot of cases that throw exceptions in the code, but the majority have no error message and are one of just three generic classes.

Thoughts?

**Comment by paragonie-scott** [comment]
See #29 as well :)

**Comment by defuse** [comment]
I added a base `CryptoException` exception class so that it's possible to catch all three at once. I also added better messages in the places where they're relevant.

**Comment by chriseskow** [comment]
Thanks!
