### ISSUE TITLE
Possible openssl_get_cipher_methods() memory leak

### ISSUE THREAD

**Issue by im-bart** [defuse/php-encryption#72]
While batch processing a few thousand Doctrine entities, calling `openssl_get_cipher_methods()` on every `encrypt()` (it's also called from `decrypt()`) causes my application to slow down or hit the memory_limit (obvious work-around is commenting it for now). Any reason (since `$method` is based on constants) this cannot be part of the `runtimeTest()` method? I'm using a single instance and no other part of the application is really hogging memory, hence my work-around is disabling that call.

**Comment by defuse** [comment]
Yeah, I think we should just have *one* constant, set to `aes-128-cbc`. Separating them makes it seem like it's okay to change them independently, i.e. to `rc4-cbc`, when it isn't. Then we can get rid of that call, and if for some reason someone changes that constant to something bad, the other OpenSSL calls will fail.

**Comment by defuse** [comment]
Made the change in 24e85c92efe1dc65645b861852e83cf5c8b7e2ee

**Comment by defuse** [comment]
@im-bart Can you confirm whether or not the fix solves your issue? Thanks!

**Comment by im-bart** [comment]
Yeah, running `openssl_get_cipher_methods()` once is enough. I've also removed that code from decrypt(), see PR https://github.com/defuse/php-encryption/pull/75

**Comment by defuse** [comment]
Thanks!
