### ISSUE TITLE
Use of statics prohibits testing/injection/mocking capabilities

### ISSUE THREAD

**Issue by Rican7** [defuse/php-encryption#79]
This library uses all static methods, and while some of them make sense, its really too bad that the library's Crypto class can't be used as an injectable instance. Currently, testing services that make use of this library means running expensive crypto hashing algorithms that slow down a unit testing feedback loop.

Switching to non-statics would also allow for certain configurations to be used, if certain aspects needed to be overrided (I know, likely not suggested), for example providing a different hash function but defaulting to the current constant `sha256`.

Thank you for this great library and for considering this issue.

**Comment by chriseskow** [comment]
In PHP you can call static methods on an object instance, so you can in fact instantiate the Crypto object:

```php
$crypto = new \Defuse\Crypto\Crypto();
$ciphertext = $crypto->encrypt($cleartext, $key);
```

That said, I agree that instance methods would be better, and it would be great to be able to typehint against an interface and swap out the implementation:

```php
interface CryptoInterface
{
    public function createNewRandomKey();
    public function encrypt($plaintext, $key);
    public function decrypt($ciphertext, $key);
}
```

If statics must be kept for BC purposes, then we can use statics in the interface instead:

```php
interface CryptoInterface
{
    public static function createNewRandomKey();
    public static function encrypt($plaintext, $key);
    public static function decrypt($ciphertext, $key);
}

**Comment by paragonie-scott** [comment]
In PR #78 the `File` class is going to inherit from `\Defuse\Crypto\StreamInterface`.

**Comment by Rican7** [comment]
@chriseskow 
> In PHP you can call static methods on an object instance

Yea, that's not so much a rule as it is an implementation detail, though, which is really improper and should be avoided.

> That said, I agree that instance methods would be better, and it would be great to be able to typehint against an interface and swap out the implementation

Absolutely. That would be ideal.

> If statics must be kept for BC purposes, then we can use statics in the interface instead

That shouldn't be necessary. A non-static interface could be created with a delegate implementation to preserve BC, so we can still code against the new style without breaking BC. Something like this:


```php
interface CryptoInterface
{
    public function createNewRandomKey();
    public function encrypt($plaintext, $key);
    public function decrypt($ciphertext, $key);
}

/**
 * A delegate pass-thru that provides a default implementation of the
 * CryptoInterface to allow for keeping BC of the original Crypto class
 */
final class DelegateCrypto implements CryptoInterface
{
    public function createNewRandomKey()
    {
        return Crypto::createNewRandomKey();
    }

    public function encrypt($plaintext, $key)
    {
        return Crypto::encrypt($plaintext, $key);
    }

    public function decrypt($ciphertext, $key)
    {
        return Crypto::decrypt($ciphertext, $key);
    }
}
```

**Comment by Rican7** [comment]
@paragonie-scott yea, that only covers the `File` class, though, and even then that's still using static methods, which is awkward for the interface usage.

**Comment by paragonie-scott** [comment]
Here's the thing: Most of the people who **use** this library should **NEVER** swap out an implementation. It's meant to be an opinionated, secure-by-default, "don't stick your fingers in it and mess it up" library that solves a problem that most developers can't be trusted with for them.

I don't know how @defuse feels about making this class implement an interface, because users might think that gives them license to roll their own in production.

We might be better off moving to a namespace with functions.

**Comment by Rican7** [comment]
> We might be better off moving to a namespace with functions

That would make it even harder to test. :/

**Comment by paragonie-scott** [comment]
> if certain aspects needed to be overrided (I know, likely not suggested), for example providing a different hash function but defaulting to the current constant `sha256`.

See: https://github.com/defuse/php-encryption/blob/6e13003c1edf28e8b6967a2cf17a5f20053b589a/src/Crypto.php#L37-L50

It's not just *not recommended*, it's something that is strongly discouraged.

If we add an interface, we run the risk that non-crypto-expert developers might think it's okay to ignore this advice and implement their own library that implements the interface, but uses Rindael-256 in ECB mode with `md5($key)` as the encryption key, and passes `md5(md5($key))` as an IV (which is discarded) and doesn't authenticate the ciphertexts properly.

The full unit test for my proposal for v2.0.0 suite takes less than 10 seconds to run, including Travis overhead and file operations. I don't think the hashing algorithms are that expensive.

**Comment by chriseskow** [comment]
@paragonie-scott I'm not sure if anyone would be tempted to use this library just for the interface and completely ignore the implementation classes. I think that would be more likely the case if the interface was provided in a separate package or a PSR or something.

Anyway, I do understand your concern about misuse.

**Comment by paragonie-scott** [comment]
> I'm not sure if anyone would be tempted to use this library just for the interface and completely ignore the implementation classes.

See https://stackoverflow.com/a/30159120/2224584 for more about users going out of their way to not follow best practices.

**Comment by pulyaevskiy** [comment]
One can always create his/her own `CypherInterface` to abstract from this library and have `DefuseCryptoCipher` implementation and put there whatever logic needed for his/her application. Test it separately, of course.

It seems like all this `static`s are more of an issue for developers of this library, but not really for consumers.

**Comment by Rican7** [comment]
@paragonie-scott If someone wanted to skirt the implementation of this library, then they could do that at any time by calling a different method/class/function, haha. Providing an interface doesn't mean that it'll be any "easier" to re-implement the API, it just will make it easier to swap out for a mock when gluing together code that you can't control (like for frameworks). It makes it more re-usable.

I understand what you're saying to a degree, but to ignore an interface construct just because you want to force an implementation just doesn't make a lot of sense as a reusable library. Reduce configuration of your implementation (which you already have with constants), don't force it through other means or it just won't be used (the easiest way to circumvent the implementation, haha), you know?

**Comment by paragonie-scott** [comment]
Sure, once someone has a copy of the code they can surgically alter it to
their heart's content.

I can't speak for Taylor here, I might be way off. Did you see the comments
on the StackOverflow issue I linked before?

Someone was so dead set on using a password that they refused to listen to
reason. That worries me immensely

How do you propose you would use the interface, should it be added? I'm
curious to see exactly what you are envisioning so I may understand the
full implications.

**Comment by Rican7** [comment]
@paragonie-scott as my original issue mentioned, for testing. :)

Quickly typed example:

```php
final class ExternalAccountConnectionService {
    private $crypto;

    public function __construct(CryptoInterface $crypto = null) {
        // Default to the delegate
        $this->crypto = $crypto ?: new DelegateCrypto();
    }

    public function connect($external_account_type, $username, $password)
    {
        // ... Query external service for user with credentials, verifying that they're valid
        
        // Encrypt the password (obviously catch exceptions and use multiple keys, etc)...
        $encrypted = $this->crypto->encrypt(
            $password,
            $this->crypto->generateNewRandomKey()
        );

        // ... Store the encrypted version

        // ... Do other work

        return true;
    }
}


// In tests...

class ExternalAccountConnectionServiceTest extends PHPUnitSomethingOrWhateverTestCaseThing
{
    public function testConnect()
    {
        $service = new ExternalAccountConnectionServiceTest(
            new MockCryptoThingThatReturnsASimpleString()
        );

        $this->assertTrue($service->connect());
    }

    /**
     * @expectedException BlahBlahBlahExampleException
     */
    public function testConnectFailsWithCryptoException()
    {
        $service = new ExternalAccountConnectionServiceTest(
            new MockCryptoThingThatThrowsException()
        );
    }
}
```

**Comment by Rican7** [comment]
Again, my real issue is more the fact that this uses static methods than anything else. An interface would just make it easier to code against.

**Comment by paragonie-scott** [comment]
What if I write a PR that adds an interface and non-static class that looks
like:

    class Concrete implements StringCryptoInterface {
        public function encrypt($message, $key)
        {
            return Crypto::encrypt($message, $key);
        }
    }

That would allow you to mock it without creating a thousand merge conflicts
with the existing PR. Would that satisfy your needs?

**Comment by chriseskow** [comment]
@paragonie-scott Is that any different from @Rican7's `DelegateCrypto` example above?

**Comment by paragonie-scott** [comment]
I dunno. I'm on my phone which is pretty terrible for code review atm

**Comment by paragonie-scott** [comment]
Upon reflection, nope. :)

I'll draft a PR real quick.

**Comment by paragonie-scott** [comment]
@Rican7 Apologies, I thought you were recommending that we rewrite Crypto to not use static methods. Having an class we can instantiate that extends an interface so you can mock it doesn't change the underlying library at all and therefore causes no harm that developers aren't already capable of. I see now that I was wholly mistaken.

**Comment by Rican7** [comment]
@paragonie-scott No problem, bud! Yea, I was just trying to suggest a way to improve usability (for tests, etc) of the library. Rewriting the `Crypto` class to use non-statics would be a major BC break and would be a headache for the users of the lib. While it might stand the benefit in a major release refactor, it would be harmful to do in 1.x.

I wouldn't say you were wholly mistaken. You brought up some very valid points. Thanks for taking my suggestion into consideration and for being open to the change.

Great work here all around. :+1:

**Comment by defuse** [comment]
I'm not sure what the status of this is, but I'm *not* putting it in the 2.0 milestone.

**Comment by defuse** [comment]
This will come in 2.1, probably.

**Comment by defuse** [comment]
I'm rejecting this change, especially since I don't have time to spend on this library and want it to go into maintenance mode, for the reasons described here https://github.com/defuse/php-encryption/pull/81#issuecomment-204827652
