### ISSUE TITLE
Create Key container class that prevents user from stupid mistakes

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#80]
https://github.com/paragonie/halite_cookie/blob/master/src/Key.php

[Motivation](https://stackoverflow.com/a/30159120/2224584):

> How would I use the php-enctyption plugin with a custom passphrase? I've tried self defining one, but it doesn't match the required format.
> 
> --------------------------------------------------------
> 
> So you can recover the data using a custom password instead of the random one they generate. I found that any 16 character password will work for this though
> 
> --------------------------------------------------------
> 
> Is this the proper usage? $key = Crypto::binToHex("PassPhrase");

**Comment by joepie91** [comment]
Elaboration: the easy way should be the correct way.

Thus, something that is potentially unsafe to do without the correct competence level, should be made artificially hard and unintuitive - this will steer away newbies, and create an incentive for them to say "whatever, I'll just use the [secure] default".

**Comment by pnowosie** [comment]
I like this idea, also we would add static method to KeyContainer which derives it from password, like in #5

**Comment by paragonie-scott** [comment]
The class I referenced has a `derive()` method that uses scrypt (courtesy of Libsodium).

**Comment by paragonie-scott** [comment]
Note: This is precisely what Halite does, for libsodium users. We can probably punt this to v3.

**Comment by defuse** [comment]
This is easy to do (literally just add a `Key` class, with methods for serialize/deserialize, and then require all `$key` arguments to be instances of `Key`), and has huge usability benefits, so I want it in v2.0.

**Comment by defuse** [comment]
I'll do this. :)

**Comment by defuse** [comment]
This is done in #116.
