### ISSUE TITLE
CannotPerformOperationException not found

### ISSUE THREAD

**Issue by salvoselene** [defuse/php-encryption#84]
The class name in file CannotPerformOperationException.php misses the Esception end part, i dunno if it's really an error or if i've done something stupid, but renaming the class in the file solves the problem

**Comment by paragonie-scott** [comment]
Related to this perhaps? https://github.com/defuse/php-encryption/commit/d2c33279e31d5f3d4b74a82139b6ce56d551965b

**Comment by salvoselene** [comment]
Sorry, i didn't explain well, my fault.
I got a class not found error from line 87 in file Crypto.php

 85       if (self::ourStrlen($key) !== self::KEY_BYTE_SIZE)
 86       {
-87            throw new Ex\CannotPerformOperationException("Key is the wrong size.");
 88       }

Thinked about an error of mine (edited the autoload.php), but then i opened the file 
'CannotPerformOperationException.php' and found:

 4         class CannotPerformOperation extends \Defuse\Crypto\Exception\CryptoException

Edited the class name to the one throwed at line 87 in Crypto.php and went well.

I don't know if is a indirect problem of a naming redesigning or a simple mistake, but i think the second one

**Comment by DevarityGames** [comment]
I'm getting the exact same error. I can't even use this now, and I need the library urgently.

**Comment by paragonie-scott** [comment]
Yep, that was a typo. Should be fixed now.

**Comment by defuse** [comment]
Closing since I think it's fixed (re-open if it isn't)
