### ISSUE TITLE
Add a license.txt

### ISSUE THREAD

**Issue by larowlan** [defuse/php-encryption#91]
It is unclear from the project repo and code what the exact license is.
I was thinking of building a Drupal module containing this, but there is a restriction on adding third-party code to Drupal.org that isn't GPL2 compatible.

Can you clarify the license via a LICENSE.txt?

**Comment by jerrygrey** [comment]
There is a license in [the PHP file](https://github.com/defuse/php-encryption/blob/master/src/Crypto.php), if that helps.

**Comment by larowlan** [comment]
Thanks!

**Comment by badjava** [comment]
@larowlan FYI there is a Drupal module using this already:

https://www.drupal.org/project/real_aes

**Comment by larowlan** [comment]
Nice!

On 21 September 2015 at 14:54, Chad DeGroot <notifications@github.com>
wrote:

> @larowlan <https://github.com/larowlan> FYI there is a Drupal module
> using this already:
>
> https://www.drupal.org/project/real_aes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/defuse/php-encryption/issues/91#issuecomment-141877746>
> .
>



-- 
Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au
