### ISSUE TITLE
Version 2 - use CTR mode?

### ISSUE THREAD

**Issue by paragonie-scott** [defuse/php-encryption#93]
Per [Thomas Ptacek](https://twitter.com/tqbf/status/653379188460752896).

Since my proposal for version 2 is already changing the protocol (with a `legacyDecrypt()` function so people can migrate to 2.0.0) by adding version tagging, and HKDF salting, should we also consider upgrading to AES-128-CTR? (Or even AES-256-CTR if people *really* want it? It's not a meaningful distinction for me.)

With HKDF salting, the probability of a `(key, nonce)` pair reuse is even less likely: Even if the nonce is repeated (i.e. after 2^64 messages), the derived key for that particular message will almost certainly be different. This should be sufficiently safe.

The `File` API already uses CTR, because it makes more sense in that context than CBC.

Ref #78

**Comment by defuse** [comment]
+1 on using CTR mode everywhere if we're already using it in at least one place. Then we can get rid of the PKCS#7 padding code.

**Comment by paragonie-scott** [comment]
I'll update #78 then.
