### ISSUE TITLE
Is autoload.php a source of LFI?

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#95]
`autoload.php` constructs a path name from a class name and then requires that file. That seems risky. Does it create LFI vulnerabilities somehow? Can attackers invoke that function if there's an unserialize vulnerability?

Would a whitelist, i.e. just a `switch` statement, be enough?

**Comment by paragonie-scott** [comment]
> Can attackers invoke that function if there's an unserialize vulnerability?

I hadn't even considered this to be honest. It wouldn't allow directory traversals but could lead to undefined behavior. A whitelist is in order.

**Comment by paragonie-scott** [comment]
#96 is a proposed hardening strategy.

**Comment by paragonie-scott** [comment]
#140

**Comment by defuse** [comment]
Fixed.
