### ISSUE TITLE
Remove the exception handler override

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#97]
We overrode exceptions to prevent keys from being displayed in stack traces. Let's not do that anymore, but instead just make the risk clear in the documentation.

**Comment by defuse** [comment]
Removed in #116, and added relevant comments to #52 and #100.

**Comment by paragonie-scott** [comment]
Also, using a key object rather than a string might prevent that from leaking in every area other than the stack trace triggered by the key object's constructor. :)

**Comment by defuse** [comment]
Good point! I'll test that.

**Comment by defuse** [comment]
Opened #126 to test that.
