### ISSUE TITLE
Submit to the League of Extraordinary Packages

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#98]
After v2.0 release, submit it to that thing.

**Comment by paragonie-scott** [comment]
:+1: cc @alexbilbie

**Comment by enygma** [comment]
:shipit: :+1:

**Comment by alexbilbie** [comment]
Can you submit it to the [League mailing list](https://groups.google.com/forum/#!forum/thephpleague) please

**Comment by paragonie-scott** [comment]
https://groups.google.com/forum/#!topic/thephpleague/Qzh4rR442NY Started the conversation here :)

**Comment by defuse** [comment]
Removed this issue from the v2.0 label and milestone since it's not a blocker on release (it can happen after, potentially many months after, and I leave it up to @paragonie-scott to pursue this if he wishes, I won't put time into it.)

**Comment by paragonie-scott** [comment]
I'd say close it then. It's clear that I'm not welcome on their "turf".

**Comment by defuse** [comment]
+1 to close it
