### ISSUE TITLE
Switch to AES-256.

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#99]
We might as well switch to AES-256, even though it isn't necessary.

(I'll do this)

**Comment by paragonie-scott** [comment]
Doesn't the same NIST document have AES-256-CTR test vectors?

**Comment by defuse** [comment]
Yeah, it should. I have that weird kind of irrational laziness preventing me from opening another tab and searching for it right now. :P

**Comment by paragonie-scott** [comment]
## F.5.6 CTR-AES256.Decrypt

    Key 
		603deb1015ca71be2b73aef0857d7781
        1f352c073b6108d72d9810a30914dff4
		
	Init. Counter 
		f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
	
#### `Block #1`

	Input Block 
		f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
    Output Block 
		0bdf7df1591716335e9a8b15c860c502
	Ciphertext 
		601ec313775789a5b7a7f504bbf3d228
    Plaintext 
		6bc1bee22e409f96e93d7e117393172a

#### `Block #2`

	Input Block
		f0f1f2f3f4f5f6f7f8f9fafbfcfdff00
	Output Block
		5a6e699d536119065433863c8f657b94
	Ciphertext
		f443e3ca4d62b59aca84e990cacaf5c5
    Plaintext 
		ae2d8a571e03ac9c9eb76fac45af8e51

#### `Block #3`

	Input Block 
		f0f1f2f3f4f5f6f7f8f9fafbfcfdff01
	Output Block 
		1bc12c9c01610d5d0d8bd6a3378eca62
	Ciphertext
		2b0930daa23de94ce87017ba2d84988d
	Plaintext
		30c81c46a35ce411e5fbc1191a0a52ef

#### `Block #4`

	Input Block
		f0f1f2f3f4f5f6f7f8f9fafbfcfdff02
	Output Block 
		2956e1c8693536b1bee99c73a31576b6
	Ciphertext 
		dfc9c58db67aada613c2dd08457941a6
	Plaintext 
		f69f2445df4f9b17ad2b417be66c3710

**Comment by defuse** [comment]
Thanks!

**Comment by defuse** [comment]
This is done in #116.
